const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{execFileSync}=require('child_process');
const root=path.resolve(__dirname,'../..');
const specialties=[{id:11,name:'Cardiologia',active:true},{id:12,name:'Medicina dello sport',active:true},{id:13,name:'Dermatologia',active:true},{id:14,name:'Specialità archiviata',active:false}];
const server=http.createServer((req,res)=>{
 const u=new URL(req.url,'http://localhost');
 if(req.method!=='GET'){res.writeHead(405);res.end();return;}
 if(u.pathname.startsWith('/public/')){const p=path.resolve(root,'.'+u.pathname);if(!p.startsWith(path.join(root,'public')+path.sep)||!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));return;}
 if(u.pathname==='/admin/personale/specialita/opzioni'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,options:[...specialties,{id:15,name:'Neurologia',active:true}]}));return;}
 if(u.pathname==='/admin/personale/search'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,results:[{id_personale:1,label:'Anna Test'},{id_personale:2,label:'Altro personale'}]}));return;}
 if(u.pathname.startsWith('/admin/personale/get/')){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,personale:{id_personale:1,id_user:10,nome:'Anna',cognome:'Test',tipo:1},user:{id_user:10,username:'synthetic'},tipi:[{id:1,label:'Dottore'}],gruppi:[{id:1,label:'Sede test'}],selected_luoghi:[1],professional:u.pathname.endsWith('/2')?{available:false}:{available:true,enabled:true,specialty_ids:[11,14],specialty_options:specialties,version:3,catalog_id:0,legacy_options:[{id:5,name:'Professionista precedente'}]}}));return;}
 res.setHeader('Content-Type','text/html;charset=utf-8');res.end(execFileSync('php',['-d','xdebug.mode=off',path.join(root,'ops/personnel-professional-preview.php'),u.searchParams.get('mode')||'']));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const url='http://127.0.0.1:'+server.address().port;
 await page.goto(url);await page.locator('#s_nome').fill('Anna');await page.locator('#searchForm').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await page.locator('.res-item').first().click();
 const fields=page.locator('#professional-profile'),trigger=page.locator('.ps-trigger'),search=page.locator('#ps-search');await fields.waitFor({state:'visible'});assert.equal(await fields.isEnabled(),true);assert.equal(await page.locator('#professional_version').inputValue(),'3');await page.locator('#professional_legacy_id').selectOption('5');
 const ids=()=>page.locator('#professional_specialty_ids').evaluate(e=>new FormData(e.form).getAll('professional_specialty_ids[]'));
 assert.deepEqual(await ids(),['11','14']);await trigger.click();await search.fill('sport');await page.locator('.ps-option input').check();assert.deepEqual(await ids(),['11','12','14']);
 await search.fill('inesistente');assert.equal(await page.locator('.ps-empty').isVisible(),true);await search.press('Escape');assert.equal(await trigger.getAttribute('aria-expanded'),'false');assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);
 await page.getByRole('button',{name:'Rimuovi Specialità archiviata',exact:true}).click();assert.deepEqual(await ids(),['11','12']);
 await trigger.click();await search.fill('derma');await search.press('ArrowDown');await page.keyboard.press('Space');assert.deepEqual(await ids(),['11','12','13']);await page.keyboard.press('Escape');
 const payload=await page.locator('#professional_specialty_ids').evaluate(e=>Object.fromEntries(new FormData(e.form)));assert.equal(payload.professional_legacy_id,'5');assert.equal(payload.professional_enabled,'1');assert.equal(payload.professional_profile_present,'1');assert.equal(payload.professional_specialties_catalog,'1');assert.equal(payload.professional_specialties,undefined);
 await trigger.click();await page.getByRole('button',{name:'Aggiorna elenco',exact:true}).click();await page.getByRole('status').filter({hasText:'Elenco aggiornato.'}).waitFor();assert.deepEqual(await ids(),['11','12','13']);await trigger.click();await search.fill('neuro');assert.equal(await page.locator('.ps-option').count(),1);await search.press('Escape');
 await page.getByRole('button',{name:'Rimuovi Dermatologia',exact:true}).click();await trigger.click();await search.fill('');
 fs.mkdirSync(path.join(root,'rest/build'),{recursive:true});await fields.scrollIntoViewIfNeeded();const box=await fields.boundingBox(),panel=await page.locator('.ps-panel').boundingBox();await page.screenshot({path:path.join(root,'rest/build/personnel-specialties-desktop.png'),clip:{x:box.x,y:box.y,width:box.width,height:Math.max(box.height,panel.y+panel.height-box.y)+8}});await search.press('Escape');
 await page.locator('.res-item').nth(1).click();await fields.waitFor({state:'hidden'});await page.waitForFunction(()=>document.getElementById('professional-profile').disabled===true);assert.deepEqual(await ids(),[]);
 await page.goto(url+'/?mode=create');assert.equal(await page.locator('#professional_specialty_ids').getAttribute('required'),null);assert.equal(await page.locator('[name=professional_enabled]').inputValue(),'');await trigger.click();assert.equal(await page.locator('.ps-option').count(),3);await search.fill('cardio');await page.locator('.ps-option input').check();await search.press('Escape');
 await page.setViewportSize({width:390,height:1000});await trigger.click();await page.locator('.ps-panel').waitFor({state:'visible'});const mobile=await page.locator('.ps-panel').boundingBox();assert.ok(mobile.x>=0 && mobile.x+mobile.width<=391);const mb=await page.locator('.personnel-professional-profile').boundingBox();await page.screenshot({path:path.join(root,'rest/build/personnel-specialties-mobile.png'),clip:{x:mb.x,y:mb.y,width:mb.width,height:Math.max(mb.height,mobile.y+mobile.height-mb.y)+8}});await search.press('Escape');
 await page.locator('#professional_specialty_ids').evaluate(e=>e.form.reset());await page.waitForFunction(()=>document.querySelectorAll('.ps-chip').length===0);assert.deepEqual(await ids(),[]);
 await page.locator('#personnel-specialty-select').evaluate(e=>e.specialtySelect.setOptions([],[]));await trigger.click();assert.match(await page.locator('.ps-empty').innerText(),/Nessuna specialità disponibile/);await search.press('Escape');
 assert.deepEqual(errors,[]);console.log('PASS: catalog selection, search, multiple checkboxes, keyboard, chips, refresh, archived entries, optional fields, feature isolation, reset and mobile layout.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
