<?php
use App\Services\PolyclinicAdministrationService as Clinic;
use App\Services\PolyclinicMoney as Money;
$base='admin/fatturazione-poliambulatori';
$money=static fn($v)=>number_format(((int)$v)/100,2,',','.').' €';
$form=static function(string $action,string $tab,array $extra=[]) use($base,$date): void { ?>
<form method="post" action="<?= site_url($base.'/azione') ?>" class="pc-form">
<?= csrf_field() ?><input type="hidden" name="action" value="<?= esc($action) ?>"><input type="hidden" name="tab" value="<?= esc($tab) ?>"><input type="hidden" name="return_date" value="<?= esc($date) ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>">
<?php foreach($extra as $k=>$v): ?><input type="hidden" name="<?= esc($k) ?>" value="<?= esc((string)$v) ?>"><?php endforeach;
};
$input=static function(string $name,string $label,$value='',string $type='text',bool $required=true): void { ?>
<label><?= esc($label) ?><input name="<?= esc($name) ?>" type="<?= esc($type) ?>" value="<?= esc((string)$value) ?>" <?= $required?'required':'' ?> <?= $type==='number'?'step="1" min="0"':'' ?> maxlength="190"></label>
<?php };
$select=static function(string $name,string $label,array $choices,$value='',bool $optional=false): void { ?>
<label><?= esc($label) ?><select name="<?= esc($name) ?>" <?= $optional?'':'required' ?>><?php if($optional): ?><option value="0">Nessuno / base</option><?php endif; foreach($choices as $k=>$v): ?><option value="<?= esc((string)$k) ?>" <?= (string)$k===(string)$value?'selected':'' ?>><?= esc((string)$v) ?></option><?php endforeach ?></select></label>
<?php };
$options=[]; foreach(($catalog??[]) as $k=>$items) { $options[$k]=[]; foreach($items as $item) if($item['active']) $options[$k][$item['id']]=$item['name']; }
$error=$error??null;
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Poliambulatorio · AmbulatorioFacile</title>
<link rel="stylesheet" href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>"><link rel="stylesheet" href="<?= base_url('public/dist/css/AdminLTE.css') ?>"><link rel="stylesheet" href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>">
<style>
.pc{max-width:1440px;margin:auto;padding:28px;color:#183c43;background:#f4f8f9;min-height:90vh}.pc h1{font-size:30px;font-weight:700}.pc h2{font-size:22px;margin:0 0 18px}.pc h3{font-size:17px}.pc nav{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.pc nav a,.pc button,.pc .pc-link{border:1px solid #b8d5d8;padding:10px 15px;border-radius:8px;background:white;color:#17636b;display:inline-block}.pc nav a.active,.pc button{background:#17636b;color:white}.pc .pc-card{background:white;border:1px solid #d9e6e8;border-radius:12px;padding:22px;margin-bottom:20px}.pc .pc-form{display:flex;align-items:end;gap:14px;flex-wrap:wrap;margin:12px 0}.pc label{display:flex;flex-direction:column;gap:6px;font-size:12px;min-width:140px;max-width:100%;flex:1}.pc input,.pc select{padding:9px;border:1px solid #b9cdd1;border-radius:6px;width:100%;font-size:14px;color:#183c43;background:white}.pc .pc-scroll{overflow:auto}.pc table{width:100%;margin:15px 0;border-collapse:collapse}.pc th,.pc td{padding:11px;text-align:left;border-bottom:1px solid #e0e9ea;vertical-align:top}.pc th{font-size:12px;color:#567078}.pc small,.pc .pc-muted{color:#5c747b}.pc .pc-error{border-left:4px solid #ac3838;padding:14px;background:#fff0ee;margin:14px 0}.pc .pc-success{padding:14px;background:#e5f5ec;margin:14px 0}.pc details{margin:12px 0}.pc summary{cursor:pointer;font-weight:bold}.pc .pc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px}.pc .pc-number{font-size:25px;font-weight:bold}.pc .pc-badge{padding:4px 8px;background:#edf5f6;border-radius:5px;white-space:nowrap}.pc .pc-danger{background:#9d3b36}.pc a{color:#17636b}
</style></head><body class="skin-blue sidebar-mini"><div class="wrapper"><?= view('partials/header',['menu_items'=>$menu_items]) ?>
<main class="pc"><a href="<?= site_url('/') ?>">← Home</a><h1>Fatturazione poliambulatori</h1><p><?= esc($tenantScope['tenant_name']??'') ?> · Accettazione, amministrazione e controllo economico</p>
<nav><?php foreach(['accettazione'=>'Accettazione','catalogo'=>'Prestazioni e listini','documenti'=>'Incassi e compensi','report'=>'Report','integrazioni'=>'Commercialista e XML','requisiti'=>'Copertura funzionale'] as $k=>$label): ?><a class="<?= $tab===$k?'active':'' ?>" href="<?= site_url($base.'?tab='.$k) ?>"><?= esc($label) ?></a><?php endforeach ?></nav>
<?php if($error || session()->getFlashdata('pc_error')): ?><div role="alert" class="pc-error"><?= esc($error?:session()->getFlashdata('pc_error')) ?></div><?php endif ?>
<?php if($message=session()->getFlashdata('pc_success')): ?><div role="status" class="pc-success"><?= esc($message) ?></div><?php endif ?>
<?php if(!$ready): ?><section class="pc-card"><h2>Modulo da attivare</h2><p>Lo schema amministrativo non è ancora installato per questo spazio. L’installazione deve essere eseguita dall’amministratore sull’ambiente scelto.</p></section>
<?php elseif($error): ?><section class="pc-card">Correggere i filtri o tornare a una sezione dal menu.</section>
<?php elseif($tab==='accettazione'): ?>
<section class="pc-card"><h2>Accettazione pazienti</h2><form class="pc-form" method="get"><input type="hidden" name="tab" value="accettazione"><?php $input('date','Giornata',$date,'date'); $input('q','Cerca paziente per nome o codice fiscale',service('request')->getGet('q')??'','search',false); ?><button>Cerca</button><a class="pc-link" href="<?= site_url('agenda/gestione-pazienti') ?>">Anagrafica pazienti</a></form>
<?php if($patients): $patientChoices=[];foreach($patients as $p) $patientChoices[$p['id_client']]=$p['patient_name'].' · '.$p['patient_tax_code']; $form('arrival','accettazione'); $select('patient_id','Paziente',$patientChoices); $select('doctor_id','Professionista',$options['doctor']); $input('visit_date','Data visita',$date,'date'); $input('appointment_id','Appuntamento agenda (facoltativo)','','number',false); ?><button>Registra arrivo</button></form><?php endif ?>
<p class="pc-muted">Cerca il paziente nell’anagrafica per registrarne l’arrivo. Per collegare un appuntamento, il professionista deve avere il relativo collegamento agenda configurato.</p></section>
<?php foreach($encounters as $e): ?><section class="pc-card"><h2><?= esc($e['patient_name']) ?> <span class="pc-badge"><?= esc(Clinic::STATES[$e['state']]) ?></span></h2><p><?= esc($options['doctor'][$e['doctor_id']]??'Professionista archiviato') ?> · Visita #<?= (int)$e['id'] ?></p>
<?php $next=['arrived'=>['waiting'=>'Metti in attesa','cancelled'=>'Annulla'],'waiting'=>['in_care'=>'Inizia visita','cancelled'=>'Annulla'],'in_care'=>['completed'=>'Concludi visita'],'completed'=>[],'cancelled'=>[]]; if($next[$e['state']]): $form('transition','accettazione',['id'=>$e['id'],'version'=>$e['version']]); $select('state','Passaggio successivo',$next[$e['state']]); ?><button>Aggiorna stato</button></form><?php endif ?>
<div class="pc-scroll"><table><thead><tr><th>Prestazione / professionista</th><th>Quantità</th><th>Totale</th><th>A carico ente</th><th>Convenzione</th><th>Documento</th></tr></thead><tbody>
<?php foreach($e['orders'] as $o): $s=json_decode($o['snapshot_json'],true); ?><tr><td><?= esc($s['service']) ?><br><small><?= esc($s['doctor'].' · '.$s['branch']) ?></small></td><td><?= (int)$o['quantity'] ?></td><td><?= $money($o['total_cents']) ?></td><td><?= $money($o['payer_cents']) ?></td><td><?= esc($s['agreement']) ?><br><small><?= esc($s['authorization']) ?></small></td><td><?php if($o['billing_id']): ?><a href="<?= site_url($base.'?tab=documenti&document='.$o['billing_id']) ?>">Apri fattura</a><?php elseif(!in_array($e['state'],['completed','cancelled'],true)): $form('remove_order','accettazione',['id'=>$o['id']]); ?><button class="pc-danger">Rimuovi</button></form><?php endif ?></td></tr><?php endforeach ?>
</tbody></table></div>
<?php if(!in_array($e['state'],['completed','cancelled'],true)): ?><details><summary>Aggiungi prestazione</summary><?php $form('order','accettazione',['encounter_id'=>$e['id']]); $select('service_id','Prestazione',$options['service']); $select('doctor_id','Professionista',$options['doctor'],$e['doctor_id']); $input('quantity','Quantità',1,'number'); $select('list_id','Listino',$options['list'],0,true); $select('agreement_id','Convenzione',$options['agreement'],0,true); $input('authorization','Autorizzazione / impegnativa','','text',false); ?><button>Aggiungi</button></form><small>La convenzione selezionata determina listino e quota dell’ente. Prezzo e regola compenso vengono conservati sulla prestazione.</small></details><?php endif ?>
<?php if($e['state']==='completed' && array_filter($e['orders'],static fn($o)=>!$o['billing_id'])): ?><details><summary>Emetti fattura</summary><?php $form('invoice','accettazione',['encounter_id'=>$e['id']]); $input('issue_date','Data emissione',date('Y-m-d'),'date'); $input('due_date','Scadenza',date('Y-m-d'),'date'); $input('stamp','Bollo','0.00'); $input('vat_rate','IVA %','0.00'); $input('vat_nature','Natura IVA (se aliquota zero)','N4','text',false); $select('recipient_type','Intestatario',['patient'=>'Paziente (sanitaria)','business'=>'Azienda / ente']); ?>
<details style="width:100%"><summary>Dati azienda / ente, se intestatario</summary><div class="pc-form"><?php foreach(['name'=>'Ragione sociale','vat_number'=>'Partita IVA','address'=>'Indirizzo','postal_code'=>'CAP','city'=>'Comune','province'=>'Provincia','recipient_code'=>'Codice destinatario'] as $f=>$label) $input('recipient_'.$f,$label,'','text',false); ?></div></details><button>Emetti documento definitivo</button></form><small>La fattura emessa non è modificabile. Eventuali rettifiche si registrano con nota di credito.</small></details><?php endif ?></section><?php endforeach ?>
<?php if(!$encounters): ?><section class="pc-card">Nessuna accettazione nella giornata selezionata.</section><?php endif ?>
<?php elseif($tab==='catalogo'):
$kind=(string)(service('request')->getGet('kind')??'branch'); if(!isset(Clinic::KINDS[$kind]))$kind='branch';
$editId=(int)service('request')->getGet('edit'); $edit=[];foreach($catalog[$kind] as $item)if((int)$item['id']===$editId)$edit=$item; $ed=$edit['data']??[];
?>
<nav><?php foreach(Clinic::KINDS as $k=>$label): ?><a class="<?= $kind===$k?'active':'' ?>" href="<?= site_url($base.'?tab=catalogo&kind='.$k) ?>"><?= esc($label) ?></a><?php endforeach ?></nav>
<section class="pc-card"><h2><?= $edit?'Modifica':'Nuova voce' ?> · <?= esc(Clinic::KINDS[$kind]) ?></h2>
<?php $form('catalog','catalogo',['kind'=>$kind,'id'=>$edit['id']??0,'version'=>$edit['version']??0]); $input('code','Codice',$edit['code']??''); $input('name','Nome',$edit['name']??''); $select('active','Disponibilità',[1=>'Attiva',0=>'Archiviata'],$edit['active']??1);
if($kind==='doctor') $input('agenda_id','Identificativo medico agenda',$ed['agenda_id']??0,'number',false);
if($kind==='service') { $select('branch_id','Branca',$options['branch'],$ed['branch_id']??''); $input('price','Prezzo base',Money::decimal((int)($ed['price_cents']??0))); }
if($kind==='agreement') { $select('agreement_kind','Tipo',['private'=>'Convenzione privata','insurance'=>'Assicurazione','ssn'=>'SSN'],$ed['kind']??'private'); $select('list_id','Listino',$options['list'],$ed['list_id']??''); $input('coverage','Copertura ente %',Money::decimal((int)($ed['coverage_bps']??0))); $input('payer','Ente pagatore',$ed['payer']??'','text',false); $select('authorization_required','Autorizzazione obbligatoria',[0=>'No',1=>'Sì'],!empty($ed['authorization_required'])?1:0); }
if($kind==='rule') { $select('doctor_id','Professionista',$options['doctor'],$ed['doctor_id']??''); $select('service_id','Prestazione',$options['service'],$ed['service_id']??''); $select('mode','Calcolo',['percent'=>'Percentuale','fixed'=>'Quota fissa per prestazione'],$ed['mode']??'percent'); $input('value','Valore (% oppure euro)',Money::decimal((int)($ed['value']??0))); $select('basis','Maturazione',['collected'=>'Sull’incassato','billed'=>'Sul fatturato'],$ed['basis']??'collected'); }
?><button>Salva</button></form>
<div class="pc-scroll"><table><thead><tr><th>Codice</th><th>Nome</th><th>Stato</th><th></th></tr></thead><tbody><?php foreach($catalog[$kind] as $item): ?><tr><td><?= esc($item['code']) ?></td><td><?= esc($item['name']) ?></td><td><?= $item['active']?'Attiva':'Archiviata' ?></td><td><a href="<?= site_url($base.'?tab=catalogo&kind='.$kind.'&edit='.$item['id']) ?>">Modifica</a></td></tr><?php endforeach ?></tbody></table></div></section>
<?php if($kind==='list'): ?><section class="pc-card"><h2>Tariffe dei listini</h2><?php $form('tariff','catalogo',['version'=>-1]); $select('list_id','Listino',$options['list']); $select('service_id','Prestazione',$options['service']); $input('price','Prezzo'); ?><button>Aggiungi tariffa</button></form>
<?php foreach($tariffs as $t): $form('tariff','catalogo',['list_id'=>$t['list_id'],'service_id'=>$t['service_id'],'version'=>$t['version']]); ?><span><?= esc(($options['list'][$t['list_id']]??'Archiviato').' · '.($options['service'][$t['service_id']]??'Archiviata')) ?></span><?php $input('price','Tariffa',Money::decimal((int)$t['amount_cents'])); ?><button>Aggiorna</button></form><?php endforeach ?></section><?php endif ?>
<?php elseif($tab==='documenti'): ?>
<?php if(!empty($detail)): $d=$detail['document']; $id=(int)$d['id_billing_document']; $b=$detail['balance']; ?>
<section class="pc-card"><h2><?= $d['document_type']==='credit_note'?'Nota di credito':'Fattura' ?> <?= esc($d['document_number']) ?></h2><p><?= esc($d['patient_name']) ?> · <?= esc($d['issue_date']) ?></p><a class="pc-link" href="<?= site_url($base.'/pdf/'.$id) ?>">Scarica PDF</a>
<div class="pc-grid"><?php foreach(['total_cents'=>'Totale documento','credit_cents'=>'Note di credito','paid_cents'=>'Incassato netto','due_cents'=>'Da incassare','refund_due_cents'=>'Da rimborsare'] as $key=>$label): ?><div><h3><?= esc($label) ?></h3><div class="pc-number"><?= $money($b[$key]) ?></div></div><?php endforeach ?></div>
<?php if($d['document_type']==='invoice'): ?>
<details open><summary>Registra incasso o rimborso</summary><?php $form('payment','documenti',['billing_id'=>$id]); $input('amount','Importo (negativo per rimborso)'); $input('payment_date','Data',date('Y-m-d'),'date'); $select('method','Metodo',['bank_transfer'=>'Bonifico','cash'=>'Contanti','card'=>'Carta','pos'=>'POS','other'=>'Altro']); $select('payer','Pagatore',['patient'=>'Paziente','organization'=>'Ente / assicurazione']); $input('reference','Riferimento / causale','','text',false); ?><button>Registra movimento</button></form></details>
<div class="pc-scroll"><table><thead><tr><th>Data</th><th>Importo</th><th>Metodo</th><th>Pagatore</th><th>Riferimento</th></tr></thead><tbody><?php foreach($detail['payments'] as $p): ?><tr><td><?= esc($p['payment_date']) ?></td><td><?= $money($p['amount_cents']) ?></td><td><?= esc(['bank_transfer'=>'Bonifico','cash'=>'Contanti','card'=>'Carta','pos'=>'POS','other'=>'Altro'][$p['method']]??$p['method']) ?></td><td><?= $p['payer']==='patient'?'Paziente':'Ente' ?></td><td><?= esc($p['reference']) ?></td></tr><?php endforeach ?></tbody></table></div>
<details><summary>Nota di credito</summary><p>Lo storno viene ripartito proporzionalmente sulle prestazioni, sull’IVA e sul bollo. Il rimborso effettivo si registra separatamente.</p><?php $form('credit','documenti',['billing_id'=>$id]); $input('amount','Importo da stornare'); $input('issue_date','Data',date('Y-m-d'),'date'); $input('reason','Causale'); ?><button>Emetti nota di credito</button></form></details>
<details><summary>Piano rate</summary><?php if($detail['plan_needs_update']): ?><p class="pc-error">Il totale delle rate non coincide più con il debito dopo lo storno. Aggiornare il piano.</p><?php endif ?>
<?php $form('installments','documenti',['billing_id'=>$id,'version'=>$detail['state']['version']]); ?><div id="pc-installments" style="width:100%">
<?php $plan=$detail['installments']?:[['due_date'=>date('Y-m-d'),'amount_cents'=>$b['net_cents']]]; foreach($plan as $r): ?><div class="pc-form pc-rate"><?php $input('dates[]','Scadenza',$r['due_date'],'date'); $input('amounts[]','Importo',Money::decimal((int)$r['amount_cents'])); ?><button type="button" class="pc-remove-rate">Rimuovi rata</button></div><?php endforeach ?></div><button type="button" id="pc-add-rate">Aggiungi rata</button><button>Salva piano completo</button></form>
<?php foreach($detail['installments'] as $r): ?><p><?= esc($r['due_date']) ?> · <?= $money($r['amount_cents']) ?> · residuo <?= $money($r['due_cents']) ?></p><?php endforeach ?></details>
<h3>Compensi maturati e liquidazioni</h3><p class="pc-muted">Bollo e IVA esclusi dal compenso base. Gli incassi sono ripartiti proporzionalmente; note di credito e rimborsi aggiornano il maturato. Un saldo negativo è un recupero da registrare.</p>
<?php foreach($detail['compensation'] as $c): ?><p><strong><?= esc($c['doctor']) ?></strong> · maturato <?= $money($c['earned_cents']) ?> · liquidato <?= $money($c['settled_cents']) ?> · saldo <?= $money($c['due_cents']) ?></p><?php if($c['due_cents']): $form('settle','documenti',['billing_id'=>$id,'doctor_id'=>$c['doctor_id']]); $input('amount','Liquidazione / recupero',Money::decimal((int)$c['due_cents'])); $input('payment_date','Data',date('Y-m-d'),'date'); $input('reference','Riferimento pagamento'); ?><button>Registra liquidazione</button></form><?php endif; endforeach ?>
<?php foreach($detail['settlements'] as $s): ?><p><small><?= esc($s['payment_date'].' · '.$s['reference']) ?> · <?= $money($s['amount_cents']) ?></small></p><?php endforeach ?>
<?php else: ?><p>Documento collegato alla fattura #<?= (int)$detail['state']['original_id'] ?>. Registrare l’eventuale rimborso sulla fattura originaria.</p><?php endif ?>
<details><summary>Fatturazione elettronica: file e riscontro esterno</summary><p>Stato: <strong><?= esc(['not_prepared'=>'Da preparare','exported'=>'XML preparato','submitted'=>'Inviato tramite canale esterno','delivered'=>'Consegnato','rejected'=>'Scartato','undeliverable'=>'Mancata consegna'][$detail['state']['einvoice_state']]??'Da verificare') ?></strong>. L’esportazione non invia il documento a SdI. Disponibile per intestatari azienda/ente con dati completi; il canale esterno va configurato e collaudato.</p>
<form method="post" action="<?= site_url($base.'/xml/'.$id) ?>"><?= csrf_field() ?><button>Prepara XML FPR12</button></form>
<?php $form('electronic_outcome','documenti',['billing_id'=>$id,'version'=>$detail['state']['version']]); $select('state','Riscontro canale esterno',['submitted'=>'Inviato tramite canale esterno','delivered'=>'Consegnato','rejected'=>'Scartato','undeliverable'=>'Mancata consegna']); $input('reference','Identificativo SdI / riferimento ricevuta'); ?><button>Registra riscontro manuale</button></form></details></section>
<?php endif ?>
<section class="pc-card"><h2>Ultimi 100 documenti del poliambulatorio</h2><div class="pc-scroll"><table><thead><tr><th>Documento</th><th>Intestatario</th><th>Totale</th><th>Incassato</th><th>Residuo</th><th></th></tr></thead><tbody><?php foreach($documents as $d): ?><tr><td><?= esc($d['document_number']) ?><br><small><?= esc($d['issue_date']) ?></small></td><td><?= esc($d['patient_name']) ?></td><td><?= $money($d['balance']['total_cents']) ?></td><td><?= $d['document_type']==='credit_note'?'—':$money($d['balance']['paid_cents']) ?></td><td><?= $d['document_type']==='credit_note'?'—':$money($d['balance']['due_cents']) ?></td><td><a href="<?= site_url($base.'?tab=documenti&document='.$d['id_billing_document']) ?>">Apri</a></td></tr><?php endforeach ?></tbody></table></div></section>
<?php elseif($tab==='report'): ?>
<section class="pc-card"><h2>Analisi delle prestazioni fatturate</h2><form method="get" class="pc-form"><input type="hidden" name="tab" value="report"><?php $input('from','Dal',$report['from'],'date'); $input('to','Al',$report['to'],'date'); $select('group','Raggruppa per',['doctor'=>'Professionista','branch'=>'Branca','service'=>'Prestazione','agreement'=>'Convenzione'],$report['group']); $select('doctor_id','Professionista',$options['doctor'],service('request')->getGet('doctor_id')??0,true); $select('branch_id','Branca',$options['branch'],service('request')->getGet('branch_id')??0,true); $select('service_id','Prestazione',$options['service'],service('request')->getGet('service_id')??0,true); ?><button>Applica filtri</button></form><p>Importi delle prestazioni esclusi IVA e bollo. Fatture e note di credito rientrano nel periodo della propria data di emissione.</p>
<div class="pc-scroll"><table><thead><tr><th>Raggruppamento</th><th>Quantità fatturate</th><th>Fatturato</th><th>Storni</th><th>Netto</th><th>Incassi periodo</th></tr></thead><tbody><?php foreach($report['rows'] as $r): ?><tr><td><?= esc($r['label']) ?></td><td><?= (int)$r['quantity'] ?></td><td><?= $money($r['gross_cents']) ?></td><td><?= $money($r['credit_cents']) ?></td><td><?= $money($r['net_cents']) ?></td><td><?= $money($r['cash_cents']) ?></td></tr><?php endforeach ?></tbody></table></div><p class="pc-muted">I documenti precedenti privi di collegamento strutturato alle prestazioni restano nei report generali della fatturazione.</p></section>
<section class="pc-card"><h2>Compensi sulle fatture del periodo</h2><p>Situazione attuale, aggiornata con tutti gli incassi e gli storni successivi. Questo riepilogo considera il filtro professionista; i filtri branca e prestazione riguardano la tabella precedente.</p><div class="pc-scroll"><table><thead><tr><th>Professionista</th><th>Maturato</th><th>Liquidato</th><th>Saldo da liquidare / recuperare</th></tr></thead><tbody><?php foreach($report['compensation'] as $fee): ?><tr><td><?= esc($fee['doctor']) ?></td><td><?= $money($fee['earned_cents']) ?></td><td><?= $money($fee['settled_cents']) ?></td><td><?= $money($fee['due_cents']) ?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php elseif($tab==='integrazioni'): ?>
<section class="pc-card"><h2>Collegamenti universali: demo</h2><p><strong>Modalità demo — nessun invio reale.</strong> Mostra accettazione, scarto o attesa di un esito. La contabilità usa le registrazioni del periodo; SdI usa una fattura aziendale sintetica. Gli esiti demo non cambiano lo stato delle fatture.</p>
<?php $form('simulate_connector','integrazioni'); $select('connector','Collegamento',['accounting'=>'Commercialista / Passepartout (universale)','sdi'=>'SdI (fattura sintetica)']); $select('scenario','Esito da mostrare',['accepted'=>'Accettazione','rejected'=>'Scarto','timeout'=>'Esito incerto']); $input('from','Dal',date('Y-m-01'),'date'); $input('to','Al',date('Y-m-d'),'date'); ?><button>Esegui simulazione</button></form>
<div class="pc-scroll"><table><thead><tr><th>Data</th><th>Collegamento</th><th>Esito demo</th><th>Dettaglio</th></tr></thead><tbody><?php foreach(($demoRuns??[]) as $run): $result=json_decode($run['result_json'],true)??[]; ?><tr><td><?= esc($run['created_at']) ?></td><td><?= $run['connector']==='sdi'?'SdI':'Commercialista' ?></td><td><?= esc($result['label']??'') ?><br><small><?= esc($result['reference']??'') ?></small></td><td><?= esc($result['summary']??'') ?><br><small><?= esc($result['note']??'') ?></small></td></tr><?php endforeach ?></tbody></table></div></section>
<section class="pc-card"><h2>Esportazione per il commercialista</h2><p>Prima nota CSV con registrazioni bilanciate, fatture, note di credito e movimenti del registro incassi. I conti devono corrispondere al piano contabile dello studio.</p><p><strong>Passepartout:</strong> il tracciato nativo e la prova d’importazione sono da validare sul prodotto utilizzato. Questo export è un CSV configurabile; non viene dichiarato come import nativo già collaudato.</p>
<?php $ac=$accounting['data']; $form('accounting','integrazioni',['version'=>$accounting['version']]); foreach(['customer_account'=>'Conto clienti','revenue_account'=>'Conto ricavi','vat_account'=>'Conto IVA','stamp_account'=>'Conto bolli','cash_account'=>'Conto cassa','bank_account'=>'Conto banca'] as $f=>$label) $input($f,$label,$ac[$f]??''); $input('columns','Colonne nell’ordine desiderato',implode(',',$ac['columns']??\App\Services\PolyclinicAccountingExport::FIELDS)); $select('delimiter','Separatore',[';'=>'Punto e virgola',','=>'Virgola',':'=>'Due punti'],$ac['delimiter']??';'); ?><button>Salva configurazione</button></form>
<form method="get" action="<?= site_url($base.'/export') ?>" class="pc-form"><?php $input('from','Dal',date('Y-m-01'),'date'); $input('to','Al',date('Y-m-d'),'date'); ?><button>Scarica prima nota CSV</button></form><small>Ogni operazione ha un identificativo stabile. Reimportare lo stesso periodo richiede il controllo duplicati nel sistema destinatario.</small></section>
<section class="pc-card"><h2>Emittente XML FPR12</h2><p>Il file si prepara dal dettaglio documento. Il collegamento automatico a un provider SdI non è attivo.</p><?php $form('einvoice_settings','integrazioni',['version'=>$einvoice['version']]); foreach(['business_name'=>'Ragione sociale','vat_number'=>'Partita IVA','address'=>'Indirizzo','postal_code'=>'CAP','city'=>'Comune','province'=>'Provincia','tax_regime'=>'Regime fiscale (es. RF01)'] as $f=>$label) $input($f,$label,$einvoice['data'][$f]??''); ?><button>Salva emittente</button></form></section>
<section class="pc-card"><h2>Ultime operazioni</h2><div class="pc-scroll"><table><thead><tr><th>Data</th><th>Operatore</th><th>Operazione</th><th>Riferimento</th></tr></thead><tbody><?php foreach($audit as $a): ?><tr><td><?= esc($a['created_at']) ?></td><td><?= (int)$a['actor_id'] ?></td><td><?= esc($a['action']) ?></td><td><?= (int)$a['entity_id'] ?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php elseif($tab==='requisiti'): ?>
<section class="pc-card"><h2>Copertura funzionale</h2><p>La disponibilità dei collegamenti esterni dipende dall’attivazione e dal collaudo dello spazio.</p><table><thead><tr><th>Ambito</th><th>Funzioni</th></tr></thead><tbody>
<?php foreach(['Agenda'=>'Multi-medico e multi-stanza nel modulo agenda esistente.','Accettazione'=>'Arrivo, attesa, visita, conclusione e collegamento appuntamento.','Cartella clinica'=>'Cartella, referti, allegati e consensi nel modulo clinico, se abilitato.','Prestazioni e listini'=>'Catalogo, branche, prezzi base e tariffe per listino.','Fatture e incassi'=>'Emissione, rate, pagamenti parziali, rimborsi e note di credito proporzionali.','Compensi'=>'Regole per medico/prestazione, quota fissa o percentuale, maturazione e liquidazioni.','Convenzioni / assicurazioni / SSN'=>'Listino, copertura ente, autorizzazione e quota paziente. Flussi regionali e portali assicurativi non collegati.','Report'=>'Analisi per medico, branca, prestazione, convenzione e periodo.','Commercialista'=>'Prima nota CSV configurabile; import nativo Passepartout da validare.','Fatturazione elettronica'=>'Preparazione XML FPR12 e registrazione manuale esiti; canale SdI automatico da collegare.','Sistema TS'=>'Modulo esistente; profilo reale da collaudare. Note di credito e incassi parziali richiedono gestione TS dedicata.'] as $label=>$description): ?><tr><th><?= esc($label) ?></th><td><?= esc($description) ?></td></tr><?php endforeach ?></tbody></table></section>
<?php endif ?>
</main></div><script>
document.addEventListener('click',function(event){
 if(event.target.id==='pc-add-rate'){const root=document.getElementById('pc-installments');const row=root.querySelector('.pc-rate');if(row){const copy=row.cloneNode(true);copy.querySelectorAll('input').forEach(i=>i.value='');root.appendChild(copy);}}
 if(event.target.classList.contains('pc-remove-rate')){const root=document.getElementById('pc-installments');if(root.children.length>1)event.target.closest('.pc-rate').remove();}
});
</script></body></html>
