<?php
$dashboard = is_array($dashboard ?? null) ? $dashboard : [];
$profile = is_array($profile ?? null) ? $profile : [];
$states = is_array($dashboard['by_state'] ?? null) ? $dashboard['by_state'] : [];
$errors = is_array($errors ?? null) ? $errors : [];
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AmbulatorioFacile | FSE 2.0</title>
<link href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet"><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link href="<?= base_url('public/dist/css/AdminLTE.css') ?>" rel="stylesheet"><link href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>" rel="stylesheet">
<style>.fse-card{background:#fff;border:1px solid #dfe8ec;border-radius:10px;padding:18px;margin-bottom:18px}.fse-kpi{font-size:30px;font-weight:700;color:#176b76}.fse-flow span{display:inline-block;padding:8px 12px;margin:4px;border-radius:18px;background:#edf6f7}.fse-head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}</style></head>
<body class="skin-blue sidebar-mini"><div class="wrapper"><?= view('partials/header', ['menu_items' => $menu_items ?? []]) ?><div class="content-wrapper"><section class="content"><div class="row"><aside class="col-md-3"><?= view('partials/sidebar_admin', ['menu_items' => $menu_items ?? []]) ?></aside><main class="col-md-9">
<div class="fse-card"><div class="fse-head"><div><p class="text-muted">Modulo clinico</p><h1 style="margin-top:0"><i class="fa fa-medkit"></i> FSE 2.0</h1><p>Referti CDA2, firma PAdES, validazione e pubblicazione sul Gateway nazionale.</p></div><div><a class="btn btn-default" href="<?= portal_tenant_space_url('fse2') ?>"><i class="fa fa-cog"></i> Configura</a> <a class="btn btn-info" href="<?= site_url('admin/fse2/documenti') ?>">Referti</a> <a class="btn btn-success" href="<?= site_url('admin/fse2/documenti/nuovo') ?>"><i class="fa fa-plus"></i> Nuovo referto</a></div></div></div>
<?php if ($success): ?><div class="alert alert-success"><?= esc($success) ?></div><?php endif ?><?php if ($errors): ?><div class="alert alert-danger"><?= esc((string) ($errors['generic'] ?? implode(' ', $errors))) ?></div><?php endif ?>
<div class="row"><div class="col-sm-4"><div class="fse-card"><div class="text-muted">Totale referti</div><div class="fse-kpi"><?= (int) ($dashboard['total'] ?? 0) ?></div></div></div><div class="col-sm-4"><div class="fse-card"><div class="text-muted">Da validare</div><div class="fse-kpi"><?= (int) ($states['ready_to_validate'] ?? 0) ?></div></div></div><div class="col-sm-4"><div class="fse-card"><div class="text-muted">Pubblicati</div><div class="fse-kpi"><?= (int) ($states['published'] ?? 0) ?></div></div></div></div>
<div class="fse-card"><h3>Stato integrazione</h3><p><strong>Ambiente:</strong> <?= esc(strtoupper((string) ($profile['environment'] ?? 'non configurato'))) ?> · <strong>Profilo:</strong> <?= esc((string) ($profile['profile_name'] ?? 'non configurato')) ?> · <strong>Gateway:</strong> <?= !empty($profile['is_enabled']) ? 'abilitato' : 'disabilitato' ?></p><div class="fse-flow"><span>1. Bozza clinica</span><i class="fa fa-angle-right"></i><span>2. CDA + PDF</span><i class="fa fa-angle-right"></i><span>3. Firma PAdES</span><i class="fa fa-angle-right"></i><span>4. Gateway</span><i class="fa fa-angle-right"></i><span>5. FSE regionale</span></div></div>
<?php if (empty($dashboard['table_available'])): ?><div class="alert alert-warning"><?= esc((string) ($dashboard['schema_message'] ?? 'Le tabelle FSE non sono disponibili nel database dello spazio.')) ?></div><?php endif ?>
</main></div></section></div><footer class="main-footer"><strong>&copy; AmbulatorioFacile</strong></footer></div><script src="<?= base_url('public/plugins/jQuery/jQuery-2.1.4.min.js') ?>"></script><script src="<?= base_url('public/bootstrap/js/bootstrap.min.js') ?>"></script></body></html>
