<?php
$context = is_array($formContext ?? null) ? $formContext : [];
$doc = is_array($context['document'] ?? null) ? $context['document'] : [];
$events = is_array($context['events'] ?? null) ? $context['events'] : [];
$labels = is_array($context['state_labels'] ?? null) ? $context['state_labels'] : [];
$requests = is_array($context['administrative_requests'] ?? null) ? $context['administrative_requests'] : [];
$errors = is_array($errors ?? null) ? $errors : [];
$id = (int) ($doc['id_fse_document'] ?? 0); $state = (string) ($doc['local_state'] ?? 'draft');
$selectedProfileId = (string) (old('id_fse_profile') ?? ($context['profile']['id_fse_profile'] ?? ''));
if (!$id && !isset($doc['administrative_request'])) {
    foreach (($context['profiles'] ?? []) as $candidate) {
        if ((string)$candidate['id_fse_profile'] === $selectedProfileId && !empty($candidate['care_regime'])) $doc['administrative_request'] = $candidate['care_regime'];
    }
}
$value = static fn(string $key, $default=''): string => esc((string) (old($key) ?? ($doc[$key] ?? $default)));
$dateValue = static function(string $key) use ($doc): string { $v=(string)(old($key) ?? ($doc[$key] ?? '')); return esc($v !== '' ? str_replace(' ', 'T', substr($v,0,16)) : ''); };
$locked = !\App\Services\FseDocumentLifecycle::isEditable($doc);
$localSigning = ($context['profile']['access_mode'] ?? '') === 'toscana_privati' || !empty($doc['previous_document_id']);
$gatewayBlocked = $localSigning;
$diagnosis = $context['diagnosis'] ?? null;
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $id ? 'Referto FSE #'.$id : 'Nuovo referto FSE' ?></title><link href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet"><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link href="<?= base_url('public/dist/css/AdminLTE.css') ?>" rel="stylesheet"><link href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>" rel="stylesheet"><style>.fse-box{background:#fff;border:1px solid #dfe8ec;border-radius:10px;padding:18px;margin-bottom:18px}.state{display:inline-block;padding:6px 11px;border-radius:14px;background:#e9f4f5;color:#176b76;font-weight:700}.actions form{display:inline-block;margin:0 5px 7px 0}.patient-results{position:absolute;z-index:20;background:#fff;border:1px solid #ccc;width:100%;max-height:220px;overflow:auto}.patient-results button{display:block;width:100%;text-align:left;border:0;background:#fff;padding:8px}.patient-results button:hover{background:#eef7f8}textarea{min-height:90px}</style></head>
<body class="skin-blue sidebar-mini"><div class="wrapper"><?= view('partials/header',['menu_items'=>$menu_items ?? []]) ?><div class="content-wrapper"><section class="content"><div class="row"><aside class="col-md-3"><?= view('partials/sidebar_admin',['menu_items'=>$menu_items ?? []]) ?></aside><main class="col-md-9">
<div class="fse-box"><div class="clearfix"><div class="pull-left"><h1 style="margin-top:0"><?= $id ? 'Referto FSE #'.$id : 'Nuovo referto FSE' ?></h1><span class="state"><?= esc((string)($labels[$state] ?? $state)) ?></span></div><a class="btn btn-default pull-right" href="<?= site_url('admin/fse2/documenti') ?>">Torna alla lista</a></div></div>
<?php if ($success): ?><div class="alert alert-success"><?= esc($success) ?></div><?php endif ?><?php if ($errors): ?><div class="alert alert-danger"><?= esc((string)($errors['generic'] ?? implode(' ', $errors))) ?></div><?php endif ?>
<?php if (!empty($warning)): ?><div class="alert alert-warning" role="alert"><?= esc((string) $warning) ?></div><?php endif ?>
<?php if (!empty($syntheticAppLab)): ?><div class="fse-box" data-fse-synthetic-bridge><h2>Precollaudo Toscana · ambiente sintetico isolato</h2>
<p>Solo dati inventati. Puoi verificare gli artefatti firmati di questo referto e collegarne uno snapshot al laboratorio: invio, sostituzione, metadati e cancellazione avranno esclusivamente esiti simulati, senza modificare lo stato del referto qui mostrato.</p>
<?php if ($id && $state === 'signed' && ($context['profile']['access_mode'] ?? '') === 'toscana_privati'): ?>
<form method="post" action="<?= site_url('admin/fse2/documenti/laboratorio-toscana/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-warning">Verifica e collega snapshot al laboratorio</button></form>
<?php else: ?><p>Per collegare lo snapshot, completa la preparazione e la firma sintetica con un profilo Toscana di test.</p><?php endif ?>
<p style="margin-top:10px"><a href="<?= site_url('admin/fse2/laboratorio-toscana') ?>">Apri gli esiti separati del laboratorio</a>. Non è un collaudo ufficiale né una firma qualificata.</p></div><?php endif ?>
<?php if ($id): ?><div class="fse-box"><a class="btn btn-info" href="<?= site_url('admin/fse2/documenti/assistenza/'.$id) ?>">Scarica rapporto tecnico per assistenza</a><p class="text-muted" style="margin-top:8px">Stati e identificativi tecnici, senza referto o credenziali. Condividere solo con il supporto autorizzato. Nessun reinvio viene eseguito.</p></div><?php endif ?>
<?php if ($id): ?><div class="fse-box"><h3>Versione <?= (int) ($doc['version_number'] ?? 1) ?> e storico</h3>
<?php if (!empty($doc['previous_document_id'])): ?><div class="alert alert-warning">Correzione locale del referto #<?= (int) $doc['previous_document_id'] ?>. La sostituzione sul FSE non è stata eseguita e rimane disabilitata.</div><p><strong>Motivo:</strong> <?= esc((string) ($doc['revision_reason'] ?? '')) ?></p><?php endif ?>
<?php foreach (($context['history'] ?? []) as $version): ?><p><a href="<?= site_url('admin/fse2/documenti/modifica/' . (int) $version['id_fse_document']) ?>">Versione <?= (int) $version['version_number'] ?> — referto #<?= (int) $version['id_fse_document'] ?></a> · <?= esc($labels[$version['local_state']] ?? $version['local_state']) ?></p><?php endforeach ?>
<?php if (!empty($context['can_revise'])): ?><form method="post" action="<?= site_url('admin/fse2/documenti/correggi/' . $id) ?>"><?= csrf_field() ?><div class="form-group"><label for="revision_reason">Motivo della correzione</label><textarea class="form-control" id="revision_reason" name="revision_reason" maxlength="2000" required></textarea></div><button class="btn btn-warning">Apri correzione senza modificare l’originale</button></form><?php endif ?></div><?php endif ?>
<?php if (is_array($diagnosis) && $diagnosis['code'] !== 'NO_PENDING_OPERATION'): ?><div class="fse-box"><h3>Diagnosi operazione</h3><p><?= esc($diagnosis['message']) ?></p><dl><?php foreach ($diagnosis['technical'] as $key => $technical): ?><?php if ($technical): ?><dt><?= esc($key) ?></dt><dd style="overflow-wrap:anywhere"><?= esc((string) $technical) ?></dd><?php endif ?><?php endforeach ?></dl><p class="text-muted">Nessuno sblocco o reinvio automatico.</p></div><?php endif ?>
<form class="fse-box" method="post" action="<?= site_url('admin/fse2/documenti/save') ?>"><?= csrf_field() ?><input type="hidden" name="id_fse_document" value="<?= $id ?>"><input type="hidden" name="edit_token" value="<?= $value('edit_token') ?>"><input type="hidden" id="id_client" name="id_client" value="<?= $value('id_client') ?>"><fieldset <?= $locked ? 'disabled' : '' ?>>
<div class="form-group"><label>Profilo sede e regime</label>
<?php if(!$id): ?><select id="fse-profile-select" class="form-control" name="id_fse_profile" required><option value="">Seleziona il profilo</option><?php foreach(($context['profiles']??[]) as $p): ?><option value="<?= (int)$p['id_fse_profile'] ?>" data-care-regime="<?= esc($p['care_regime']??'') ?>" <?= $selectedProfileId===(string)$p['id_fse_profile']?'selected':'' ?>><?= esc($p['profile_name'].' — '.($p['site_code']??'').' / '.($p['care_regime']??'da definire')) ?></option><?php endforeach ?></select>
<?php else: ?><input type="hidden" name="id_fse_profile" value="<?= (int)($doc['id_fse_profile']??0) ?>"><p><?= esc((string)($context['profile']['profile_name']??'Profilo associato')) ?> — configurazione associata alla creazione, non cambia con il predefinito.</p><?php endif ?></div>
<h3>Dati paziente</h3><div class="row"><div class="col-sm-12 form-group" style="position:relative"><label>Cerca paziente esistente</label><input id="patient-search" class="form-control" autocomplete="off" placeholder="Cognome, nome, codice fiscale..."><div id="patient-results" class="patient-results" hidden></div></div>
<div class="col-sm-4 form-group"><label>Nome *</label><input id="patient_first_name" class="form-control" name="patient_first_name" required value="<?= $value('patient_first_name') ?>"></div><div class="col-sm-4 form-group"><label>Cognome *</label><input id="patient_last_name" class="form-control" name="patient_last_name" required value="<?= $value('patient_last_name') ?>"></div><div class="col-sm-4 form-group"><label>Codice fiscale *</label><input id="patient_cf" class="form-control" name="patient_cf" maxlength="16" required value="<?= $value('patient_cf') ?>"></div>
<div class="col-sm-3 form-group"><label>Data nascita *</label><input class="form-control" type="date" name="patient_birth_date" required value="<?= $value('patient_birth_date') ?>"></div><div class="col-sm-3 form-group"><label>Sesso *</label><select class="form-control" name="patient_gender" required><?php foreach(['M'=>'Maschile','F'=>'Femminile','UN'=>'Non noto'] as $k=>$l): ?><option value="<?= $k ?>" <?= (old('patient_gender') ?? ($doc['patient_gender'] ?? ''))===$k?'selected':'' ?>><?= $l ?></option><?php endforeach ?></select></div><div class="col-sm-6 form-group"><label>Email</label><input id="patient_email" class="form-control" type="email" name="patient_email" value="<?= $value('patient_email') ?>"></div><div class="col-sm-7 form-group"><label>Indirizzo</label><input id="patient_address" class="form-control" name="patient_address" value="<?= $value('patient_address') ?>"></div><div class="col-sm-5 form-group"><label>Città</label><input id="patient_city" class="form-control" name="patient_city" value="<?= $value('patient_city') ?>"></div></div>
<hr><h3>Prestazione e referto RSA</h3><div class="row"><div class="col-sm-8 form-group"><label>Titolo documento *</label><input class="form-control" name="document_title" required value="<?= $value('document_title','Referto di Specialistica Ambulatoriale') ?>"></div><div class="col-sm-4 form-group"><label>Regime</label><select class="form-control" name="administrative_request"><?php foreach($requests as $k=>$l): ?><option value="<?= esc($k) ?>" <?= (old('administrative_request') ?? ($doc['administrative_request'] ?? 'NOSSN'))===$k?'selected':'' ?>><?= esc($l) ?></option><?php endforeach ?></select></div><div class="col-sm-6 form-group"><label>Inizio prestazione *</label><input class="form-control" type="datetime-local" name="service_start" required value="<?= $dateValue('service_start') ?>"></div><div class="col-sm-6 form-group"><label>Fine prestazione</label><input class="form-control" type="datetime-local" name="service_end" value="<?= $dateValue('service_end') ?>"></div><input type="hidden" name="loinc_code" value="<?= $value('loinc_code','11488-4') ?>"><input type="hidden" name="loinc_display_name" value="<?= $value('loinc_display_name','Nota di consulto') ?>"></div>
<?php foreach(['service_description'=>'Prestazione eseguita *','reason_text'=>'Motivo della visita','history_text'=>'Anamnesi','findings_text'=>'Reperti','report_text'=>'Referto *','diagnosis_text'=>'Diagnosi','conclusions_text'=>'Conclusioni'] as $k=>$label): ?><div class="form-group"><label><?= $label ?></label><textarea class="form-control" name="<?= $k ?>" <?= in_array($k, ['report_text','service_description'], true)?'required':'' ?>><?= $value($k) ?></textarea></div><?php endforeach ?>
<div class="checkbox"><label><input type="hidden" name="patient_consent" value="0"><input type="checkbox" name="patient_consent" value="1" <?= (old('patient_consent') ?? ($doc['patient_consent'] ?? 1)) ? 'checked':'' ?>> Paziente preso in carico ai fini FSE (claim patient_consent)</label></div>
<?php if(!$locked): ?><button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Salva bozza</button><?php endif ?></fieldset></form>
<?php if($id): ?><div class="fse-box"><h3>Firma e Gateway</h3><p class="text-muted">Il gestionale genera CDA e PDF. La firma qualificata PAdES viene applicata con il dispositivo/servizio di firma autorizzato e il PDF firmato viene poi ricaricato.</p><div class="actions">
<?php if(!$locked): ?><form method="post" action="<?= site_url('admin/fse2/documenti/prepara/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-info"><i class="fa fa-file-pdf-o"></i> Genera CDA + PDF</button></form><?php endif ?>
<?php if(!empty($doc['cda_path'])): ?><a class="btn btn-default" href="<?= site_url('admin/fse2/documenti/download/'.$id.'/cda') ?>">Scarica CDA</a><?php endif ?> <?php if(!empty($doc['unsigned_pdf_path'])): ?><a class="btn btn-default" href="<?= site_url('admin/fse2/documenti/download/'.$id.'/unsigned') ?>">Scarica PDF da firmare</a><?php endif ?> <?php if(!empty($doc['signed_pdf_path'])): ?><a class="btn btn-default" href="<?= site_url('admin/fse2/documenti/download/'.$id.'/signed') ?>">Scarica firmato</a><?php endif ?>
</div><?php if($state===($localSigning ? 'ready_to_validate' : 'validated')): ?><form method="post" enctype="multipart/form-data" action="<?= site_url('admin/fse2/documenti/firma/'.$id) ?>" style="margin-top:15px"><?= csrf_field() ?><div class="row"><div class="col-sm-8"><input class="form-control" type="file" name="signed_pdf" accept="application/pdf" required></div><div class="col-sm-4"><button class="btn btn-warning"><i class="fa fa-upload"></i> Acquisisci PAdES</button></div></div></form><?php endif ?>
<?php if ($gatewayBlocked): ?><div class="alert alert-warning" style="margin-top:15px">Preparazione e firma locali consentite. Gli invii Toscana e le sostituzioni restano bloccati fino al collaudo e alle abilitazioni richieste.</div><?php endif ?>
<?php if (!$gatewayBlocked): ?>
<hr><div class="actions"><?php if(in_array($state,['ready_to_validate','rejected'],true) && !\App\Services\FseDocumentLifecycle::isSealed($doc)): ?><form method="post" action="<?= site_url('admin/fse2/documenti/valida/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-default">Valida PDF/CDA sul Gateway</button></form><?php endif ?><?php if($state==='signed'): ?><form method="post" action="<?= site_url('admin/fse2/documenti/pubblica/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-success">Pubblica PDF firmato</button></form><?php endif ?><?php if(!empty($doc['workflow_instance_id']) && in_array($state,['publishing','published','deleting'],true)): ?><form method="post" action="<?= site_url('admin/fse2/documenti/stato/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-info">Aggiorna stato</button></form><?php endif ?><?php if($state==='published'): ?><form method="post" action="<?= site_url('admin/fse2/documenti/elimina/'.$id) ?>" onsubmit="return confirm('Eliminare il documento pubblicato dal FSE?')"><?= csrf_field() ?><button class="btn btn-danger">Elimina dal FSE</button></form><?php endif ?></div>
<?php endif ?>
<?php if(!empty($doc['workflow_instance_id'])): ?><p><strong>Workflow:</strong> <?= esc((string)$doc['workflow_instance_id']) ?></p><?php endif ?>
<?php if(!empty($doc['last_gateway_message'])): ?><div class="alert alert-info" role="status" data-fse-last-outcome><strong>Ultimo esito Gateway:</strong> <?= esc((string)$doc['last_gateway_message']) ?><br><strong>HTTP:</strong> <?= (int)($doc['gateway_http_status'] ?? 0) ?><br><strong>Stato Gateway:</strong> <?= esc((string)($doc['gateway_state'] ?? '-')) ?></div><?php endif ?></div>
<div class="fse-box"><h3>Audit</h3><?php if(!$events): ?><p class="text-muted">Nessun evento.</p><?php else: ?><table class="table table-condensed"><thead><tr><th>Data</th><th>Evento</th><th>Messaggio</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= esc((string)$event['created_at']) ?></td><td><?= esc((string)$event['event_type']) ?></td><td><?= esc((string)$event['message']) ?></td></tr><?php endforeach ?></tbody></table><?php endif ?></div><?php endif ?>
</main></div></section></div><footer class="main-footer"><strong>&copy; AmbulatorioFacile</strong></footer></div><script src="<?= base_url('public/plugins/jQuery/jQuery-2.1.4.min.js') ?>"></script><script src="<?= base_url('public/bootstrap/js/bootstrap.min.js') ?>"></script><script>
(function(){var q=document.getElementById('patient-search'), box=document.getElementById('patient-results'), timer;if(!q)return;q.addEventListener('input',function(){clearTimeout(timer);var term=q.value.trim();if(term.length<2){box.hidden=true;return}timer=setTimeout(function(){fetch('<?= site_url('admin/fse2/documenti/pazienti/search') ?>?term='+encodeURIComponent(term),{credentials:'same-origin'}).then(function(r){return r.json()}).then(function(data){box.innerHTML='';(data.results||[]).forEach(function(p){var b=document.createElement('button');b.type='button';b.textContent=(p.label||'')+' · '+(p.patient_tax_code||'');b.onclick=function(){['id_client','patient_first_name','patient_last_name','patient_cf','patient_email','patient_address','patient_city'].forEach(function(id){var map={id_client:'id_client',patient_first_name:'patient_first_name',patient_last_name:'patient_last_name',patient_cf:'patient_tax_code',patient_email:'patient_email',patient_address:'patient_address',patient_city:'patient_city'};document.getElementById(id).value=p[map[id]]||''});box.hidden=true};box.appendChild(b)});box.hidden=box.children.length===0})},250)})})();
(function(){var profile=document.getElementById('fse-profile-select'),regime=document.querySelector('[name="administrative_request"]');if(profile&&regime)profile.addEventListener('change',function(){var selected=profile.options[profile.selectedIndex],value=selected?selected.getAttribute('data-care-regime'):'';if(value)regime.value=value;});})();
</script></body></html>
