<?php
$context = is_array($formContext ?? null) ? $formContext : [];
$doc = is_array($context['document'] ?? null) ? $context['document'] : [];
$events = is_array($context['events'] ?? null) ? $context['events'] : [];
$labels = is_array($context['state_labels'] ?? null) ? $context['state_labels'] : [];
$requests = is_array($context['administrative_requests'] ?? null) ? $context['administrative_requests'] : [];
$errors = is_array($errors ?? null) ? $errors : [];
$id = (int) ($doc['id_fse_document'] ?? 0); $state = (string) ($doc['local_state'] ?? 'draft');
$value = static fn(string $key, $default=''): string => esc((string) (old($key) ?? ($doc[$key] ?? $default)));
$dateValue = static function(string $key) use ($doc): string { $v=(string)(old($key) ?? ($doc[$key] ?? '')); return esc($v !== '' ? str_replace(' ', 'T', substr($v,0,16)) : ''); };
$locked = in_array($state, ['validating','publishing','deleting','published','deleted'], true);
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $id ? 'Referto FSE #'.$id : 'Nuovo referto FSE' ?></title><link href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet"><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link href="<?= base_url('public/dist/css/AdminLTE.css') ?>" rel="stylesheet"><link href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>" rel="stylesheet"><style>.fse-box{background:#fff;border:1px solid #dfe8ec;border-radius:10px;padding:18px;margin-bottom:18px}.state{display:inline-block;padding:6px 11px;border-radius:14px;background:#e9f4f5;color:#176b76;font-weight:700}.actions form{display:inline-block;margin:0 5px 7px 0}.patient-results{position:absolute;z-index:20;background:#fff;border:1px solid #ccc;width:100%;max-height:220px;overflow:auto}.patient-results button{display:block;width:100%;text-align:left;border:0;background:#fff;padding:8px}.patient-results button:hover{background:#eef7f8}textarea{min-height:90px}</style></head>
<body class="skin-blue sidebar-mini"><div class="wrapper"><?= view('partials/header',['menu_items'=>$menu_items ?? []]) ?><div class="content-wrapper"><section class="content"><div class="row"><aside class="col-md-3"><?= view('partials/sidebar_admin',['menu_items'=>$menu_items ?? []]) ?></aside><main class="col-md-9">
<div class="fse-box"><div class="clearfix"><div class="pull-left"><h1 style="margin-top:0"><?= $id ? 'Referto FSE #'.$id : 'Nuovo referto FSE' ?></h1><span class="state"><?= esc((string)($labels[$state] ?? $state)) ?></span></div><a class="btn btn-default pull-right" href="<?= site_url('admin/fse2/documenti') ?>">Torna alla lista</a></div></div>
<?php if ($success): ?><div class="alert alert-success"><?= esc($success) ?></div><?php endif ?><?php if ($errors): ?><div class="alert alert-danger"><?= esc((string)($errors['generic'] ?? implode(' ', $errors))) ?></div><?php endif ?>
<form class="fse-box" method="post" action="<?= site_url('admin/fse2/documenti/save') ?>"><?= csrf_field() ?><input type="hidden" name="id_fse_document" value="<?= $id ?>"><input type="hidden" id="id_client" name="id_client" value="<?= $value('id_client') ?>">
<h3>Dati paziente</h3><div class="row"><div class="col-sm-12 form-group" style="position:relative"><label>Cerca paziente esistente</label><input id="patient-search" class="form-control" autocomplete="off" placeholder="Cognome, nome, codice fiscale..."><div id="patient-results" class="patient-results" hidden></div></div>
<div class="col-sm-4 form-group"><label>Nome *</label><input id="patient_first_name" class="form-control" name="patient_first_name" required value="<?= $value('patient_first_name') ?>"></div><div class="col-sm-4 form-group"><label>Cognome *</label><input id="patient_last_name" class="form-control" name="patient_last_name" required value="<?= $value('patient_last_name') ?>"></div><div class="col-sm-4 form-group"><label>Codice fiscale *</label><input id="patient_cf" class="form-control" name="patient_cf" maxlength="16" required value="<?= $value('patient_cf') ?>"></div>
<div class="col-sm-3 form-group"><label>Data nascita *</label><input class="form-control" type="date" name="patient_birth_date" required value="<?= $value('patient_birth_date') ?>"></div><div class="col-sm-3 form-group"><label>Sesso *</label><select class="form-control" name="patient_gender" required><?php foreach(['M'=>'Maschile','F'=>'Femminile','UN'=>'Non noto'] as $k=>$l): ?><option value="<?= $k ?>" <?= (old('patient_gender') ?? ($doc['patient_gender'] ?? ''))===$k?'selected':'' ?>><?= $l ?></option><?php endforeach ?></select></div><div class="col-sm-6 form-group"><label>Email</label><input id="patient_email" class="form-control" type="email" name="patient_email" value="<?= $value('patient_email') ?>"></div><div class="col-sm-7 form-group"><label>Indirizzo</label><input id="patient_address" class="form-control" name="patient_address" value="<?= $value('patient_address') ?>"></div><div class="col-sm-5 form-group"><label>Città</label><input id="patient_city" class="form-control" name="patient_city" value="<?= $value('patient_city') ?>"></div></div>
<hr><h3>Prestazione e referto RSA</h3><div class="row"><div class="col-sm-8 form-group"><label>Titolo documento *</label><input class="form-control" name="document_title" required value="<?= $value('document_title','Referto di Specialistica Ambulatoriale') ?>"></div><div class="col-sm-4 form-group"><label>Regime</label><select class="form-control" name="administrative_request"><?php foreach($requests as $k=>$l): ?><option value="<?= esc($k) ?>" <?= (old('administrative_request') ?? ($doc['administrative_request'] ?? 'NOSSN'))===$k?'selected':'' ?>><?= esc($l) ?></option><?php endforeach ?></select></div><div class="col-sm-6 form-group"><label>Inizio prestazione *</label><input class="form-control" type="datetime-local" name="service_start" required value="<?= $dateValue('service_start') ?>"></div><div class="col-sm-6 form-group"><label>Fine prestazione</label><input class="form-control" type="datetime-local" name="service_end" value="<?= $dateValue('service_end') ?>"></div><input type="hidden" name="loinc_code" value="<?= $value('loinc_code','11488-4') ?>"><input type="hidden" name="loinc_display_name" value="<?= $value('loinc_display_name','Nota di consulto') ?>"></div>
<?php foreach(['reason_text'=>'Motivo della visita','history_text'=>'Anamnesi','findings_text'=>'Reperti','report_text'=>'Referto *','diagnosis_text'=>'Diagnosi','conclusions_text'=>'Conclusioni'] as $k=>$label): ?><div class="form-group"><label><?= $label ?></label><textarea class="form-control" name="<?= $k ?>" <?= $k==='report_text'?'required':'' ?>><?= $value($k) ?></textarea></div><?php endforeach ?>
<div class="checkbox"><label><input type="hidden" name="patient_consent" value="0"><input type="checkbox" name="patient_consent" value="1" <?= (old('patient_consent') ?? ($doc['patient_consent'] ?? 1)) ? 'checked':'' ?>> Paziente preso in carico ai fini FSE (claim patient_consent)</label></div>
<?php if(!$locked): ?><button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Salva bozza</button><?php endif ?></form>
<?php if($id): ?><div class="fse-box"><h3>Firma e Gateway</h3><p class="text-muted">Il gestionale genera CDA e PDF. La firma qualificata PAdES viene applicata con il dispositivo/servizio di firma autorizzato e il PDF firmato viene poi ricaricato.</p><div class="actions">
<?php if(!in_array($state,['published','deleted','publishing'],true)): ?><form method="post" action="<?= site_url('admin/fse2/documenti/prepara/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-info"><i class="fa fa-file-pdf-o"></i> Genera CDA + PDF</button></form><?php endif ?>
<?php if(!empty($doc['cda_path'])): ?><a class="btn btn-default" href="<?= site_url('admin/fse2/documenti/download/'.$id.'/cda') ?>">Scarica CDA</a><?php endif ?> <?php if(!empty($doc['unsigned_pdf_path'])): ?><a class="btn btn-default" href="<?= site_url('admin/fse2/documenti/download/'.$id.'/unsigned') ?>">Scarica PDF da firmare</a><?php endif ?> <?php if(!empty($doc['signed_pdf_path'])): ?><a class="btn btn-default" href="<?= site_url('admin/fse2/documenti/download/'.$id.'/signed') ?>">Scarica firmato</a><?php endif ?>
</div><?php if($state==='validated'): ?><form method="post" enctype="multipart/form-data" action="<?= site_url('admin/fse2/documenti/firma/'.$id) ?>" style="margin-top:15px"><?= csrf_field() ?><div class="row"><div class="col-sm-8"><input class="form-control" type="file" name="signed_pdf" accept="application/pdf" required></div><div class="col-sm-4"><button class="btn btn-warning"><i class="fa fa-upload"></i> Acquisisci PAdES</button></div></div></form><?php endif ?>
<hr><div class="actions"><?php if(in_array($state,['ready_to_validate','rejected'],true)): ?><form method="post" action="<?= site_url('admin/fse2/documenti/valida/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-default">Valida PDF/CDA sul Gateway</button></form><?php endif ?><?php if($state==='signed'): ?><form method="post" action="<?= site_url('admin/fse2/documenti/pubblica/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-success">Pubblica PDF firmato</button></form><?php endif ?><?php if(!empty($doc['workflow_instance_id']) && in_array($state,['publishing','published','deleting'],true)): ?><form method="post" action="<?= site_url('admin/fse2/documenti/stato/'.$id) ?>"><?= csrf_field() ?><button class="btn btn-info">Aggiorna stato</button></form><?php endif ?><?php if($state==='published'): ?><form method="post" action="<?= site_url('admin/fse2/documenti/elimina/'.$id) ?>" onsubmit="return confirm('Eliminare il documento pubblicato dal FSE?')"><?= csrf_field() ?><button class="btn btn-danger">Elimina dal FSE</button></form><?php endif ?></div>
<?php if(!empty($doc['workflow_instance_id'])): ?><p><strong>Workflow:</strong> <?= esc((string)$doc['workflow_instance_id']) ?><br><strong>Stato Gateway:</strong> <?= esc((string)($doc['gateway_state'] ?? '-')) ?><br><strong>Ultimo messaggio:</strong> <?= esc((string)($doc['last_gateway_message'] ?? '-')) ?></p><?php endif ?></div>
<div class="fse-box"><h3>Audit</h3><?php if(!$events): ?><p class="text-muted">Nessun evento.</p><?php else: ?><table class="table table-condensed"><thead><tr><th>Data</th><th>Evento</th><th>Messaggio</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= esc((string)$event['created_at']) ?></td><td><?= esc((string)$event['event_type']) ?></td><td><?= esc((string)$event['message']) ?></td></tr><?php endforeach ?></tbody></table><?php endif ?></div><?php endif ?>
</main></div></section></div><footer class="main-footer"><strong>&copy; AmbulatorioFacile</strong></footer></div><script src="<?= base_url('public/plugins/jQuery/jQuery-2.1.4.min.js') ?>"></script><script src="<?= base_url('public/bootstrap/js/bootstrap.min.js') ?>"></script><script>
(function(){var q=document.getElementById('patient-search'), box=document.getElementById('patient-results'), timer;if(!q)return;q.addEventListener('input',function(){clearTimeout(timer);var term=q.value.trim();if(term.length<2){box.hidden=true;return}timer=setTimeout(function(){fetch('<?= site_url('admin/fse2/documenti/pazienti/search') ?>?term='+encodeURIComponent(term),{credentials:'same-origin'}).then(function(r){return r.json()}).then(function(data){box.innerHTML='';(data.results||[]).forEach(function(p){var b=document.createElement('button');b.type='button';b.textContent=(p.label||'')+' · '+(p.patient_tax_code||'');b.onclick=function(){['id_client','patient_first_name','patient_last_name','patient_cf','patient_email','patient_address','patient_city'].forEach(function(id){var map={id_client:'id_client',patient_first_name:'patient_first_name',patient_last_name:'patient_last_name',patient_cf:'patient_tax_code',patient_email:'patient_email',patient_address:'patient_address',patient_city:'patient_city'};document.getElementById(id).value=p[map[id]]||''});box.hidden=true};box.appendChild(b)});box.hidden=box.children.length===0})},250)})})();
</script></body></html>
