<?php
$documents=$listing['documents']??[];
$capabilities=$capabilities??[];
$money=static fn($c)=>'€ '.number_format($c/100,2,',','.');
$doctors=[];
foreach($documents as $document) foreach($document['doctors']??[] as $id=>$name) $doctors[$id]=$name;
$tsEnabled=!empty($tsEnabled);
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fatturazione · AmbulatorioFacile</title>
<link rel="stylesheet" href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/dist/css/AdminLTE.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/fontawesome/css/all.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/fontawesome/css/v4-shims.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/css/billing-ts-ui.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/css/billing-workspace.css?v=20260927-icons') ?>">
</head><body class="skin-blue sidebar-mini billing-ts-ui module-fatturazione">
<div class="wrapper"><?= view('partials/header',['menu_items'=>$menu_items??[]]) ?>
<div class="content-wrapper"><section class="content billing-archive-content"><div class="row billing-archive-layout">
<aside class="col-md-3 billing-archive-nav"><?= view('partials/sidebar_admin',['menu_items'=>$menu_items??[]]) ?></aside>
<div class="col-md-9"><main class="billing-workspace bw-content" id="billing-workspace">
<header class="bw-heading"><div><h1>Fatturazione</h1><p>Documenti, incassi e compensi in un unico spazio</p></div><a class="bw-button bw-primary" href="<?= site_url('admin/fatturazione-documenti/nuovo') ?>"><span aria-hidden="true">＋</span> Nuova fattura</a></header>
<p class="bw-settings-link"><a href="<?= site_url('admin/fatturazione-documento') ?>">Impostazioni documento</a></p>
<?= view('admin/billing/navigation',['tenantScope'=>$tenantScope,'activeBillingTab'=>'Documenti']) ?>
<?php foreach(['success'=>'success','warning'=>'warning'] as $key=>$tone): if(!empty($$key)): ?><div class="alert alert-<?= $tone ?>"><?= esc($$key) ?></div><?php endif; endforeach ?>
<?php if(!empty($errors['generic'])): ?><div class="alert alert-danger"><?= esc($errors['generic']) ?></div><?php endif ?>
<?php if(empty($listing['table_available'])): ?><div class="alert alert-warning"><?= esc($listing['schema_message']??'Archivio non disponibile.') ?></div><?php endif ?>
<div class="bw-kpis" aria-label="Riepilogo documenti filtrati">
<?php foreach([['net','Fatturato netto','bar-chart','teal'],['cash','Incassato','database','green'],['due','Da incassare','clock-o','amber'],[!empty($capabilities['billing_compensation'])?'fees':'drafts',!empty($capabilities['billing_compensation'])?'Compensi da liquidare':'Bozze','user','blue']] as [$key,$label,$icon,$tone]): ?>
<article class="bw-kpi"><span class="bw-kpi-icon <?= $tone ?>" aria-hidden="true"><i class="fa fa-<?= $icon ?>"></i></span><div><span><?= $label ?></span><strong id="bw-kpi-<?= $key ?>">—</strong></div></article>
<?php endforeach ?>
</div>
<div class="bw-toolbar"><label class="bw-search"><span aria-hidden="true">⌕</span><input id="bw-search" type="search" aria-label="Cerca paziente o documento" placeholder="Cerca paziente o documento"></label>
<label><span class="sr-only">Periodo</span><select id="bw-period"><option value="">Tutti i periodi</option><?php $months=array_unique(array_map(static fn($d)=>substr($d['issue_date']??'',0,7),$documents)); rsort($months); $monthNames=['','Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre']; foreach($months as $month): if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month)) continue; ?><option value="<?= esc($month) ?>"><?= $monthNames[(int)substr($month,5,2)].' '.substr($month,0,4) ?></option><?php endforeach ?></select></label>
<?php if($doctors): ?><label><span class="sr-only">Medico</span><select id="bw-doctor"><option value="">Tutti i medici</option><?php foreach($doctors as $id=>$name): ?><option value="<?= (int)$id ?>"><?= esc($name) ?></option><?php endforeach ?></select></label><?php endif ?>
<label><span class="sr-only">Stato</span><select id="bw-status"><option value="">Tutti gli stati</option><?php foreach(['Saldata','Parziale','Quota ente','Rettificata','Nota di credito','Da incassare','Bozza'] as $status): ?><option><?= $status ?></option><?php endforeach ?></select></label>
<details class="bw-more-filters"><summary>Altri filtri</summary><label>Tipo documento<select id="bw-type"><option value="">Tutti</option><option value="invoice">Fatture</option><option value="receipt">Ricevute</option><option value="credit_note">Note di credito</option></select></label><label>Sistema TS<select id="bw-ts"><option value="">Tutti</option><option value="selectable">Selezionabili per TS</option><option value="sent">Inviati</option><option value="sending">In invio</option></select></label><label>Incassi ed email<select id="bw-collection"><option value="">Tutti</option><option value="overdue">Scadute</option><option value="to_send">Email da inviare</option></select></label><button class="bw-button" type="button" id="bw-reset">Azzera filtri</button></details>
</div>
<p class="bw-scope">Riepilogo dei documenti nell’elenco filtrato · fino agli ultimi 250 documenti. <a href="<?= site_url('admin/fatturazione-statistiche') ?>">Report completo</a></p>
<?php if($tsEnabled): ?><form method="post" id="bw-bulk-form" action="<?= site_url('admin/sistema-ts/documenti/send-bulk-billing') ?>"><?= csrf_field() ?><input type="hidden" name="return_to" value="billing_archive"><div id="bw-bulk-inputs"></div><div class="bw-bulk"><label><input type="checkbox" id="bw-select-all"> Seleziona tutte le fatture filtrate disponibili per TS</label><button class="bw-button" id="bw-send" disabled>Invia selezionate a TS <span id="bw-selected-count">(0)</span></button></div></form><?php endif ?>
<div class="bw-document-layout">
<div class="bw-list-column"><section class="bw-table-card"><div class="bw-table-scroll"><table class="bw-table"><thead><tr><?php if($tsEnabled): ?><th class="bw-check-cell"><span class="sr-only">Selezione TS</span></th><?php endif ?><th><button type="button" id="bw-sort">Documento ↕</button></th><th>Paziente</th><th class="bw-amount">Totale</th><th>Stato</th></tr></thead><tbody>
<?php foreach($documents as $row): $id=(int)$row['id_billing_document']; $selectable=$tsEnabled && empty($row['ts_blocking_reason']) && $row['local_state']==='issued' && !empty($row['ts_sync_enabled']) && !in_array($row['ts_sync_state'],['sent','sending'],true); $row['ts_selectable']=$selectable; ?>
<tr class="bw-row" data-id="<?= $id ?>"><?php if($tsEnabled): ?><td class="bw-check-cell"><?php if($selectable): ?><input type="checkbox" class="bw-select" value="<?= $id ?>" aria-label="Seleziona <?= esc($row['document_number']) ?> per TS"><?php else: ?><span title="<?= esc($row['ts_blocking_reason']??'Documento non disponibile per invio TS') ?>">—</span><?php endif ?></td><?php endif ?>
<td><button class="bw-open-document" type="button" aria-controls="bw-detail"><?= esc($row['document_number']) ?></button><small><?= esc($row['issue_date']) ?></small></td><td><?= esc($row['patient_name']) ?></td><td class="bw-amount"><?= $money($row['signed_total_cents']) ?></td><td><span class="bw-status <?= esc($row['status_tone']) ?>"><?= esc($row['status_label']) ?></span></td></tr>
<template id="bw-detail-<?= $id ?>"><article class="bw-detail-card"><header><h2><?= esc($row['document_number']) ?> · <?= esc($row['patient_name']) ?></h2><a href="<?= site_url('admin/fatturazione-documenti/modifica/'.$id) ?>" aria-label="Apri documento completo">↗</a></header>
<div class="bw-detail-meta"><?php foreach($row['services'] as $description): ?><p><i class="fa fa-stethoscope" aria-hidden="true"></i> <?= esc($description) ?></p><?php endforeach ?><?php foreach($row['doctors'] as $doctor): ?><p><i class="fa fa-user" aria-hidden="true"></i> <?= esc($doctor) ?></p><?php endforeach ?><?php foreach($row['agreements'] as $agreement): ?><p><i class="fa fa-shield" aria-hidden="true"></i> <?= esc($agreement) ?></p><?php endforeach ?><p>Emissione <?= esc($row['issue_date']) ?> · <?= esc($listing['document_type_labels'][$row['document_type']]??$row['document_type']) ?></p></div>
<div class="bw-breakdown"><?php $b=$row['balance']; foreach(['patient'=>'Paziente','organization'=>'Ente / assicurazione'] as $payer=>$label): if($payer==='organization' && !$b['organization_net_cents']) continue; ?><div><span><?= $label ?></span><strong><?= $money($b[$payer.'_net_cents']) ?></strong><span class="<?= $b[$payer.'_paid_cents'] >= $b[$payer.'_net_cents']?'green':'amber' ?>"><?= $row['document_type']==='credit_note'?'Storno':($row['local_state']==='draft'?'Bozza':($b[$payer.'_paid_cents'] >= $b[$payer.'_net_cents']?'Pagati':'Da incassare')) ?></span></div><?php endforeach ?></div>
<?php if($b['paid_cents']>0 && $b['due_cents']>0): ?><p>Incassato <?= $money($b['paid_cents']) ?> · Residuo <?= $money($b['due_cents']) ?></p><?php endif ?>
<?php if($b['credit_cents']>0): ?><p>Note di credito <?= $money($b['credit_cents']) ?> · Netto <?= $money($b['net_cents']) ?></p><?php endif ?>
<?php if($row['managed'] && !empty($capabilities['billing_compensation'])): ?><div class="bw-fee"><span>Compenso maturato</span><strong><?= $money($row['earned_cents']) ?></strong></div><?php endif ?>
<div class="bw-detail-actions">
<?php if($row['managed'] && $row['document_type']==='invoice'): ?><a class="bw-button bw-primary" href="<?= site_url('admin/fatturazione/gestione?tab=documenti&document='.$id.'#pc-payments') ?>">Registra incasso</a>
<?php elseif($row['local_state']==='issued' && $row['payment_status']!=='paid' && $row['document_type']!=='credit_note'): ?><form method="post" action="<?= site_url('admin/fatturazione-documenti/pagamento/'.$id) ?>" onsubmit="return confirm('Confermi la registrazione del saldo della fattura?')"><?= csrf_field() ?><input type="hidden" name="payment_status" value="paid"><label>Data incasso<input name="payment_date" type="date" value="<?= date('Y-m-d') ?>" required></label><button class="bw-button bw-primary">Registra saldo</button></form><?php endif ?>
<div class="bw-paired"><a class="bw-button" href="<?= site_url('admin/fatturazione-documenti/pdf/'.$id) ?>">Apri PDF</a><?php if($row['managed'] && $row['document_type']==='invoice'): ?><a class="bw-button" href="<?= site_url('admin/fatturazione/gestione?tab=documenti&document='.$id.'#pc-credit') ?>">Nota di credito</a><?php else: ?><a class="bw-button" href="<?= site_url('admin/fatturazione-documenti/modifica/'.$id) ?>"><?= empty($row['can_edit'])?'Apri documento':'Modifica' ?></a><?php endif ?></div>
<details><summary>Altre azioni e stato</summary><p>Documento: <?= esc($listing['local_state_labels'][$row['local_state']]??$row['local_state']) ?></p><p>Sistema TS: <?= esc($listing['ts_sync_labels'][$row['ts_sync_state']]??$row['ts_sync_state']) ?></p><?php if(!empty($row['ts_blocking_reason'])): ?><p><?= esc($row['ts_blocking_reason']) ?></p><?php endif ?>
<a class="bw-button" href="<?= site_url('admin/fatturazione-documenti/preview/'.$id) ?>">Anteprima</a>
<?php if($row['local_state']==='issued'): ?><a class="bw-button" href="<?= site_url('admin/fatturazione-documenti/email/'.$id) ?>">Invia via email</a><?php if($row['payment_status']!=='paid' && !empty($row['invoice_email_sent_at'])): ?><a class="bw-button" href="<?= site_url('admin/fatturazione-documenti/email/'.$id.'?type=reminder') ?>">Invia sollecito</a><?php endif ?><?php endif ?>
<?php if(!empty($row['linked_ts_document_id'])): ?><a class="bw-button" href="<?= site_url('admin/sistema-ts/documenti/modifica/'.(int)$row['linked_ts_document_id']) ?>">Apri documento TS</a><?php endif ?>
<?php if(!$row['managed'] && $row['payment_status']==='paid' && $row['local_state']==='issued'): ?><form method="post" action="<?= site_url('admin/fatturazione-documenti/pagamento/'.$id) ?>" onsubmit="return confirm('Annullare la registrazione del pagamento?')"><?= csrf_field() ?><input type="hidden" name="payment_status" value="unpaid"><button class="bw-button">Annulla pagamento</button></form><?php endif ?>
<?php if(!$row['managed'] && !empty($row['can_delete'])): ?><form method="post" action="<?= site_url('admin/fatturazione-documenti/elimina/'.$id) ?>" onsubmit="return confirm('Confermi la cancellazione del documento?')"><?= csrf_field() ?><button class="bw-button bw-danger">Elimina documento</button></form><?php endif ?>
</details></div></article></template>
<?php endforeach ?>
</tbody></table></div><div class="bw-empty" id="bw-empty" hidden>Nessun documento con questi filtri.</div><footer class="bw-list-footer"><span id="bw-count"></span><span>Seleziona un documento per vedere il dettaglio</span></footer></section>
<section class="bw-connections"><strong>Collegamenti</strong><?php if($tsEnabled): ?><a class="bw-status muted" href="<?= site_url('admin/sistema-ts/documenti') ?>">Sistema TS · documenti e invio cumulativo</a><?php endif ?><?php if(!empty($workspaceUnified)): ?><a class="bw-status blue" href="<?= site_url('admin/fatturazione/gestione?tab=integrazioni') ?>">SdI · XML e simulazione</a><a class="bw-status muted" href="<?= site_url('admin/fatturazione/gestione?tab=integrazioni') ?>">Commercialista · CSV</a><?php endif ?></section>
</div><aside id="bw-detail" aria-label="Dettaglio fattura" aria-live="polite"><div class="bw-detail-card bw-empty">Seleziona una fattura nell’elenco.</div></aside>
</div>
<script type="application/json" id="bw-data"><?= json_encode(array_map(static function($row) use($tsEnabled){return ['id'=>(int)$row['id_billing_document'],'number'=>$row['document_number'],'patient'=>$row['patient_name'],'tax'=>$row['patient_tax_code']??'','date'=>$row['issue_date'],'doctors'=>array_keys($row['doctors']),'status'=>$row['status_label'],'type'=>$row['document_type'],'ts'=>$row['ts_sync_state'],'net'=>$row['revenue_cents'],'cash'=>$row['cash_cents'],'due'=>$row['outstanding_cents'],'fees'=>$row['fee_due_cents'],'draft'=>$row['local_state']==='draft','email_sent'=>!empty($row['invoice_email_sent_at']),'overdue'=>$row['local_state']==='issued' && $row['outstanding_cents']>0 && !empty($row['due_date']) && $row['due_date']<date('Y-m-d')];},$documents),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR) ?></script>
</main></div></div></section></div></div><script src="<?= base_url('public/assets/js/billing-workspace.js?v=20260927-icons') ?>"></script></body></html>
