<?php helper(['portal','form']); ?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gestione menu · AmbulatorioFacile</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:#203d4b;font:15px/1.5 system-ui,sans-serif}header{background:white;border-bottom:1px solid #dce5ec;padding:20px 4%}header a{color:#126b74}main{max-width:1400px;margin:auto;padding:24px}h1{margin:5px 0}p{color:#5c7280}button,select,input{font:inherit;border:1px solid #c7d6df;border-radius:7px;padding:9px;background:white;color:inherit}button{cursor:pointer}button:hover{background:#e8f3f4}button:disabled{opacity:.45;cursor:default}button.primary{background:#087b85;color:white;border:0}label{display:block;margin:14px 0 5px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:18px 0}.columns{display:grid;grid-template-columns:minmax(300px,1.2fr) minmax(260px,1fr) minmax(240px,.8fr);gap:18px}.panel{background:white;padding:20px;border:1px solid #dce5ec;border-radius:12px;min-width:0}.panel h2{font-size:17px;margin:0 0 12px}.row{display:flex;align-items:center;gap:8px;border:1px solid transparent;border-radius:7px;padding:9px;cursor:pointer;margin:3px 0}.row:hover{background:#f2f7f8}.row.selected{background:#e4f3f4;border-color:#14828c}.row.hidden{opacity:.5}.row svg,.preview svg{width:19px;height:19px;flex-shrink:0}.row .name{flex:1}.badge{font-size:11px;color:#607682}.fields input:not([type=checkbox]),.fields select{width:100%}.preview details{padding:7px 0}.preview summary{cursor:pointer;display:flex;align-items:center;gap:8px;font-weight:600}.preview .leaf{display:flex;gap:8px;padding:8px;color:#45616f}.preview .children{border-left:1px solid #d7e4eb;margin-left:9px;padding-left:12px}.notice{padding:12px;border-radius:7px;background:#e9f5ed}#message{color:#ad361e}#dirty{color:#975b0b}small{color:#667c89}@media(max-width:950px){.columns{grid-template-columns:1fr}.preview{min-height:180px}}:focus-visible{outline:2px solid #087b85;outline-offset:2px}
@media(min-width:951px){.panel{max-height:66vh;overflow:auto}}#scope{max-width:100%}
</style></head><body><header><a href="<?= esc(portal_platform_url('spazi-clienti')) ?>">← Console piattaforma</a><h1>Gestione menu</h1><span>Menu, sottomenu e collegamenti diretti alle pagine esistenti</span></header><main>
<?php if($success=session()->getFlashdata('success')): ?><div class="notice" role="status"><?= esc($success) ?></div><?php endif ?>
<form method="get"><label for="scope">Disposizione da modificare</label><select id="scope" name="spazio" onchange="this.form.submit()"><option value="0">Predefinita per tutti gli spazi</option><?php foreach($tenants as $tenant): $id=(int)$tenant['id_tenant']; ?><option value="<?= $id ?>" <?= $layout['scope']===$id?'selected':'' ?>><?= esc($tenant['tenant_name']??$tenant['name']??$tenant['slug']??('Spazio '.$id)) ?></option><?php endforeach ?></select></form>
<p><?= $layout['scope']===0?'Le modifiche si applicano agli spazi che seguono la disposizione predefinita.':($layout['inherited']?'Questo spazio segue la disposizione predefinita. Salvando crei una personalizzazione solo per questo spazio.':'Questo spazio ha una disposizione personalizzata.') ?> Moduli abilitati e permessi continuano a filtrare le voci per ciascun utente.</p>
<form id="save-form" method="post" action="<?= esc(portal_platform_url('menu/save')) ?>"><?= csrf_field() ?><input type="hidden" name="scope" value="<?= $layout['scope'] ?>"><input type="hidden" name="version" value="<?= $layout['version'] ?>"><input type="hidden" name="globalVersion" value="<?= $layout['globalVersion'] ?>"><input type="hidden" name="nodes" id="nodes-input"><input type="hidden" name="action" id="action-input" value="save">
<div class="toolbar"><button type="button" id="add">+ Nuovo sottomenu</button><button class="primary" type="submit">Salva disposizione</button><button type="button" id="restore" <?= !$layout['canRestore']?'disabled':'' ?>>Ripristina precedente</button><?php if($layout['scope']>0): ?><button type="button" id="inherit" <?= $layout['inherited']?'disabled':'' ?>>Usa disposizione predefinita</button><?php endif ?><span id="dirty" role="status"></span></div></form>
<div id="message" role="alert"></div><div class="columns"><section class="panel"><h2>Struttura del menu</h2><small>Seleziona una voce. Trascinala su un’altra per spostarla nello stesso livello; usa “Dentro il menu” per cambiare sottomenu.</small><div id="tree"></div></section><section class="panel fields"><h2>Modifica voce</h2><div id="empty">Seleziona una voce nella struttura.</div><div id="fields" hidden><label for="label">Nome</label><input id="label" maxlength="90"><label for="icon">Icona</label><select id="icon"><?php foreach($icons as $icon): ?><option><?= esc($icon) ?></option><?php endforeach ?></select><label for="parent">Dentro il menu</label><select id="parent"></select><label><input type="checkbox" id="hidden"> Nascondi questa voce</label><div class="toolbar"><button id="up" type="button">↑ Su</button><button id="down" type="button">↓ Giù</button></div><small id="destination"></small></div></section><section class="panel"><h2>Anteprima interattiva</h2><small>Mostra la disposizione. Le pagine non si aprono dall’editor; nel menu dell’app si aprono direttamente. Le sezioni vuote vengono nascoste.</small><div id="preview" class="preview"></div></section></div><p><small>Il catalogo acquisisce le voci dei menu esistenti quando vengono aperti dagli utenti. Le nuove funzioni si aggiungono senza spostare le voci già personalizzate. Nascondere una voce non revoca i permessi sulla pagina.</small></p>
</main><script type="application/json" id="layout-data"><?= json_encode($layout['nodes'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><script type="application/json" id="icons-data"><?= json_encode(array_combine($icons,array_map([\App\Services\UnifiedMenuService::class,'icon'],$icons)),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><script>
(()=>{'use strict';let nodes=JSON.parse(document.getElementById('layout-data').textContent),selected=null,dragged=null,dirty=false;
const icons=JSON.parse(document.getElementById('icons-data').textContent),$=id=>document.getElementById(id),find=id=>nodes.find(n=>n.id===id);
function icon(name){const el=document.createElement('span');el.innerHTML=icons[name]||icons.Impostazioni;return el.firstChild;}
function changed(){dirty=true;$('dirty').textContent='Modifiche da salvare';render();}
function below(id,ancestor){let seen=new Set;while(id){if(id===ancestor)return true;if(seen.has(id))return true;seen.add(id);id=find(id)?.parent||'';}return false;}
function renderTree(parent,host,depth=0){for(const n of nodes.filter(n=>n.parent===parent)){const row=document.createElement('div');row.className='row'+(selected===n.id?' selected':'')+(n.hidden?' hidden':'');row.style.marginLeft=(depth*16)+'px';row.tabIndex=0;row.draggable=true;row.dataset.id=n.id;row.setAttribute('role','button');row.setAttribute('aria-label',n.label);row.append(icon(n.icon));const text=document.createElement('span');text.className='name';text.textContent=n.label;row.append(text);const badge=document.createElement('span');badge.className='badge';badge.textContent=n.type==='group'?'Menu':'Pagina';row.append(badge);row.onclick=()=>{selected=n.id;render();};row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selected=n.id;render();}};row.ondragstart=e=>{dragged=n.id;e.dataTransfer.setData('text/plain',n.id);};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();const moving=find(dragged);if(!moving||moving.id===n.id||below(n.parent,moving.id))return;moving.parent=n.parent;nodes=nodes.filter(x=>x.id!==moving.id);nodes.splice(nodes.findIndex(x=>x.id===n.id),0,moving);changed();};host.append(row);if(n.type==='group')renderTree(n.id,host,depth+1);}}
function preview(parent,host){let count=0;for(const n of nodes.filter(n=>n.parent===parent&&!n.hidden)){if(n.type==='group'){const d=document.createElement('details'),s=document.createElement('summary'),children=document.createElement('div');children.className='children';if(!preview(n.id,children))continue;s.append(icon(n.icon),document.createTextNode(n.label));d.append(s,children);host.append(d);}else{const a=document.createElement('div');a.className='leaf';a.append(icon(n.icon),document.createTextNode(n.label));host.append(a);}count++;}return count;}
function render(){ $('tree').replaceChildren();renderTree('',$('tree'));$('preview').replaceChildren();preview('',$('preview'));const n=find(selected);$('empty').hidden=!!n;$('fields').hidden=!n;if(!n)return;$('label').value=n.label;$('label').disabled=!!n.runtime_label;$('icon').value=n.icon;$('hidden').checked=n.hidden;$('parent').replaceChildren(new Option('Livello principale',''));for(const g of nodes.filter(x=>x.type==='group'&&!below(x.id,n.id)))$('parent').add(new Option(g.label,g.id));$('parent').value=n.parent;$('destination').textContent=n.runtime_label?'Il nome viene adattato automaticamente all’account corrente.':n.type==='link'?'Collegamento a una pagina esistente. Spostarlo non modifica i permessi.':'Contiene le voci di menu assegnate a questo gruppo.';}
$('label').oninput=()=>{const n=find(selected);n.label=$('label').value;dirty=true;$('dirty').textContent='Modifiche da salvare';$('tree').replaceChildren();renderTree('',$('tree'));$('preview').replaceChildren();preview('',$('preview'));};
for(const field of ['icon','parent','hidden'])$(field).onchange=()=>{const n=find(selected);n[field]=field==='hidden'?$(field).checked:$(field).value;changed();};
function move(step){const n=find(selected);if(!n)return;const siblings=nodes.filter(x=>x.parent===n.parent),at=siblings.findIndex(x=>x.id===n.id),other=siblings[at+step];if(!other)return;const a=nodes.indexOf(n),b=nodes.indexOf(other);[nodes[a],nodes[b]]=[nodes[b],nodes[a]];changed();}
$('up').onclick=()=>move(-1);$('down').onclick=()=>move(1);$('add').onclick=()=>{const n={id:'g_'+crypto.randomUUID(),parent:'',label:'Nuovo sottomenu',icon:'Impostazioni',type:'group',hidden:false};nodes.push(n);selected=n.id;changed();$('label').focus();$('label').select();};
function submit(action){$('action-input').value=action;$('save-form').requestSubmit();}
$('restore').onclick=()=>submit('restore');if($('inherit'))$('inherit').onclick=()=>submit('inherit');
$('save-form').onsubmit=e=>{if($('action-input').value==='save'&&nodes.some(n=>!n.label.trim())){e.preventDefault();$('message').textContent='Inserisci un nome per ogni voce.';return;} $('nodes-input').value=JSON.stringify(nodes);dirty=false;};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});render();})();
</script></body></html>
