<?php
helper('portal');
$menuDataAdmin = session()->get('menuDataAdmin');
$menu_items = is_array($menuDataAdmin['result'] ?? null) ? $menuDataAdmin['result'] : [];
$dashboard = is_array($dashboard ?? null) ? $dashboard : [];
$summary = is_array($dashboard['summary'] ?? null) ? $dashboard['summary'] : [];
$campaigns = is_array($dashboard['campaigns'] ?? null) ? $dashboard['campaigns'] : [];
$selected = is_array($dashboard['selected_campaign'] ?? null) ? $dashboard['selected_campaign'] : null;
$recipients = is_array($dashboard['recipients'] ?? null) ? $dashboard['recipients'] : [];
$errors = is_array($errors ?? null) ? $errors : [];
$format = static function ($value) { $value = trim((string) $value); if ($value === '') return '—'; try { return (new DateTimeImmutable($value))->setTimezone(new DateTimeZone('Europe/Rome'))->format('d/m/Y H:i'); } catch (Throwable $e) { return $value; } };
$labels = ['queued'=>'In coda','running'=>'In corso','completed'=>'Completata','pending'=>'In attesa','processing'=>'In invio','sent'=>'Inviato','failed'=>'Non inviato'];
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invii WhatsApp</title>
<link href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet"><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link href="<?= base_url('public/dist/css/AdminLTE.css') ?>" rel="stylesheet"><link href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>" rel="stylesheet">
<style>.campaign-box{border:1px solid #dfe7e8;border-radius:12px;padding:20px;background:#fff;margin-bottom:18px}.campaign-intro{background:linear-gradient(135deg,#f1fbf7,#f9fcfd)}.metric{border:1px solid #e2e8ea;border-radius:10px;padding:13px;margin-bottom:12px;background:#fbfcfc}.metric b{display:block;font-size:23px;color:#16745a}.note{color:#65757a;font-size:12px}.status{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef3f4;font-size:11px;font-weight:700}.status.sent,.status.completed{background:#e8f8ef;color:#15704f}.status.failed{background:#fff0ee;color:#b42318}.status.queued,.status.pending,.status.running,.status.processing{background:#fff8e8;color:#8b6300}.campaign-message{white-space:pre-wrap;max-width:380px}.table>tbody>tr>td{vertical-align:middle}.page-wrap{padding:20px}</style></head>
<body class="hold-transition skin-blue sidebar-mini"><div class="wrapper"><?php include APPPATH . 'Views/agenda/partials/menu_laterale.php'; ?><div class="content-wrapper"><section class="content page-wrap">
<div class="campaign-box campaign-intro"><h3 style="margin-top:0"><i class="fa fa-whatsapp text-green"></i> Invii WhatsApp</h3><p style="margin-bottom:0">Campagne per tutti i pazienti o per gli appuntamenti di una data. L’invio avviene nel backend, uno alla volta ogni <strong>5 minuti</strong>, anche chiudendo la pagina.</p></div>
<?php if (!empty($success)): ?><div class="alert alert-success"><?= esc($success) ?></div><?php endif; ?><?php foreach ($errors as $error): ?><div class="alert alert-danger"><?= esc($error) ?></div><?php endforeach; ?>
<div class="row"><div class="col-sm-3"><div class="metric"><span class="note">Campagne</span><b><?= (int)($summary['total'] ?? 0) ?></b></div></div><div class="col-sm-3"><div class="metric"><span class="note">In attesa</span><b><?= (int)($summary['queued'] ?? 0) ?></b></div></div><div class="col-sm-3"><div class="metric"><span class="note">Inviati</span><b><?= (int)($summary['sent'] ?? 0) ?></b></div></div><div class="col-sm-3"><div class="metric"><span class="note">Errori</span><b><?= (int)($summary['failed'] ?? 0) ?></b></div></div></div>
<?php if (empty($dashboard['schema_ready'])): ?><div class="alert alert-warning">La coda campagne sarà disponibile non appena l’aggiornamento database sarà completato.</div><?php else: ?>
<div class="campaign-box"><h4 style="margin-top:0">Nuova campagna</h4><form method="post" action="<?= esc(portal_tenant_space_url('invii-whatsapp/create'), 'attr') ?>"><?= csrf_field() ?><div class="row"><div class="col-md-5"><div class="form-group"><label>Destinatari</label><select class="form-control" id="audience" name="audience_type"><option value="all_patients" <?= old('audience_type') === 'appointments_on_date' ? '' : 'selected' ?>>Tutti i pazienti con cellulare valido</option><option value="appointments_on_date" <?= old('audience_type') === 'appointments_on_date' ? 'selected' : '' ?>>Pazienti con appuntamento in una data</option></select></div></div><div class="col-md-4" id="date-wrap"><div class="form-group"><label>Data appuntamenti</label><input type="date" class="form-control" name="appointment_date" value="<?= esc((string)old('appointment_date'), 'attr') ?>"></div></div></div><div class="form-group"><label>Messaggio</label><textarea class="form-control" name="message_text" rows="5" maxlength="2000" required placeholder="Scrivi il messaggio da inviare..."><?= esc((string)old('message_text')) ?></textarea><p class="note">Sono ammessi solo numeri mobili italiani validi. Un numero duplicato riceve un solo messaggio.</p></div><button class="btn btn-success" type="submit"><i class="fa fa-clock-o"></i> Accoda invii protetti</button></form></div>
<div class="campaign-box"><h4 style="margin-top:0">Registro campagne</h4><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Creata</th><th>Destinatari</th><th>Stato</th><th>Progresso</th><th></th></tr></thead><tbody><?php foreach ($campaigns as $row): ?><tr><td><?= esc($format($row['created_at'] ?? '')) ?></td><td><?= ($row['audience_type'] ?? '') === 'appointments_on_date' ? 'Appuntamenti del ' . esc((string)($row['appointment_date'] ?? '')) : 'Tutti i pazienti' ?></td><td><span class="status <?= esc($row['status'] ?? '', 'attr') ?>"><?= esc($labels[$row['status'] ?? ''] ?? (string)($row['status'] ?? '')) ?></span></td><td><?= (int)($row['sent_recipients'] ?? 0) ?> inviati · <?= (int)($row['pending_recipients'] ?? 0) ?> in attesa · <?= (int)($row['failed_recipients'] ?? 0) ?> errori</td><td><a class="btn btn-default btn-xs" href="<?= esc(portal_tenant_space_url('invii-whatsapp') . '?campaign=' . (int)$row['id_whatsapp_campaign'], 'attr') ?>">Dettaglio</a></td></tr><?php endforeach; ?><?php if ($campaigns === []): ?><tr><td colspan="5" class="text-muted">Nessuna campagna ancora creata.</td></tr><?php endif; ?></tbody></table></div></div>
<?php if ($selected): ?><div class="campaign-box"><h4 style="margin-top:0">Dettaglio campagna #<?= (int)$selected['id_whatsapp_campaign'] ?></h4><p class="campaign-message"><?= esc((string)$selected['message_text']) ?></p><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Paziente</th><th>Numero</th><th>Stato</th><th>Data invio</th><th>Esito</th></tr></thead><tbody><?php foreach ($recipients as $row): ?><tr><td><?= esc((string)($row['patient_name'] ?? 'Paziente')) ?></td><td><?= esc((string)($row['recipient_phone'] ?? '')) ?></td><td><span class="status <?= esc($row['status'] ?? '', 'attr') ?>"><?= esc($labels[$row['status'] ?? ''] ?? (string)($row['status'] ?? '')) ?></span></td><td><?= esc($format($row['sent_at'] ?? '')) ?></td><td><?= esc((string)($row['error_text'] ?? '')) ?></td></tr><?php endforeach; ?><?php if ($recipients === []): ?><tr><td colspan="5" class="text-muted">Nessun destinatario.</td></tr><?php endif; ?></tbody></table></div></div><?php endif; ?><?php endif; ?>
</section></div></div><script src="<?= base_url('public/plugins/jQuery/jquery-2.2.3.min.js') ?>"></script><script>!function(){var a=document.getElementById('audience'),d=document.getElementById('date-wrap');function f(){d.style.display=a.value==='appointments_on_date'?'block':'none'}a.addEventListener('change',f);f()}();</script></body></html>
