<?php helper(['form','session_auth']); $sectionHome=site_url('navigazione/'.$sectionSlug); ?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= esc($sectionName) ?> | AmbulatorioFacile</title>
<style>
body{margin:0;background:#f4f7fa;color:#243849;font:14px/1.5 system-ui,sans-serif}*{box-sizing:border-box}.af-section-header{background:#fff;border-bottom:1px solid #dce5ec;padding:18px 24px;font-size:18px;font-weight:600}.af-section-header span{color:#087f8c}.af-section-shell{display:grid;grid-template-columns:230px minmax(0,1fr);min-height:80vh;max-width:1400px;margin:auto}.af-section-shell aside{background:#fff;border-right:1px solid #dce5ec;padding:16px 10px}.af-section-shell main{padding:28px;min-width:0}h1{font-size:25px;line-height:1.25;margin:5px 0 8px;font-weight:600}.af-section-intro{color:#63798a;margin:0 0 24px}.af-section-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.af-section-tile{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:22px;background:#fff;border:1px solid #dce5ec;border-radius:10px;text-decoration:none;color:#243849}.af-section-tile:hover{border-color:#087f8c;background:#faffff}.af-section-tile small{display:block;color:#63798a;margin-top:5px}.af-section-tile .af-menu-icon{width:22px;height:22px;color:#087f8c;flex-shrink:0}.af-section-links{background:#fff;border:1px solid #dce5ec;border-radius:10px;padding:8px 22px}.af-section-links a{display:flex;justify-content:space-between;gap:16px;padding:17px 0;border-bottom:1px solid #dce5ec;color:#24545b;text-decoration:none}.af-section-links a:last-child{border-bottom:0}.af-section-back{display:inline-block;color:#087f8c;margin-bottom:20px}a:focus-visible{outline:3px solid #087f8c;outline-offset:3px}@media(max-width:650px){.af-section-shell{grid-template-columns:1fr}.af-section-shell aside{border-right:0;border-bottom:1px solid #dce5ec}.af-section-shell main{padding:18px}.af-section-grid{grid-template-columns:1fr}}
</style></head><body>
<header class="af-section-header">Ambulatorio<span>Facile</span></header>
<div class="af-section-shell"><aside><?= view('partials/unified_menu') ?></aside><main>
<?php if ($selectedTile!==''): ?><a class="af-section-back" href="<?= esc($sectionHome) ?>">← <?= esc($sectionName) ?></a><?php endif ?>
<h1><?= esc($selectedTile!==''?$selectedTile:$sectionName) ?></h1>
<p class="af-section-intro"><?= $sectionName==='Impostazioni'?'Configurazione dello spazio, raccolta in un solo posto.':'Scegli l’attività da aprire.' ?></p>
<?php if ($selectedTile===''): ?><div class="af-section-grid">
<?php foreach($sectionTiles as $title=>$items): $href=count($items)===1?$items[0]['href']:$sectionHome.'?'.http_build_query(['sezione'=>$title]); ?>
<a class="af-section-tile" href="<?= esc($href) ?>"><?= \App\Services\UnifiedMenuService::icon($sectionName) ?><div><strong><?= esc($title) ?></strong><small><?= esc(implode(' · ',array_slice(array_column($items,'label'),0,3))) ?></small></div><span aria-hidden="true">›</span></a>
<?php endforeach ?></div>
<?php else: ?><div class="af-section-links"><?php foreach($sectionTiles[$selectedTile] as $link): ?><a href="<?= esc($link['href']) ?>"><span><?= esc($link['label']) ?></span><span aria-hidden="true">›</span></a><?php endforeach ?></div><?php endif ?>
</main></div></body></html>
