<?php use App\Services\AdministrationService as A; include __DIR__.'/layout.php'; $d=$row['data']; $id=$row['id']; $rev=(int)$row['revision']; ?>
<section><h2><?= esc($section==='quotes' ? 'Preventivo':($section==='cases' ? 'Pratica':'Spettanza')) ?> <?= esc(substr($id,0,12)) ?></h2><p><?= esc($patient['patient_name'] ?? (isset($row['staff_id']) ? 'Professionista #'.$row['staff_id']:'')) ?></p><p><strong><?= esc($states[$row['state']] ?? $row['state']) ?></strong> · Revisione <?= $rev ?> · <?= $money($row['total_cents'] ?? $row['amount_cents']) ?></p>
<?php if($section==='quotes'): ?><p>Data <?= esc($d['date']) ?> · Valido fino al <?= esc($row['expires_on']) ?></p><div class="scroll"><table><tr><th>Prestazione</th><th>Quantità</th><th>Prezzo</th><th>Totale</th></tr><?php foreach($d['lines'] as $l): ?><tr><td><?= esc($l['description']) ?><br><small><?= esc($l['list'].' · '.$l['code'].' · '.$l['tax_note']) ?></small></td><td><?= (int)$l['quantity'] ?></td><td><?= $money($l['unit_cents']) ?></td><td><?= $money($l['total_cents']) ?></td></tr><?php endforeach ?></table></div><p>Sconto: <?= $money($d['discount_cents']) ?> · Totale: <strong><?= $money($row['total_cents']) ?></strong></p><p><?= nl2br(esc($d['notes'])) ?></p><a class="button" href="<?= site_url('admin/amministrazione/preventivo/'.$id.'/pdf') ?>">Scarica PDF</a>
<?php if($row['state']==='accepted'): ?><form method="post" action="<?= site_url('admin/amministrazione/preventivo/'.$id.'/fattura') ?>"><?= csrf_field() ?><p>Apri una nuova bozza e verifica intestazione, imposte ed eventuali fatture già emesse per questo preventivo.</p><button>Precompila fattura</button></form><?php endif ?>
<?php elseif($section==='cases'): ?><p>Ente: <?= esc($d['payer_snapshot']['name']) ?> · <?= $row['regime']==='ssn' ? 'Registro SSN':'Convenzione / fondo' ?></p><p>Riferimento: <?= esc($d['reference']) ?> · Scadenza <?= esc($d['due_on']) ?></p><p>Quota ente: <?= $money($row['payer_cents']) ?> · Quota paziente: <?= $money($row['patient_cents']) ?> · Incassi registrati: <?= $money($row['received_cents']) ?></p>
<?php if($row['regime']==='ssn'): ?><p>Prescrizione: <?= esc($d['prescription']) ?> · Esenzione: <?= esc($d['exemption']) ?></p><?php endif ?><p><?= nl2br(esc($d['notes'])) ?></p><a href="<?= site_url('admin/amministrazione/dettaglio/quotes/'.$row['quote_id']) ?>">Preventivo collegato</a>
<?php else: ?><p>Fattura <?= esc($d['billing_snapshot']['number']) ?> del <?= esc($d['billing_snapshot']['date']) ?> · ID <?= (int)$row['billing_id'] ?></p><p>Regola: <?= esc($d['rule_snapshot']['name']) ?> · <?= A::money($d['rule_snapshot']['percent_bps']) ?>% + <?= $money($d['rule_snapshot']['fixed_cents']) ?></p><p>Riferimento attribuzione: <?= esc($d['reference']) ?></p><?php endif ?>
</section>
<?php $allowed=$section==='quotes' ? ['draft'=>['offered','cancelled'],'offered'=>['accepted','rejected','cancelled'],'accepted'=>['cancelled']]:($section==='cases' ? ['draft'=>['authorized','rejected','cancelled'],'authorized'=>['submitted','cancelled'],'submitted'=>['reconciled','rejected'],'rejected'=>['draft']]:['draft'=>['approved','void'],'approved'=>['settled','void'],'settled'=>['void']]); $next=$allowed[$row['state']] ?? [];
if($next): ?><section><h2>Aggiorna stato</h2><?php $start(['quotes'=>'quote_state','cases'=>'case_state','compensation'=>'compensation_state'][$section],$id,$rev); ?><div class="grid"><label>Nuovo stato<select name="target"><?php foreach($next as $n): ?><option value="<?= $n ?>"><?= esc($states[$n]) ?></option><?php endforeach ?></select></label><?php $field('reference','Riferimento / motivazione'); ?></div><?php if($section!=='quotes'): ?><p>“Invio registrato” e “Pagamento registrato” annotano un’operazione già eseguita esternamente. Non effettuano invii o bonifici.</p><?php endif ?><button>Registra stato</button></form></section><?php endif ?>
<?php if($section==='quotes' && $row['state']==='accepted' && (isset($modules['admin_payers']) || isset($modules['admin_ssn']))): ?><section><h2>Apri pratica dal preventivo</h2><p>Una pratica per preventivo. La copertura dell’ente si calcola sul totale scontato: percentuale, meno franchigia, con il massimale per pratica. Verifica i valori rispetto all’autorizzazione ricevuta.</p>
<?php foreach(['payer'=>'admin_payers','ssn'=>'admin_ssn'] as $regime=>$flag): if(!isset($modules[$flag])) continue; ?><details><summary><?= $regime==='ssn' ? 'Registro SSN':'Convenzione, assicurazione o fondo' ?></summary><?php $start('case'); ?><input type="hidden" name="quote_id" value="<?= esc($id,'attr') ?>"><input type="hidden" name="regime" value="<?= $regime ?>"><div class="grid">
<?php if($regime==='payer'): ?><label>Accordo<select name="payer_id" required><?php foreach($payers as $p): ?><option value="<?= esc($p['id'],'attr') ?>"><?= esc($p['data']['name']) ?></option><?php endforeach ?></select></label><?php else: $field('ssn_entity','Ente SSN'); $field('prescription','Riferimento prescrizione'); $field('exemption','Codice esenzione','','text',false); $field('ticket','Quota paziente / ticket EUR','0.00'); endif; $field('reference','Riferimento pratica'); $field('due_on','Scadenza',date('Y-m-d',strtotime('+30 days')),'date'); ?></div><?php $field('notes','Note','','text',false); ?><button>Crea pratica</button></form></details><?php endforeach ?></section><?php endif ?>
<?php if($section==='cases'): ?><section><h2>Incassi</h2><p>Il registro documenta gli incassi; l’emissione fiscale resta nel modulo Fatturazione.</p><?php if(in_array($row['state'],['authorized','submitted'],true)): $start('receipt',$id,$rev); ?><div class="grid"><label>Pagante<select name="party"><option value="patient">Paziente</option><option value="payer">Ente</option></select></label><?php $field('amount','Importo EUR'); $field('paid_on','Data incasso',date('Y-m-d'),'date'); $field('method','Metodo di pagamento'); $field('reference','Riferimento incasso'); ?></div><button>Registra incasso</button></form><?php endif ?>
<?php foreach($row['receipts'] as $receipt): ?><article><p><?= esc($receipt['paid_on']) ?> · <?= $receipt['party']==='payer' ? 'Ente':'Paziente' ?> · <?= $money($receipt['amount_cents']) ?> · <?= (int)$receipt['active'] ? 'Registrato':'Stornato' ?></p><p><?= esc($receipt['data']['reference'].' · '.$receipt['data']['method']) ?></p><?php if((int)$receipt['active']): $start('void_receipt',$id,$rev); ?><input type="hidden" name="receipt_id" value="<?= esc($receipt['id'],'attr') ?>"><?php $field('reference','Motivo storno'); ?><button>Storna registrazione</button></form><?php else: ?><p><?= esc($receipt['data']['void_reason'] ?? '') ?></p><?php endif ?></article><?php endforeach ?></section><?php endif ?>
<section><h2>Storico</h2><?php foreach($d['history'] ?? [] as $event): ?><p><?= esc($event['at']) ?> · <?= esc($states[$event['state']] ?? $event['state']) ?> · <?= esc($event['reference'] ?? '') ?> · Utente #<?= (int)$event['actor'] ?></p><?php endforeach ?><details><summary>Traccia operazioni</summary><div class="scroll"><table><tr><th>Data UTC</th><th>Operazione</th><th>Utente</th><th>Revisione</th></tr><?php foreach($audit as $a): ?><tr><td><?= esc($a['created_at']) ?></td><td><?= esc($a['event']) ?></td><td><?= (int)$a['actor_id'] ?></td><td><?= (int)$a['revision'] ?></td></tr><?php endforeach ?></table></div></details></section></main></body></html>
