<?php use App\Services\AdministrationService as A; include __DIR__.'/layout.php'; ?>
<?php if(!$ready): ?><section><h2>Prepara gli archivi dello spazio</h2><p>Attiva gli archivi necessari ai moduli amministrativi abilitati.</p><?php $start('prepare'); ?><button>Prepara archivi</button></form></section>
<?php else: ?>
<?php if($section==='catalog'): ?>
<p>Le modifiche alle voci non cambiano preventivi e pratiche già registrati. Prezzi in euro; indicare il trattamento fiscale concordato.</p>
<?php foreach(['service'=>['admin_quotes','Prestazione di listino'],'payer'=>['admin_payers','Convenzione / assicurazione / fondo'],'rule'=>['admin_compensation','Regola spettanze']] as $kind=>[$flag,$label]): if(!isset($modules[$flag])) continue;
$entries=array_values(array_filter($rows,static fn($r)=>$r['kind']===$kind)); array_unshift($entries,['id'=>'','revision'=>0,'active'=>1,'data'=>[]]);
foreach($entries as $entry): $d=$entry['data']; ?><section><details <?= $entry['id']==='' ? 'open':'' ?>><summary><?= esc($entry['id']==='' ? 'Aggiungi '.$label:$d['name'].' · revisione '.$entry['revision'].(!(int)$entry['active'] ? ' · archiviata':'')) ?></summary>
<?php $start('catalog',$entry['id'],(int)$entry['revision']); ?><input type="hidden" name="kind" value="<?= $kind ?>"><div class="grid">
<?php $field('name','Nome',$d['name'] ?? ''); $field('from','Valido dal',$d['from'] ?? date('Y-m-d'),'date'); $field('until','Valido fino al',$d['until'] ?? '','date',false);
if($kind==='service') { $field('code','Codice',$d['code'] ?? ''); $field('list','Listino',$d['list'] ?? 'Privati'); $field('price','Prezzo finale EUR',isset($d['price_cents']) ? A::money($d['price_cents']):''); $field('tax_note','Trattamento fiscale',$d['tax_note'] ?? '','text',false); }
if($kind==='payer'): ?><label>Tipo<select name="type"><?php foreach(['convention'=>'Convenzione','insurance'=>'Assicurazione','fund'=>'Fondo'] as $v=>$l): ?><option value="<?= $v ?>" <?= ($d['type'] ?? '')===$v ? 'selected':'' ?>><?= $l ?></option><?php endforeach ?></select></label>
<?php $field('coverage','Copertura %',A::money($d['coverage_bps'] ?? 10000)); $field('deductible','Franchigia EUR',A::money($d['deductible_cents'] ?? 0)); $field('cap','Massimale per pratica EUR (0 = nessuno)',A::money($d['cap_cents'] ?? 0)); $field('reference','Riferimento accordo',$d['reference'] ?? '','text',false); endif;
if($kind==='rule'): ?><label>Professionista<select name="staff_id" required><?php foreach($staff as $s): ?><option value="<?= (int)$s['id_personale'] ?>" <?= ($d['staff_id'] ?? 0)==$s['id_personale'] ? 'selected':'' ?>><?= esc(trim(($s['cognome'] ?? '').' '.($s['nome'] ?? '')).' · #'.$s['id_personale']) ?></option><?php endforeach ?></select></label><label>Maturazione<select name="basis"><option value="issued" <?= ($d['basis'] ?? '')==='issued' ? 'selected':'' ?>>Fattura emessa</option><option value="paid" <?= ($d['basis'] ?? '')==='paid' ? 'selected':'' ?>>Fattura saldata</option></select></label>
<?php $field('percent','Percentuale sul totale fattura',A::money($d['percent_bps'] ?? 0)); $field('fixed','Quota fissa EUR per fattura',A::money($d['fixed_cents'] ?? 0)); endif; ?></div>
<?php $field('notes','Note',$d['notes'] ?? '','text',false); ?><label><input type="checkbox" name="active" value="1" <?= (int)$entry['active'] ? 'checked':'' ?>> Voce attiva</label><button>Salva voce</button></form></details></section><?php endforeach; endforeach ?>
<?php elseif($section==='quotes'): ?><section><h2>Nuovo preventivo</h2><form method="get"><input type="hidden" name="section" value="quotes"><?php $field('q','Cerca paziente (almeno due caratteri)',(string)service('request')->getGet('q')); ?><button>Cerca paziente</button></form>
<?php if($patients): $start('quote'); ?><input type="hidden" name="request_token" value="<?= bin2hex(random_bytes(16)) ?>"><label>Paziente<select name="patient_id" required><?php foreach($patients as $p): ?><option value="<?= (int)$p['id_client'] ?>"><?= esc($p['patient_name'].' · #'.$p['id_client']) ?></option><?php endforeach ?></select></label><div class="grid"><?php $field('date','Data',date('Y-m-d'),'date'); $field('expires','Scadenza',date('Y-m-d',strtotime('+30 days')),'date'); $field('discount','Sconto %','0'); ?></div>
<div id="quote-lines"><?php for($i=0;$i<5;$i++): ?><div class="grid"><label>Prestazione <?= $i+1 ?><select name="service_id[]"><option value="">Seleziona prestazione</option><?php foreach($catalog['service'] ?? [] as $s): ?><option value="<?= esc($s['id'],'attr') ?>"><?= esc($s['data']['list'].' · '.$s['data']['name'].' · '.$money($s['data']['price_cents'])) ?></option><?php endforeach ?></select></label><label>Quantità<input name="quantity[]" type="number" min="1" max="999" value="1"></label></div><?php endfor ?></div><button type="button" onclick="let c=document.querySelector('#quote-lines');if(c.children.length<50)c.append(c.firstElementChild.cloneNode(true));">Aggiungi riga</button>
<?php $field('notes','Note e condizioni','','text',false); ?><button>Crea preventivo</button></form><?php elseif(service('request')->getGet('q')): ?><p>Nessun paziente trovato.</p><?php endif ?></section>
<?php elseif($section==='compensation'): ?><section><h2>Calcola spettanza</h2><p>Registra il compenso di un professionista su una fattura emessa. Verifica manualmente l’attribuzione della prestazione; il pagamento viene soltanto annotato nel registro.</p><?php $start('accrue'); ?><div class="grid"><label>Regola<select name="rule_id" required><?php foreach($catalog['rule'] ?? [] as $r): ?><option value="<?= esc($r['id'],'attr') ?>"><?= esc($r['data']['name'].' · professionista #'.$r['data']['staff_id']) ?></option><?php endforeach ?></select></label><?php $field('billing_id','ID fattura','','number'); $field('reference','Riferimento prestazione / attribuzione'); ?></div><button>Calcola spettanza</button></form></section>
<?php else: ?><p>Apri un preventivo accettato per creare una pratica. Gli invii a fondi, assicurazioni e SSN si registrano con il riferimento dell’operazione eseguita nel sistema competente.</p><?php endif ?>
<?php if($section!=='catalog'): ?><section><h2>Registro</h2><a href="<?= site_url('admin/amministrazione/export/'.$section) ?>">Scarica registro CSV</a><div class="scroll"><table><thead><tr><th>Riferimento</th><th>Stato</th><th>Importo</th><th>Aggiornato (UTC)</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= esc(substr($r['id'],0,12)) ?><br><small><?= isset($r['patient_id']) ? 'Paziente #'.(int)$r['patient_id']:'Professionista #'.(int)$r['staff_id'] ?></small></td><td><?= esc($states[$r['state']] ?? $r['state']) ?></td><td><?= $money($r['total_cents'] ?? $r['amount_cents']) ?></td><td><?= esc($r['updated_at']) ?></td><td><a href="<?= site_url('admin/amministrazione/dettaglio/'.$section.'/'.$r['id']) ?>">Apri</a></td></tr><?php endforeach ?></tbody></table></div><?php if(!$rows): ?><p>Nessuna registrazione.</p><?php endif ?></section><?php endif ?>
<nav><?php if($page>1): ?><a href="<?= site_url('admin/amministrazione?section='.$section.'&page='.($page-1)) ?>">← Precedenti</a><?php endif ?><?php if($more): ?><a href="<?= site_url('admin/amministrazione?section='.$section.'&page='.($page+1)) ?>">Successivi →</a><?php endif ?></nav>
<?php endif ?></main></body></html>
