<?php
use App\Services\AdministrationService as A;
$states=['draft'=>'Bozza','offered'=>'Consegnato','accepted'=>'Accettato','rejected'=>'Respinto','cancelled'=>'Annullato','authorized'=>'Autorizzato','submitted'=>'Invio registrato','reconciled'=>'Riconciliato','approved'=>'Approvato','settled'=>'Pagamento registrato','void'=>'Stornato'];
$money=static fn($v)=>number_format((int)$v/100,2,',','.').' €';
$field=static function(string $key,string $label,$value='',string $type='text',bool $required=true) { ?><label><?= esc($label) ?><input name="<?= esc($key,'attr') ?>" type="<?= esc($type,'attr') ?>" value="<?= esc((string)$value,'attr') ?>" <?= $required ? 'required':'' ?> maxlength="2000" <?= $type==='number' ? 'min="0" step="1"':'' ?>></label><?php };
$start=static function(string $op,string $id='',int $revision=0) { ?><form method="post" action="<?= site_url('admin/amministrazione/operazione') ?>"><?= csrf_field() ?><input type="hidden" name="op" value="<?= esc($op,'attr') ?>"><input type="hidden" name="id" value="<?= esc($id,'attr') ?>"><input type="hidden" name="revision" value="<?= $revision ?>"><?php };
?><!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Amministrazione | AmbulatorioFacile</title><?= view('partials/operational_workspace_assets') ?><style>.clinical-section{margin:0;background:#f3f6fa;color:#1d3044;font:16px/1.5 system-ui,sans-serif}.clinical-section main{max-width:1180px;margin:30px auto;padding:0 24px}.clinical-section h1{margin-bottom:4px}.clinical-section h2{font-size:1.3rem}.clinical-section section,.clinical-section article{background:white;border:1px solid #dce5ed;border-radius:12px;padding:22px;margin:20px 0}.clinical-section nav{display:flex;flex-wrap:wrap;gap:18px;margin:22px 0}.clinical-section a{color:#145dab}.clinical-section label{display:block;margin:10px 0;font-weight:600}.clinical-section input,.clinical-section select,.clinical-section textarea{display:block;box-sizing:border-box;width:100%;font:inherit;border:1px solid #9eafbd;border-radius:5px;padding:9px;background:white}.clinical-section input[type=checkbox]{width:auto;display:inline}.clinical-section button,.clinical-section .button{background:#155dab;color:white;border:0;border-radius:6px;padding:10px 16px;font:inherit;cursor:pointer;display:inline-block;text-decoration:none;margin:10px 0}.clinical-section table{border-collapse:collapse;width:100%}.clinical-section td,.clinical-section th{text-align:left;border-bottom:1px solid #dce5ed;padding:10px;vertical-align:top}.clinical-section small,.clinical-section .muted{color:#526679}.clinical-section .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}.clinical-section .scroll{overflow-x:auto}.clinical-section summary{cursor:pointer;font-weight:650}.clinical-section .notice{border-left:4px solid #2d7757;padding:12px;background:#edf8f2}.clinical-section code{overflow-wrap:anywhere}.clinical-section details{margin:18px 0}.clinical-section form{margin:16px 0}.clinical-section .inline{display:inline-block;margin:0 8px 0 0}.clinical-section .inline input{display:inline-block;width:auto}
</style><?= view('partials/operational_workspace_style') ?></head><body class="billing-unified-page skin-blue sidebar-mini"><?= view('partials/operational_workspace_start',['menu_items'=>$menu_items??[]]) ?><main><a href="<?= site_url('agenda') ?>">← Torna all’agenda</a><h1>Amministrazione</h1><p class="muted"><?= esc($tenant['tenant_name'] ?? $tenant['name'] ?? 'Spazio corrente') ?></p>
<nav><a href="<?= site_url('admin/amministrazione') ?>">Listini e regole</a><?php foreach(['quotes'=>['admin_quotes','Preventivi'],'cases'=>[isset($modules['admin_payers']) ? 'admin_payers':'admin_ssn','Pratiche e incassi'],'compensation'=>['admin_compensation','Spettanze']] as $key=>[$flag,$label]): if(isset($modules[$flag])): ?><a href="<?= site_url('admin/amministrazione?section='.$key) ?>"><?= $label ?></a><?php endif; endforeach ?></nav>
<?php if($message=session()->getFlashdata('success')): ?><p class="notice" role="status"><?= esc($message) ?></p><?php endif ?>
