<?php
$base=site_url('cartella-clinica/pazienti/'.$patientId.'/pacs');
$search=$search ?? null; $details=$details ?? null;
$date=static fn(string $v): string => preg_match('/^[0-9]{8}$/D',$v) ? substr($v,6,2).'/'.substr($v,4,2).'/'.substr($v,0,4) : ($v ?: 'Non indicata');
$name=static fn(string $v): string => trim(str_replace('^',' ',$v));
$localTime=static fn(string $v): string => (new \DateTimeImmutable($v,new \DateTimeZone('UTC')))->setTimezone(new \DateTimeZone('Europe/Rome'))->format('d/m/Y H:i');
?>
<!doctype html>
<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Esami e immagini | AmbulatorioFacile</title>
<style>
:root{color-scheme:light;--ink:#193345;--muted:#576c78;--brand:#086f75;--line:#dce5e9}*{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:var(--ink);font:15px/1.55 system-ui,sans-serif}header,main{max-width:1160px;margin:auto;padding:24px}header{padding-bottom:0}h1{margin:10px 0}h2{font-size:22px}h3{font-size:17px}a{color:var(--brand)}.card{background:white;border:1px solid var(--line);border-radius:12px;padding:24px;margin:0 0 20px}.muted,small{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.row{border-top:1px solid var(--line);padding:18px 0;overflow-wrap:anywhere}.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}label{display:block;font-weight:600}input,select{width:100%;padding:10px;margin:6px 0 12px;border:1px solid #afc2ca;border-radius:6px;font:inherit}input[type=checkbox]{width:auto}button,.button{display:inline-block;padding:10px 16px;background:var(--brand);color:white;border:0;border-radius:6px;font:600 14px system-ui;text-decoration:none;cursor:pointer}.secondary{background:#e8f2f3;color:#145b61}.notice{padding:16px;border-left:4px solid var(--brand);background:#e5f4ef;margin-bottom:20px}summary{cursor:pointer;font-weight:600}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #e69f35;outline-offset:3px}.uid{font-size:12px;word-break:break-all}.full{grid-column:1/-1}@media(max-width:650px){.grid{grid-template-columns:1fr}header,main{padding:16px}.card{padding:18px}}
</style></head><body>
<header><a href="<?= site_url('cartella-clinica/pazienti/'.$patientId) ?>">← Cartella del paziente</a><h1>Esami e immagini</h1><p><?= esc($patient['patient_name'] ?? 'Paziente #'.$patientId) ?> · <?= esc($tenant['tenant_name'] ?? '') ?></p></header>
<main>
<?php if(session()->getFlashdata('success')): ?><div class="notice" role="status"><?= esc(session()->getFlashdata('success')) ?></div><?php endif ?>
<?php if(!$overview['profiles']): ?>
<section class="card"><h2>Collegamento da configurare</h2><p>Il modulo è attivo. Il responsabile della piattaforma deve completare il collegamento con il PACS della struttura.</p></section>
<?php endif ?>
<?php if($details): $study=$details['study']; $link=$details['link']; ?>
<section class="card"><a href="<?= $base ?>">← Elenco esami</a><h2><?= esc($study['description'] ?: 'Esame diagnostico') ?></h2><p><?= esc($date($study['date']).' · '.$study['modalities'].' · '.$name($study['patient_name'])) ?></p><p class="uid">Studio <?= esc($study['uid']) ?></p>
<?php if($details['viewer']): ?><form method="post" action="<?= $base.'/studi/'.$link['id'].'/visualizzatore' ?>"><?= csrf_field() ?><button>Apri nel visualizzatore PACS</button><p class="muted">La consultazione prosegue nel servizio della struttura, con i relativi permessi di accesso.</p></form><?php endif ?>
<h3>Serie disponibili</h3>
<?php foreach($details['series']['rows'] as $series): ?><div class="row"><a href="<?= $base.'/studi/'.$link['id'].'?series='.rawurlencode($series['uid']) ?>"><?= esc(($series['number'] ?: 'Serie').' · '.$series['modality'].' · '.$series['description']) ?></a></div><?php endforeach ?>
<?php if($details['series']['more']): ?><p class="notice">Sono mostrate fino a 100 serie. Per lo studio completo utilizzare il visualizzatore PACS.</p><?php endif ?>
<?php if(isset($details['instances'])): ?><h3>Oggetti della serie</h3>
<?php foreach($details['instances']['rows'] as $instance): ?><div class="row"><span>Oggetto <?= esc($instance['number'] ?: $instance['uid']) ?></span>
<?php if($details['download']): ?><form method="post" action="<?= $base.'/studi/'.$link['id'].'/scarica' ?>"><?= csrf_field() ?><input type="hidden" name="series_uid" value="<?= esc($selectedSeries,'attr') ?>"><input type="hidden" name="instance_uid" value="<?= esc($instance['uid'],'attr') ?>"><button class="secondary">Scarica oggetto DICOM</button></form><?php endif ?></div><?php endforeach ?>
<div class="actions"><?php if($details['instances']['page']>1): ?><a href="<?= $base.'/studi/'.$link['id'].'?series='.rawurlencode($selectedSeries).'&page='.($details['instances']['page']-1) ?>">Precedenti</a><?php endif ?>
<?php if($details['instances']['more']): ?><a href="<?= $base.'/studi/'.$link['id'].'?series='.rawurlencode($selectedSeries).'&page='.($details['instances']['page']+1) ?>">Successivi</a><?php endif ?></div>
<?php endif ?></section>
<?php endif ?>
<?php if($search): ?>
<section class="card"><h2>Risultati dal PACS</h2><p>Verifica identità, data e prestazione prima di collegare un esame.</p>
<?php if(!$search['studies']): ?><p>Nessun esame trovato per l’identità registrata.</p><?php endif ?>
<?php foreach($search['studies'] as $study): ?><article class="row"><h3><?= esc($study['description'] ?: 'Esame diagnostico') ?></h3><p><?= esc($name($study['patient_name']).' · Nascita '.$date($study['birth_date'])) ?><br><?= esc($date($study['date']).' · '.$study['modalities'].' · Accesso '.$study['accession']) ?></p><div class="uid"><?= esc($study['uid']) ?></div>
<?php if($overview['doctor']): ?><form method="post" action="<?= $base ?>/collega"><?= csrf_field() ?><input type="hidden" name="binding_id" value="<?= esc($search['binding']['id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$search['binding']['revision'] ?>"><input type="hidden" name="study_uid" value="<?= esc($study['uid'],'attr') ?>"><label>Documento clinico collegato (numero, facoltativo)<input type="number" name="entry_id" min="1" step="1"></label><button>Conferma e collega alla cartella</button></form><?php endif ?></article><?php endforeach ?>
<div class="actions"><?php foreach(array_filter([$search['page']>1 ? $search['page']-1 : 0,$search['more'] ? $search['page']+1 : 0]) as $page): ?><form method="post" action="<?= $base ?>/cerca"><?= csrf_field() ?><input type="hidden" name="binding_id" value="<?= esc($search['binding']['id'],'attr') ?>"><input type="hidden" name="page" value="<?= $page ?>"><button class="secondary"><?= $page<$search['page'] ? 'Precedenti' : 'Successivi' ?></button></form><?php endforeach ?></div></section>
<?php endif ?>
<section class="card"><h2>Esami collegati alla cartella</h2><p class="muted">Le immagini restano nel PACS. Sono visibili gli abbinamenti consentiti dal tuo profilo e dalla condivisione del dossier.</p>
<?php if(!$overview['links']): ?><p>Nessun esame collegato visibile.</p><?php endif ?>
<?php if(!empty($overview['recent_limit'])): ?><p class="notice">Questa pagina mostra i collegamenti recenti. Per gli esami precedenti utilizzare la ricerca nel PACS.</p><?php endif ?>
<?php foreach($overview['links'] as $link): $study=$link['study']; ?><article class="row"><h3><?= esc($study['description'] ?: 'Esame diagnostico') ?></h3><p><?= esc($date($study['date']).' · '.$study['modalities']) ?><?= $link['entry_id'] ? ' · Documento #'.(int)$link['entry_id'] : '' ?></p><small>Collegato il <?= esc($localTime($link['created_at'])) ?></small><div class="actions"><a class="button" href="<?= $base.'/studi/'.$link['id'] ?>">Consulta esame</a>
<?php if($overview['doctor'] && (int)$link['owner_user_id']===$overview['user_id']): ?><form method="post" action="<?= $base ?>/scollega"><?= csrf_field() ?><input type="hidden" name="link_id" value="<?= esc($link['id'],'attr') ?>"><button class="secondary">Rimuovi collegamento</button></form><?php endif ?></div></article><?php endforeach ?></section>
<section class="card"><h2>Identità del paziente nei PACS</h2>
<?php foreach($overview['bindings'] as $binding): ?>
<article class="row"><h3><?= esc($overview['profiles'][$binding['profile_id']]['label'] ?? $binding['profile_id']) ?></h3><p><?= esc($binding['identity']['patient_id'].' · '.$binding['identity']['issuer']) ?> · <?= $binding['active'] ? 'Attivo' : 'Disabilitato' ?></p>
<?php if($binding['active'] && isset($overview['profiles'][$binding['profile_id']])): ?><form method="post" action="<?= $base ?>/cerca"><?= csrf_field() ?><input type="hidden" name="binding_id" value="<?= esc($binding['id'],'attr') ?>"><button>Cerca esami nel PACS</button></form><?php endif ?>
<?php if($overview['doctor'] && (int)$binding['owner_user_id']===$overview['user_id']): ?>
<details><summary>Correggi o disabilita il collegamento</summary><p>Una modifica dell’identità rende inutilizzabili i precedenti collegamenti agli studi. Sarà necessario verificarli e associarli di nuovo.</p>
<form method="post" action="<?= $base ?>/identita"><?= csrf_field() ?><input type="hidden" name="profile_id" value="<?= esc($binding['profile_id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$binding['revision'] ?>">
<div class="grid"><label>Identificativo nel PACS<input name="patient_id" maxlength="64" required value="<?= esc($binding['identity']['patient_id'],'attr') ?>"></label><label>Autorità dell’identificativo<input name="issuer" maxlength="64" required value="<?= esc($binding['identity']['issuer'],'attr') ?>"></label></div><label><input type="checkbox" name="confirmed" value="1" required> Ho verificato la corrispondenza del paziente nel PACS.</label><button>Salva nuova verifica</button></form>
<?php if($binding['active']): ?><form method="post" action="<?= $base ?>/disabilita"><?= csrf_field() ?><input type="hidden" name="binding_id" value="<?= esc($binding['id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$binding['revision'] ?>"><button class="secondary">Disabilita collegamento</button></form><?php endif ?></details><?php endif ?></article><?php endforeach ?>
<?php if($overview['doctor'] && $overview['profiles']): ?><details><summary>Aggiungi un collegamento PACS</summary><p>Inserisci i dati verificati nel PACS della struttura. Non usare il nome del paziente come identificativo.</p><form method="post" action="<?= $base ?>/identita"><?= csrf_field() ?><input type="hidden" name="revision" value="0"><label>PACS<select name="profile_id"><?php foreach($overview['profiles'] as $profile): ?><option value="<?= esc($profile['id'],'attr') ?>"><?= esc($profile['label']) ?></option><?php endforeach ?></select></label><div class="grid"><label>Identificativo paziente nel PACS<input name="patient_id" maxlength="64" required></label><label>Autorità dell’identificativo<input name="issuer" maxlength="64" required></label></div><label><input type="checkbox" name="confirmed" value="1" required> Ho verificato la corrispondenza del paziente nel PACS.</label><button>Registra identità</button></form></details><?php endif ?>
</section></main></body></html>
