<?php
$labels=['draft'=>'Bozza','ready'=>'Confermata','accepted'=>'Accettata','in_progress'=>'In esecuzione','performed'=>'Eseguita','cancelled'=>'Annullata'];
$base=site_url('cartella-clinica/demo-pacs/richieste');
$now=(new DateTimeImmutable('now',new DateTimeZone('Europe/Rome')))->format('Y-m-d\TH:i');
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Richieste PACS di prova | AmbulatorioFacile</title>
<?= view('partials/operational_workspace_assets') ?>
<style>.trial{max-width:1150px;margin:auto;padding:24px;color:#193345}.trial h1{font-size:28px}.trial h2{font-size:22px}.trial-card{background:#fff;border:1px solid #dce5e9;border-radius:12px;padding:22px;margin:18px 0}.trial-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.trial label{display:block;font-weight:600}.trial input,.trial select,.trial textarea{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid #bfcfd6;border-radius:6px;font:inherit}.trial textarea{min-height:130px}.trial button,.trial .action{display:inline-block;border:0;border-radius:7px;padding:11px 16px;background:#086f75;color:#fff;cursor:pointer;margin:5px 5px 5px 0}.trial a{color:#086f75}.trial .action{color:#fff}.trial-notice{background:#fff4db;padding:12px;border-radius:8px}.trial-success{background:#dff3e8;padding:12px}.trial-error{background:#fbe4e4;padding:12px}.trial table{width:100%;border-collapse:collapse}.trial th,.trial td{padding:10px;text-align:left;border-bottom:1px solid #e1e8ec}.trial .table-wrap{overflow:auto}.trial .badge{display:inline-block;background:#e4f3ef;padding:5px 12px;border-radius:20px}.trial small{font-weight:400}.trial code{word-break:break-all}.trial .inline{display:inline-block}.trial dl{display:grid;grid-template-columns:minmax(140px,1fr) 3fr;gap:10px}.trial dd{margin:0}.trial .muted{color:#566873}@media(max-width:700px){.trial-grid{grid-template-columns:1fr}.trial dl{display:block}.trial dd{margin-bottom:12px}}
</style><?= view('partials/operational_workspace_style') ?></head><body class="billing-unified-page skin-blue sidebar-mini"><?= view('partials/operational_workspace_start',['menu_items'=>$menu_items??[]]) ?><main class="trial">
<h1>Richieste PACS di prova</h1><p>Ambiente di test · Operatore TEST TEST</p>
<p class="trial-notice"><strong>Prova operativa su dati sintetici.</strong> Puoi salvare e confermare richieste, registrare avanzamenti e scaricare la worklist. Le prove restano in un archivio dedicato e non vengono inviate alle apparecchiature. Non inserire dati di pazienti reali.</p>
<?php if($message=session()->getFlashdata('success')): ?><p class="trial-success" role="status"><?= esc($message) ?></p><?php endif ?>
<?php if($message=session()->getFlashdata('error')): ?><p class="trial-error" role="alert"><?= esc($message) ?></p><?php endif ?>
<?php if($selected): $s=$selected;$p=$s['payload']; ?>
<section class="trial-card"><a href="<?= esc($base) ?>">← Nuova richiesta e archivio</a><h2><?= esc($p['description']) ?></h2><p class="badge"><?= esc($labels[$s['state']]) ?></p>
<dl><dt>Paziente</dt><dd><?= esc(str_replace('^',' ',$p['patient_name']).' · '.$p['birth_date']) ?></dd><dt>Identificativo PACS</dt><dd><?= esc($s['identity']['patient_id'].' / '.$s['identity']['issuer']) ?></dd><dt>Apparecchiatura</dt><dd><?= esc($stations[$p['station_ae']]['label']) ?> · <?= esc($p['station_ae']) ?></dd><dt>Modalità</dt><dd><?= esc($p['modality']) ?></dd><dt>Data e ora</dt><dd><?= esc(str_replace('T',' ',$p['scheduled_at'])) ?> · Italia</dd><dt>Numero esame</dt><dd><code><?= esc($s['accession']) ?></code></dd><dt>Identificativo studio</dt><dd><code><?= esc($s['study_uid']) ?></code></dd><dt>Note di prova</dt><dd><?= esc($p['reason']?:'—') ?></dd></dl>
<?php $next=['draft'=>['confirm','Conferma richiesta'],'ready'=>['accept','Registra accettazione'],'accepted'=>['start','Avvia esecuzione'],'in_progress'=>['complete','Concludi esame']]; if(isset($next[$s['state']])): ?>
<form method="post" action="<?= esc($base) ?>" class="inline"><?= csrf_field() ?><input type="hidden" name="order" value="<?= esc($s['id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$s['revision'] ?>"><input type="hidden" name="action" value="<?= $next[$s['state']][0] ?>"><button><?= esc($next[$s['state']][1]) ?></button></form>
<?php endif ?>
<?php if(in_array($s['state'],['draft','ready','accepted'],true)): ?><form method="post" action="<?= esc($base) ?>" class="inline"><?= csrf_field() ?><input type="hidden" name="order" value="<?= esc($s['id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$s['revision'] ?>"><button name="action" value="cancel" style="background:#79554a">Annulla richiesta di prova</button></form><?php endif ?>
<?php if(in_array($s['state'],['ready','accepted'],true)): ?><h3>Worklist per l’apparecchiatura</h3><p>Il file contiene il paziente sintetico, l’esame scelto e la destinazione. Il download non equivale all’invio o alla ricezione da parte della macchina.</p><form method="post" action="<?= site_url('cartella-clinica/demo-pacs/worklist') ?>"><?= csrf_field() ?><input type="hidden" name="order" value="<?= esc($s['id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$s['revision'] ?>"><button name="format" value="wl">Scarica worklist DICOM (.wl)</button><button name="format" value="json">Scarica DICOM JSON</button></form><p><a href="<?= esc($base.'?order='.$s['id']) ?>">Dopo il download, aggiorna la richiesta per continuare</a></p><?php endif ?>
<p><a href="<?= site_url('cartella-clinica/demo-pacs') ?>">Apri immagini campione</a> <span class="muted">· Serie dimostrativa indipendente: non è il risultato di questa nuova richiesta.</span></p>
<?php if($s['state']==='performed'): ?><h3>Referto di prova</h3><form method="post" action="<?= esc($base) ?>"><?= csrf_field() ?><input type="hidden" name="order" value="<?= esc($s['id'],'attr') ?>"><input type="hidden" name="revision" value="<?= (int)$s['revision'] ?>"><input type="hidden" name="action" value="report"><label>Testo dimostrativo<textarea name="report" required maxlength="5000"><?= esc($s['report']?:'REFERTO DIMOSTRATIVO — SENZA VALORE CLINICO. Prova del percorso richiesta, esecuzione e documentazione. Nessuna valutazione diagnostica.') ?></textarea></label><button>Salva referto di prova</button></form><p>Documento di esercitazione: non è firmato, non è inviato al FSE e non viene inserito in una cartella clinica.</p><?php endif ?>
<h3>Storico della prova</h3><ul><?php foreach($s['history'] as $event): ?><li><?= esc((new DateTimeImmutable($event['at']))->setTimezone(new DateTimeZone('Europe/Rome'))->format('d/m/Y H:i:s').' — '.$event['action']) ?></li><?php endforeach ?></ul></section>
<?php else: ?>
<section class="trial-card"><h2>Nuova richiesta</h2><p>Scegli il paziente sintetico, poi la prestazione e l’apparecchiatura.</p>
<form method="post" action="<?= esc($base) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="request_key" value="<?= esc($requestKey,'attr') ?>"><div class="trial-grid">
<label>Paziente di prova<select name="patient" required><option value="">Seleziona il paziente</option><?php foreach(\App\Services\Pacs\PacsTrialService::patients() as $key=>$patient): ?><option value="<?= esc($key,'attr') ?>"><?= esc($patient['patient_last_name'].' '.$patient['patient_first_name'].' · '.$patient['patient_birth_date'].' · '.$patient['pacs_id']) ?></option><?php endforeach ?></select></label>
<label>Esame da richiedere<select id="trialExam" name="exam" required><?php foreach($catalog as $key=>$exam): ?><option value="<?= esc($key,'attr') ?>" data-modality="<?= esc($exam['modality'],'attr') ?>"><?= esc($exam['label']) ?></option><?php endforeach ?></select></label>
<label>Apparecchiatura di destinazione<select id="trialStation" name="station" required><?php foreach($stations as $ae=>$station): ?><option value="<?= esc($ae,'attr') ?>" data-modality="<?= esc($station['modality'],'attr') ?>"><?= esc($station['label']) ?></option><?php endforeach ?></select><small>Apparecchiature dimostrative, non collegate a dispositivi reali.</small></label>
<label>Data e ora previste<input type="datetime-local" name="scheduled_at" required value="<?= esc($now,'attr') ?>"></label><label>Note di prova<input name="reason" maxlength="1000" placeholder="Facoltative; solo dati inventati"></label></div><p id="examSummary" class="muted"></p><button>Salva richiesta in bozza</button></form></section>
<?php endif ?>
<section class="trial-card"><h2>Archivio richieste di prova</h2><?php if(!$orders): ?><p>Nessuna richiesta salvata. Compila il modulo per iniziare.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Paziente</th><th>Esame</th><th>Data e ora</th><th>Apparecchiatura</th><th>Stato</th><th></th></tr></thead><tbody><?php foreach($orders as $order): ?><tr><td><?= esc(str_replace('^',' ',$order['payload']['patient_name'])) ?></td><td><?= esc($order['payload']['description']) ?><br><small><?= esc($order['accession']) ?></small></td><td><?= esc(str_replace('T',' ',$order['payload']['scheduled_at'])) ?></td><td><?= esc($stations[$order['payload']['station_ae']]['label']) ?></td><td><?= esc($labels[$order['state']]) ?></td><td><a href="<?= esc($base.'?order='.$order['id']) ?>">Apri richiesta</a></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
</main><?= view('partials/operational_workspace_end') ?>
<script>(()=>{const exam=document.getElementById('trialExam'),station=document.getElementById('trialStation');if(!exam)return;function sync(){const modality=exam.selectedOptions[0].dataset.modality;for(const option of station.options){option.disabled=option.dataset.modality!==modality;option.hidden=option.disabled;}if(station.selectedOptions[0].disabled)station.value=Array.from(station.options).find(o=>!o.disabled).value;document.getElementById('examSummary').textContent='Modalità '+modality+' · catalogo AF-DEMO · destinazione '+station.value;}exam.addEventListener('change',sync);station.addEventListener('change',sync);sync();})();</script></body></html>
