<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Nuova richiesta PACS | AmbulatorioFacile</title>
<?= view('partials/operational_workspace_assets') ?>
<style>.patient-choice{padding:24px;max-width:1050px;margin:auto}.patient-choice section{background:white;border:1px solid #dce5e9;border-radius:10px;padding:22px;margin:18px 0}.patient-choice input{padding:10px;width:min(100%,480px)}.patient-choice button,.patient-choice .button{display:inline-block;padding:11px 16px;background:#086f75;color:white;border:0;border-radius:6px;margin:8px 0}.patient-choice label{display:block}.patient-choice table{width:100%}.patient-choice th,.patient-choice td{padding:12px;text-align:left;border-bottom:1px solid #dce5e9}.patient-choice .table-wrap{overflow:auto}</style>
<?= view('partials/operational_workspace_style') ?></head><body class="billing-unified-page skin-blue sidebar-mini"><?= view('partials/operational_workspace_start',['menu_items'=>$menu_items??[]]) ?><main class="patient-choice">
<h1>Nuova richiesta PACS</h1><p>1. Scegli il paziente → 2. Verifica il collegamento PACS → 3. Compila e conferma l’esame</p>
<?php if($selection['doctor']): ?>
<section><h2>Scegli il paziente dall’anagrafica</h2><p>La ricerca mostra i pazienti dello spazio ai quali il tuo profilo medico può accedere.</p>
<form method="post" action="<?= site_url('cartella-clinica/diagnostica/nuova-richiesta') ?>"><?= csrf_field() ?><label for="patientSearch">Nome, cognome o codice fiscale</label><input id="patientSearch" name="patient_search" value="<?= esc($term,'attr') ?>" minlength="2" maxlength="100" required autocomplete="off"><button>Cerca paziente</button></form>
<?php if($term!==''): ?><?php if(!$selection['patients']): ?><p role="status">Nessun paziente accessibile trovato. Verifica i dati o usa un termine più specifico.</p><?php else: ?><p>Verifica nome e data di nascita prima di proseguire. Sono mostrati al massimo 20 risultati; affina la ricerca se necessario.</p><div class="table-wrap"><table><thead><tr><th>Paziente</th><th>Data di nascita</th><th>Codice fiscale</th><th></th></tr></thead><tbody>
<?php foreach($selection['patients'] as $patient): ?><tr><td><?= esc($patient['patient_name']) ?></td><td><?= esc($patient['patient_birth_date']?:'Non indicata') ?></td><td><?= esc($patient['patient_tax_code']) ?></td><td><a class="button" href="<?= site_url('cartella-clinica/pazienti/'.(int)$patient['id_client'].'/pacs/richieste').'#nuova-richiesta' ?>">Seleziona paziente</a></td></tr><?php endforeach ?></tbody></table></div><?php endif ?><?php endif ?></section>
<?php else: ?><section><h2>Richiesta clinica</h2><p>La creazione e conferma delle richieste cliniche sono riservate al medico. Con il profilo amministrativo puoi seguire le richieste confermate nella lista diagnostica.</p></section><?php endif ?>
<?php if((int)$tenant['id_tenant']===4 && function_exists('session_has_tenant_master_access') && session_has_tenant_master_access()): ?><section><h2>Presentazione con TEST TEST</h2><p>Nel modulo di prova puoi scegliere un paziente sintetico e mostrare tutto il percorso con questo account.</p><a class="button" href="<?= site_url('cartella-clinica/demo-pacs/richieste') ?>">Scegli paziente e crea richiesta di prova</a></section><?php endif ?>
<p><a href="<?= site_url('cartella-clinica/diagnostica') ?>">Torna alla lista diagnostica</a></p></main><?= view('partials/operational_workspace_end') ?></body></html>
