<?php
$o=$case['order'];$m=$case['images'];$report=$case['report'];$imageBase=site_url('cartella-clinica/demo-pacs/cartella/immagini');
$events=['pacs_order_created'=>'Richiesta creata','pacs_order_approved'=>'Richiesta confermata','pacs_order_exported'=>'Worklist esportata','pacs_stage_accepted'=>'Paziente accettato','pacs_stage_in_progress'=>'Esame avviato','pacs_stage_performed'=>'Esame eseguito','pacs_order_images_linked'=>'Immagini associate','pacs_report_saved'=>'Referto salvato nella cartella'];
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Cartella di prova completa | AmbulatorioFacile</title>
<?= view('partials/operational_workspace_assets') ?>
<style>.case-chart{max-width:1100px;margin:auto;padding:24px;color:#193345}.case-chart section{background:#fff;border:1px solid #dce5e9;border-radius:10px;padding:22px;margin:20px 0}.case-chart .notice{background:#fff2cf;padding:15px;border-radius:8px}.case-chart .grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.case-chart dt{font-weight:600}.case-chart dd{margin-bottom:12px;overflow-wrap:anywhere}.case-chart a{color:#086f75}.case-chart nav{display:flex;gap:18px;flex-wrap:wrap}.case-chart .status{padding:6px 12px;background:#e4f3ed;border-radius:14px;display:inline-block}.case-chart img{display:block;width:100%;max-width:512px;background:#111}.case-chart input[type=range]{width:100%}.case-chart pre{white-space:pre-wrap;font:inherit;background:#f5f8fa;padding:18px}.case-chart code{overflow-wrap:anywhere}@media(max-width:750px){.case-chart .grid{grid-template-columns:1fr}}</style>
<?= view('partials/operational_workspace_style') ?></head><body class="billing-unified-page skin-blue sidebar-mini"><?= view('partials/operational_workspace_start',['menu_items'=>$menu_items??[]]) ?><main class="case-chart">
<h1>Cartella di prova completa</h1><h2><?= esc($case['patient']['patient_name']) ?></h2><p>Nascita fittizia: 01/01/1980 · Identificativo PACS: <?= esc($m['patient']) ?></p>
<p class="notice"><strong>Caso sintetico verificato · sola consultazione.</strong> Risultato di un collaudo eseguito con i servizi applicativi di richieste e cartella clinica, su un database di laboratorio separato e un PACS di test. Non è una cartella di un paziente reale e non contiene le nuove richieste del modulo di prova.</p>
<nav aria-label="Sezioni del caso"><a href="#richiesta">Richiesta ed esecuzione</a><a href="#immagini">Immagini dell’esame</a><a href="#referto">Referto in cartella</a><a href="#storico">Storico</a></nav>
<section id="richiesta"><h2>Richiesta ed esecuzione</h2><p class="status">Richiesta confermata · Esame eseguito</p><dl class="grid"><div><dt>Esame</dt><dd><?= esc($o['payload']['description']) ?></dd><dt>Data e ora previste</dt><dd><?= esc($o['payload']['scheduled_at']) ?> · Italia</dd><dt>Apparecchiatura simulata</dt><dd><?= esc($o['payload']['station_ae']) ?></dd></div><div><dt>Numero richiesta</dt><dd><?= esc($o['accession']) ?></dd><dt>Identificativo studio PACS</dt><dd><code><?= esc($o['study_uid']) ?></code></dd><dt>Trasmissione alla macchina</dt><dd>Simulata nel laboratorio; worklist esportata, nessun dispositivo clinico coinvolto.</dd></div></dl></section>
<section id="immagini"><h2>Immagini associate a questo esame</h2><p role="status"><?= $connected ? 'PACS raggiungibile: paziente, studio e numero richiesta verificati adesso.' : 'PACS non verificabile in questo momento: ricarica per riprovare. Il collaudo storico resta consultabile.' ?></p><div class="grid"><div><img id="caseImage" src="<?= esc($imageBase.'/1','attr') ?>" alt="Phantom sintetico dell’esame, immagine 1" width="512" height="512"><p id="imageStatus" role="status">Caricamento immagine dal PACS…</p></div><div><p>16 immagini geometriche generate al computer. Nessun valore diagnostico.</p><label for="caseSlice">Immagine <span id="sliceNumber">1</span> di 16</label><input id="caseSlice" type="range" min="1" max="16" value="1"><p><a id="caseDownload" href="<?= esc($imageBase.'/1?download=1','attr') ?>">Scarica questa immagine DICOM</a></p><p>La visualizzazione verifica paziente, studio, numero richiesta e integrità del file.</p></div></div></section>
<section id="referto"><h2>Referto nella cartella</h2><p class="status">Bozza di prova · non firmata</p><h3><?= esc($report['content']['title']) ?></h3><pre><?= esc($report['content']['body']) ?></pre><p>Documento #<?= (int)$report['id'] ?>, collegato alla richiesta <?= esc($o['accession']) ?>. Salvato e riletto attraverso il servizio della cartella clinica nel laboratorio.</p></section>
<section id="storico"><h2>Storico del percorso verificato</h2><ol><?php foreach(array_reverse($case['history']) as $event): ?><?php if(isset($events[$event['event']])): ?><li><?= esc($events[$event['event']]) ?></li><?php endif ?><?php endforeach ?></ol><details><summary>Verifiche del collaudo</summary><p>Eseguito il <?= esc((new DateTimeImmutable($case['verified_at']))->setTimezone(new DateTimeZone('Europe/Rome'))->format('d/m/Y H:i')) ?> (Italia).</p><ul><?php foreach($case['checks'] as $check): ?><li><?= esc($check) ?></li><?php endforeach ?></ul></details></section>
<p><a href="<?= site_url('cartella-clinica/demo-pacs/richieste') ?>">Crea una nuova richiesta di prova</a> · <a href="<?= site_url('cartella-clinica/demo-pacs') ?>">Torna alla presentazione PACS</a></p>
</main><?= view('partials/operational_workspace_end') ?><script>(()=>{const image=document.getElementById('caseImage'),slice=document.getElementById('caseSlice'),status=document.getElementById('imageStatus'),base=<?= json_encode($imageBase,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;function loaded(){status.textContent=image.naturalWidth?'Immagine verificata e caricata.':'Immagine non disponibile: riprova quando il PACS è raggiungibile.';}image.addEventListener('load',loaded);image.addEventListener('error',loaded);if(image.complete)loaded();slice.addEventListener('change',()=>{document.getElementById('sliceNumber').textContent=slice.value;image.alt='Phantom sintetico dell’esame, immagine '+slice.value;status.textContent='Caricamento immagine dal PACS…';image.src=base+'/'+slice.value;document.getElementById('caseDownload').href=base+'/'+slice.value+'?download=1';});})();</script></body></html>
