<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Archivio immagini PACS | AmbulatorioFacile</title>
<?= view('partials/operational_workspace_assets') ?>
<style>.pacs-demo{max-width:1200px;margin:auto;padding:24px;color:#193345}.pacs-demo h1{font-size:28px}.demo-card{background:#fff;border:1px solid #dce5e9;border-radius:12px;padding:20px;margin:16px 0}.demo-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.demo-screen{background:#080b10;overflow:hidden;min-height:400px;text-align:center;border-radius:8px}.demo-screen img{width:min(100%,512px);height:auto;transform-origin:center}.demo-tools{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:16px 0}.demo-tools button,.demo-action{background:#086f75;color:white;border:0;border-radius:7px;padding:10px 15px;cursor:pointer}.demo-steps{display:flex;gap:8px;flex-wrap:wrap}.demo-steps button{padding:12px;border:1px solid #c7d7dd;border-radius:7px;background:white;color:#193345;cursor:pointer}.demo-steps button[aria-current=true]{background:#086f75;color:white}.demo-badge{display:inline-block;background:#e4f3ef;padding:5px 12px;border-radius:20px}.demo-notice{background:#fff4db;padding:12px;border-radius:8px}.pacs-demo textarea{width:100%;min-height:140px;padding:12px}.demo-stage{min-height:150px}.demo-stage h2{font-size:22px}.pacs-demo a{color:#086f75}input[type=range]{max-width:250px}@media(max-width:800px){.demo-grid{grid-template-columns:1fr}}
</style><?= view('partials/operational_workspace_style') ?></head><body class="billing-unified-page skin-blue sidebar-mini"><?= view('partials/operational_workspace_start',['menu_items'=>$menu_items??[]]) ?><main class="pacs-demo"><p><a href="<?= site_url('cartella-clinica/demo-pacs/cartella') ?>">Apri cartella: richiesta, immagini e referto</a></p>
<a href="<?= site_url('cartella-clinica/diagnostica') ?>">← Lista diagnostica</a>
<h1>Archivio immagini PACS</h1><p><a class="btn btn-primary" href="<?= site_url('cartella-clinica/demo-pacs/richieste') ?>">Nuova richiesta</a></p><p>Ambiente di test</p>
<p class="demo-notice"><strong>Dati dimostrativi.</strong> Immagini generate al computer, senza valore diagnostico. Il percorso qui sotto è una simulazione locale: non registra richieste, esecuzioni o referti clinici.</p>
<div class="demo-grid"><section class="demo-card"><h2>Serie DICOM · 16 immagini</h2><p class="demo-badge"><?= $connected ? 'Studio verificato sul PACS di test' : 'PACS non raggiungibile: riprovare tra poco' ?></p>
<div class="demo-screen"><img id="demoImage" src="<?= site_url('cartella-clinica/demo-pacs/immagini/1') ?>" alt="Immagine 1 della serie DICOM sintetica"></div><p id="imageStatus" role="status">Caricamento immagine dal PACS…</p>
<div class="demo-tools"><button id="previousImage" type="button">← Precedente</button><label>Immagine <span id="imageNumber">1</span>/16 <input id="slice" type="range" min="1" max="16" value="1"></label><button id="nextImage" type="button">Successiva →</button></div>
<div class="demo-tools"><label>Zoom <input id="zoom" type="range" min="100" max="250" value="100"></label><label>Contrasto <input id="contrast" type="range" min="50" max="200" value="100"></label><button id="resetImage" type="button">Ripristina vista</button></div>
<a id="downloadDicom" href="<?= site_url('cartella-clinica/demo-pacs/immagini/1?download=1') ?>">Scarica l’immagine DICOM originale</a><p><small>Ogni immagine viene recuperata dal PACS e confrontata con il file sintetico originale prima di mostrare la sua anteprima.</small></p></section>
<aside><section class="demo-card"><h2>Dati dello studio</h2><p><strong>Phantom DICOM</strong><br>Nascita fittizia: 01/01/1980</p><p>Esame: phantom sintetico<br>Serie: 16 immagini · 512 × 512 pixel<br>Identificativo: <?= esc($manifest['patient']) ?></p><p>Il gestionale collega paziente, richiesta, immagini e referto. Le immagini originali restano nel PACS.</p></section><section class="demo-card"><h2>Collegamenti operativi</h2><p><a href="<?= site_url('cartella-clinica/diagnostica') ?>">Lista diagnostica dello spazio</a></p><p><a href="<?= site_url('cartella-clinica/diagnostica/collegamenti') ?>">Verifica collegamenti PACS</a></p><p><a href="<?= site_url('cartella-clinica/configurazione') ?>">Configurazione PACS</a></p></section></aside></div>
<section class="demo-card"><h2>Percorso esame</h2><div class="demo-steps" id="steps"><button type="button" data-step="0">1. Richiesta</button><button type="button" data-step="1">2. Accettazione</button><button type="button" data-step="2">3. Esecuzione</button><button type="button" data-step="3">4. Immagini</button><button type="button" data-step="4">5. Referto</button></div><div class="demo-stage" id="stage" aria-live="polite"></div><div id="reportEditor" hidden><label for="demoReport">Testo dimostrativo del referto</label><textarea id="demoReport">REFERTO DIMOSTRATIVO — SENZA VALORE CLINICO
Esame sintetico utilizzato per illustrare il collegamento tra richiesta, immagini PACS e documento. Nessuna valutazione diagnostica effettuata.</textarea><button class="demo-action" id="downloadReport" type="button">Scarica bozza dimostrativa (.txt)</button></div><div class="demo-tools"><button id="nextStep" type="button">Passaggio successivo →</button><button id="restartDemo" type="button">Ricomincia</button></div><p><small>I passaggi operativi reali restano nella Lista diagnostica; la firma digitale e gli invii esterni non vengono simulati come completati.</small></p></section>
</main><?= view('partials/operational_workspace_end') ?>
<script>
(()=>{'use strict';const base=<?= json_encode(site_url('cartella-clinica/demo-pacs/immagini').'/',JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;const img=document.getElementById('demoImage'),slice=document.getElementById('slice'),status=document.getElementById('imageStatus');let image=1,step=0;
function showImage(n){image=Math.max(1,Math.min(16,n));slice.value=image;document.getElementById('imageNumber').textContent=image;img.alt='Immagine '+image+' della serie DICOM sintetica';status.textContent='Caricamento immagine dal PACS…';img.src=base+image;document.getElementById('downloadDicom').href=base+image+'?download=1';}
img.onload=()=>status.textContent='Immagine '+image+'/16 verificata e pronta';img.onerror=()=>status.textContent='Immagine non disponibile: controllare il collegamento PACS e riprovare.';if(img.complete&&img.naturalWidth)status.textContent='Immagine 1/16 verificata e pronta';slice.onchange=()=>showImage(Number(slice.value));document.getElementById('previousImage').onclick=()=>showImage(image-1);document.getElementById('nextImage').onclick=()=>showImage(image+1);const zoom=document.getElementById('zoom'),contrast=document.getElementById('contrast');zoom.oninput=()=>img.style.transform='scale('+Number(zoom.value)/100+')';contrast.oninput=()=>img.style.filter='contrast('+contrast.value+'%)';document.getElementById('resetImage').onclick=()=>{zoom.value=contrast.value=100;img.style.transform='';img.style.filter='';};
const stages=[['Richiesta esame','Il medico seleziona il paziente e la prestazione, controlla i dati e conferma la richiesta. Si generano gli identificativi che permettono di collegare l’esame alle immagini.'],['Accettazione','La segreteria o il master registrano l’arrivo del paziente nella lista diagnostica.'],['Esecuzione','Il professionista registra l’inizio e la conclusione dell’esame. Le apparecchiature archiviano le immagini nel PACS secondo il collegamento concordato.'],['Consultazione immagini','Il gestionale verifica gli identificativi dell’esame e apre le immagini. Prova a scorrere la serie, cambiare zoom e scaricare un DICOM originale.'],['Referto','Il medico redige il referto collegato all’esame. Nella cartella operativa il documento può essere finalizzato in PDF e seguire il percorso di firma configurato. Qui puoi modificare una bozza dimostrativa.']];function render(){const box=document.getElementById('stage');box.replaceChildren();const h=document.createElement('h2'),p=document.createElement('p');h.textContent=stages[step][0];p.textContent=stages[step][1];box.append(h,p);document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.step)===step)));document.getElementById('reportEditor').hidden=step!==4;document.getElementById('nextStep').disabled=step===4;}document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);render();});document.getElementById('nextStep').onclick=()=>{step=Math.min(4,step+1);render();};document.getElementById('restartDemo').onclick=()=>{step=0;render();showImage(1);};document.getElementById('downloadReport').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['DEMO - SENZA VALORE CLINICO\n\n'+document.getElementById('demoReport').value],{type:'text/plain;charset=utf-8'}));a.download='bozza-referto-dimostrativo.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};render();})();
</script></body></html>
