<?php
use App\Services\ClinicalRecordService;
$base=site_url('cartella-clinica/pazienti/'.$patientId);
$source=$editing ?? $revisionOf;
$content=$source['content'] ?? [];
$states=['draft'=>'Bozza','final'=>'Definitivo · da firmare','signed'=>'Firma verificata'];
$now=(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Rome')))->format('Y-m-d H:i:s');
$decisions=['granted'=>'Concesso','denied'=>'Negato','revoked'=>'Revocato','acknowledged'=>'Presa visione'];
$latest=[]; foreach($chart['consents'] as $consent) $latest[$consent['kind']] ??= $consent;
$download=static fn($id)=>$base.'/allegati/'.rawurlencode($id);
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cartella del paziente | AmbulatorioFacile</title>
<style>
:root{color-scheme:light;--ink:#193345;--muted:#576c78;--line:#dce5e9;--brand:#086f75}*{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:var(--ink);font:15px/1.55 system-ui,sans-serif}header{background:#fff;border-bottom:1px solid var(--line);padding:25px max(24px,calc((100% - 1160px)/2))}main{max-width:1208px;margin:auto;padding:24px}h1{font-size:28px;margin:8px 0}h2{font-size:22px;margin:0 0 16px}h3{font-size:17px}a{color:var(--brand)}nav{display:flex;gap:24px;flex-wrap:wrap;margin-top:22px}.muted,small{color:var(--muted)}.card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:24px;margin-bottom:20px;scroll-margin-top:20px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.full{grid-column:1/-1}label{display:block;font-weight:600}input,select,textarea{width:100%;border:1px solid #afc2ca;border-radius:6px;padding:10px;font:inherit;color:var(--ink);background:#fff;margin:6px 0 12px}textarea{min-height:110px;resize:vertical}button,.button{display:inline-block;border:0;border-radius:6px;background:var(--brand);color:white;padding:10px 16px;font:600 14px system-ui;text-decoration:none;cursor:pointer}button:hover,.button:hover{background:#05565b}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #e69f35;outline-offset:3px}.secondary{background:#e8f2f3;color:#145b61}.tag{display:inline-block;background:#edf2f6;padding:4px 10px;border-radius:14px;font-size:12px}.notice{background:#e5f4ef;border-left:4px solid #218665;padding:14px;margin:16px 0}.entry{border-top:1px solid var(--line);padding:20px 0}.entry:first-of-type{border-top:0}.entry p,.text{white-space:pre-wrap;overflow-wrap:anywhere}.actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.actions form{margin:0}summary{cursor:pointer;font-weight:600;padding:12px 0}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid var(--line);padding:10px;vertical-align:top}.table-wrap{overflow:auto}details form{margin:12px 0}.help{font-size:13px;color:var(--muted)}@media(max-width:700px){.grid{grid-template-columns:1fr}.card{padding:18px}main{padding:15px}h1{font-size:24px}}
</style></head><body>
<header><a href="<?= site_url('agenda/gestione-pazienti') ?>">← Pazienti</a><div class="muted"><?= esc($tenant['tenant_name'] ?? 'AmbulatorioFacile') ?></div>
<h1><?= esc($patient['patient_name'] ?? 'Cartella del paziente') ?></h1><div><?= esc($patient['patient_tax_code'] ?? '') ?> · Paziente #<?= (int)$patientId ?></div>
<nav aria-label="Sezioni della cartella"><?php if($chart['clinical']): ?><a href="#documenti">Documenti clinici</a><a href="#nuovo">Nuovo episodio</a><a href="#prestazioni">Prestazioni e referti</a><?php if(!empty($pacsEnabled)): ?><a href="<?= $base.'/pacs' ?>">Esami e immagini</a><?php endif ?><?php endif ?><a href="#allegati">Allegati</a><a href="#consensi">Consensi</a></nav></header>
<main>
<?php if(session()->getFlashdata('success')): ?><div class="notice" role="status"><?= esc(session()->getFlashdata('success')) ?></div><?php endif ?>
<?php if($chart['clinical']): ?>
<section class="card" id="documenti"><h2>Documenti clinici <span class="tag"><?= (int)$chart['total'] ?></span></h2>
<p class="help"><?= $chart['shared'] ? 'Condivisione del dossier attiva: sono visibili anche i documenti definitivi degli altri professionisti autorizzati.' : 'Condivisione del dossier non attiva: sono visibili i documenti di cui sei autore.' ?></p>
<?php if(!$chart['entries']): ?><p class="muted">Nessun documento clinico presente in questa vista.</p><?php endif ?>
<?php foreach($chart['entries'] as $entry): $own=(int)$entry['author_user_id']===$chart['actor']['user_id']; ?>
<article class="entry"><span class="tag"><?= esc($states[$entry['state']] ?? $entry['state']) ?></span> <small><?= esc($entry['occurred_at']) ?> · #<?= (int)$entry['id'] ?> · revisione <?= (int)$entry['revision'] ?></small>
<h3><?= esc($entry['content']['title']) ?></h3><div class="help"><?= esc(ClinicalRecordService::KINDS[$entry['kind']] ?? $entry['kind']) ?> · Autore #<?= (int)$entry['author_user_id'] ?><?php if($entry['previous_entry_id']): ?> · Correzione del documento #<?= (int)$entry['previous_entry_id'] ?><?php endif ?></div>
<p><?= esc($entry['content']['body']) ?></p>
<?php foreach(['anamnesis'=>'Anamnesi','findings'=>'Esame / riscontri','diagnosis'=>'Diagnosi','therapy'=>'Terapia','follow_up'=>'Indicazioni e controlli'] as $key=>$label): if(empty($entry['content'][$key])) continue; ?><details><summary><?= esc($label) ?></summary><p><?= esc($entry['content'][$key]) ?></p></details><?php endforeach ?>
<div class="actions">
<?php if($entry['pdf_object_id']): ?><a class="button secondary" href="<?= $download($entry['pdf_object_id']) ?>">Scarica originale PDF</a><?php endif ?>
<?php if($entry['signed_object_id']): ?><a class="button" href="<?= $download($entry['signed_object_id']) ?>">Scarica documento firmato</a><?php endif ?>
<?php if($own && $entry['state']==='draft'): ?><a href="<?= $base.'?edit='.(int)$entry['id'].'#nuovo' ?>">Modifica bozza</a>
<?php if($chart['actor']['role']===1): ?><form method="post" action="<?= $base.'/documenti/'.(int)$entry['id'].'/finalizza' ?>"><?= csrf_field() ?><input type="hidden" name="revision" value="<?= (int)$entry['revision'] ?>"><button>Rendi definitivo</button></form><?php endif ?>
<?php elseif($own): ?><a href="<?= $base.'?revise='.(int)$entry['id'].'#nuovo' ?>">Crea correzione</a><?php endif ?>
</div>
<?php if($own && $entry['state']==='final' && $chart['actor']['role']===1): ?>
<details><summary>Acquisisci firma digitale</summary><p class="help">Scarica l’originale, firmalo con il tuo dispositivo o servizio e carica qui il risultato. La verifica deve confermare contenuto originale, identità del medico, catena e revoca del certificato. La qualifica della firma non è attestata automaticamente da questa verifica.</p>
<form method="post" enctype="multipart/form-data" action="<?= $base.'/documenti/'.(int)$entry['id'].'/firma' ?>"><?= csrf_field() ?>
<label>Formato<select name="format"><option value="pades">PAdES · PDF firmato</option><option value="cades">CAdES · PDF.P7M</option></select></label><label>Documento firmato (massimo 15 MB)<input type="file" name="document" accept=".pdf,.p7m" required></label><button>Verifica e archivia firma</button></form></details><?php endif ?>
</article><?php endforeach ?>
<?php if($chart['total']>25): ?><nav aria-label="Pagine documenti"><?php if($chart['page']>1): ?><a href="<?= $base.'?page='.($chart['page']-1) ?>">← Precedenti</a><?php endif ?><span>Pagina <?= (int)$chart['page'] ?></span><?php if($chart['page']*25<$chart['total']): ?><a href="<?= $base.'?page='.($chart['page']+1) ?>">Successivi →</a><?php endif ?></nav><?php endif ?></section>
<section class="card" id="nuovo"><h2><?= $editing ? 'Modifica bozza' : ($revisionOf ? 'Correzione del documento #'.(int)$revisionOf['id'] : 'Nuovo episodio o documento') ?></h2>
<form method="post" action="<?= $base ?>/salva"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)($editing['id'] ?? 0) ?>"><input type="hidden" name="revision" value="<?= (int)($editing['revision'] ?? 0) ?>"><input type="hidden" name="previous_entry_id" value="<?= (int)($revisionOf['id'] ?? 0) ?>">
<div class="grid"><label>Tipo<select name="kind"><?php foreach(ClinicalRecordService::KINDS as $key=>$label): if($chart['actor']['role']!==1 && $key!=='note') continue; ?><option value="<?= esc($key,'attr') ?>" <?= ($source['kind'] ?? '')===$key ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select></label>
<label>Data e ora della prestazione (Italia)<input type="datetime-local" name="occurred_at" required value="<?= esc(str_replace(' ','T',substr($source['occurred_at'] ?? $now,0,16)),'attr') ?>"></label>
<label class="full">Titolo<input name="title" maxlength="160" required value="<?= esc($content['title'] ?? '','attr') ?>"></label>
<label class="full">Descrizione clinica<textarea name="body" maxlength="40000" required><?= esc($content['body'] ?? '') ?></textarea></label>
<?php if($chart['actor']['role']===1): foreach(['anamnesis'=>'Anamnesi','findings'=>'Esame / riscontri','diagnosis'=>'Diagnosi','therapy'=>'Terapia','follow_up'=>'Indicazioni e controlli'] as $key=>$label): ?><label><?= esc($label) ?><textarea name="<?= esc($key,'attr') ?>" maxlength="20000"><?= esc($content[$key] ?? '') ?></textarea></label><?php endforeach; endif ?>
<label>Appuntamento collegato<select name="appointment_id"><option value="0">Nessun collegamento</option><?php foreach($chart['appointments'] as $appointment): ?><option value="<?= (int)$appointment['id_appuntamento'] ?>" <?= (int)($source['appointment_id'] ?? 0)===(int)$appointment['id_appuntamento'] ? 'selected' : '' ?>>#<?= (int)$appointment['id_appuntamento'] ?> · <?= esc(($appointment['data_slot'] ?? '').' '.($appointment['tipo_visita_label'] ?? $appointment['stato'])) ?></option><?php endforeach ?></select></label></div>
<button>Salva bozza</button> <?php if($source): ?><a href="<?= $base ?>#nuovo">Annulla modifica</a><?php endif ?><p class="help">Il documento resta modificabile finché non viene reso definitivo. Le correzioni successive conservano il documento precedente.</p></form></section>
<section class="card" id="prestazioni"><h2>Storico prestazioni<?= !empty($chart['fse_enabled']) ? ' e referti FSE' : '' ?></h2><div class="table-wrap"><table><thead><tr><th>Appuntamento</th><th>Prestazione</th><th>Stato</th></tr></thead><tbody>
<?php foreach($chart['appointments'] as $appointment): ?><tr><td>#<?= (int)$appointment['id_appuntamento'] ?> · <?= esc(($appointment['data_slot'] ?? '').' '.($appointment['ora_inizio'] ?? '')) ?></td><td><?= esc($appointment['tipo_visita_label'] ?? 'Prestazione') ?><?php if(trim((string)($appointment['motivo_visita'] ?? ''))!==''): ?><br><small><?= esc($appointment['motivo_visita']) ?></small><?php endif ?></td><td><?= esc($appointment['stato']) ?></td></tr><?php endforeach ?></tbody></table></div>
<?php if(!$chart['appointments']): ?><p class="muted">Nessuna prestazione collegata visibile.</p><?php endif ?>
<?php foreach($chart['fse_reports'] as $report): ?><p>Referto FSE #<?= (int)$report['id_fse_document'] ?> · <?= esc($report['document_type'].' · '.$report['service_start'].' · '.$report['local_state']) ?> · <a href="<?= site_url('cartella-clinica/pazienti/'.$patientId.'/referti-fse/'.(int)$report['id_fse_document']) ?>">Scarica PDF disponibile</a></p><?php endforeach ?>
<p class="help">Lo storico riporta gli stati registrati in agenda.<?php if (!empty($chart['fse_enabled'])): ?> I documenti FSE mantengono il proprio percorso di validazione e pubblicazione.<?php endif ?></p></section>
<?php endif ?>
<section class="card" id="allegati"><h2>Allegati <?= !$chart['clinical'] ? 'dei consensi' : 'del paziente' ?></h2>
<?php foreach($chart['objects'] as $object): ?><p><a href="<?= $download($object['id']) ?>"><?= esc($object['name']) ?></a> <small>· <?= esc($object['created_at']) ?><?= $object['entry_id'] ? ' · documento #'.(int)$object['entry_id'] : '' ?></small></p><?php endforeach ?>
<details><summary>Aggiungi documento</summary><form method="post" enctype="multipart/form-data" action="<?= $base ?>/allegati"><?= csrf_field() ?>
<label>Categoria<select name="category"><?php if($chart['clinical']): ?><option value="clinical">Documento clinico</option><?php endif ?><option value="consent">Documento sottoscritto per consenso</option></select></label>
<label>Documento PDF, JPEG o PNG (massimo 15 MB)<input name="document" type="file" accept=".pdf,.jpg,.jpeg,.png" required></label><button>Archivia allegato</button></form></details></section>
<section class="card" id="consensi"><h2>Consensi e informative</h2><p class="help">Ogni scelta è associata a una versione del testo e conserva lo storico. Per registrare un consenso concesso, carica prima il documento sottoscritto nella categoria consensi.</p>
<?php if(!$chart['templates']): ?><p>Nessun modello pubblicato. Il responsabile dello spazio deve inserire i testi utilizzati dalla struttura.</p><?php endif ?>
<?php foreach($chart['templates'] as $template): $head=$latest[$template['kind']] ?? null; ?>
<details class="entry"><summary><?= esc($template['title'].' · versione '.$template['version']) ?> <span class="tag"><?= esc($head && (int)$head['template_id']===(int)$template['id'] ? ($decisions[$head['decision']] ?? $head['decision']) : 'Nessuna scelta attuale per questa versione') ?></span></summary>
<div class="text"><?= esc($template['content']) ?></div>
<form method="post" action="<?= $base ?>/consensi"><?= csrf_field() ?><input name="template_id" type="hidden" value="<?= (int)$template['id'] ?>"><input type="hidden" name="previous_id" value="<?= (int)($head['id'] ?? 0) ?>">
<div class="grid"><label>Scelta<select name="decision"><?php foreach($template['kind']==='privacy_notice' ? ['acknowledged'] : ['granted','denied','revoked'] as $decision): ?><option value="<?= $decision ?>"><?= esc($decisions[$decision]) ?></option><?php endforeach ?></select></label>
<label>Documento sottoscritto<select name="evidence_object_id"><option value="">Seleziona documento</option><?php foreach($chart['objects'] as $object): if($object['category']!=='consent') continue; ?><option value="<?= esc($object['id'],'attr') ?>"><?= esc($object['name']) ?></option><?php endforeach ?></select></label>
<label>Nome e cognome del dichiarante<input name="signer_name" maxlength="160" required></label><label>Qualità del dichiarante<input name="signer_capacity" placeholder="Paziente, genitore, tutore…" maxlength="160" required></label><label class="full">Annotazioni<textarea name="note" maxlength="2000"></textarea></label></div><button>Registra scelta</button></form></details><?php endforeach ?>
<details><summary>Storico completo dei consensi (<?= count($chart['consents']) ?>)</summary><?php foreach($chart['consents'] as $consent): ?><p><?= esc($consent['recorded_at'].' · '.(ClinicalRecordService::CONSENTS[$consent['kind']] ?? $consent['kind']).' · '.($decisions[$consent['decision']] ?? $consent['decision'])) ?><br><small>Modello #<?= (int)$consent['template_id'] ?> · <?= esc($consent['signer']['name'].' · '.$consent['signer']['capacity']) ?> · Operatore #<?= (int)$consent['recorded_by'] ?></small></p><?php endforeach ?></details>
<?php if($chart['manage_templates']): ?><details><summary>Pubblica un modello di consenso</summary><form method="post" action="<?= $base ?>/modelli"><?= csrf_field() ?><div class="grid"><label>Finalità<select name="kind"><?php foreach(ClinicalRecordService::CONSENTS as $key=>$label): ?><option value="<?= $key ?>"><?= esc($label) ?></option><?php endforeach ?></select></label><label>Versione<input name="version" maxlength="32" required></label><label class="full">Titolo<input name="title" maxlength="160" required></label><label class="full">Testo approvato dalla struttura<textarea name="content" maxlength="60000" required></textarea></label></div><button>Pubblica versione</button><p class="help">Il testo pubblicato resta invariato. Per aggiornarlo, pubblica una nuova versione.</p></form></details><?php endif ?>
</section></main></body></html>
