<?php
use App\Services\ClinicalRecordService;
$readOnly=!empty($chart['read_only']);
$fixtureDrafts=!empty($chart['fixture_drafts']);
$canEditClinical=$chart['clinical'] && (!$readOnly || $fixtureDrafts);
$base=site_url('cartella-clinica/pazienti/'.$patientId);
$source=$editing ?? $revisionOf;
$content=$source['content'] ?? [];
$states=['draft'=>'Bozza','final'=>'Definitivo · da firmare','signed'=>'Firma verificata'];
$now=(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Rome')))->format('Y-m-d H:i:s');
$decisions=['granted'=>'Concesso','denied'=>'Negato','revoked'=>'Revocato','acknowledged'=>'Presa visione'];
$latest=[]; foreach($chart['consents'] as $consent) $latest[$consent['kind']] ??= $consent;
$download=static fn($id)=>$base.'/allegati/'.rawurlencode($id);
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cartella del paziente | AmbulatorioFacile</title>
<link rel="stylesheet" href="<?= base_url('public/bootstrap/css/bootstrap.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/dist/css/AdminLTE.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/dist/css/skins/_all-skins.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/fontawesome/css/all.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/fontawesome/css/v4-shims.min.css') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/css/billing-workspace.css?v=20260927-icons') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/css/billing-sections.css?v=20260930-listini') ?>">
<link rel="stylesheet" href="<?= base_url('public/assets/css/clinical-professional.css?v=20261008a') ?>"></head><body class="billing-unified-page skin-blue sidebar-mini"><div class="wrapper">
<?= view('partials/header',['menu_items'=>$menu_items??[]]) ?>
<div class="content-wrapper"><section class="content"><div class="row clinical-shell"><aside class="col-md-3 clinical-menu">
<?= view('partials/sidebar_admin',['menu_items'=>$menu_items??[]]) ?>
</aside><div class="col-md-9 clinical-main"><div class="clinical-content">
<header>
<div class="breadcrumb"><a href="<?= site_url('agenda/gestione-pazienti') ?>">Pazienti</a><i data-icon="right"></i><span><?= esc($patient['patient_name'] ?? '') ?></span><i data-icon="right"></i><span>Cartella clinica</span></div>
<div class="heading"><div><h1>Cartella clinica</h1><p><?= esc($patient['patient_name'] ?? '') ?> <span class="heading-divider">/</span> Storia clinica e percorso di cura</p></div><div class="heading-actions">
<?php if(isset($pacsDemo)): ?><a class="btn" href="<?= $base.'?demo_new=1#pacs-demo' ?>"><i data-icon="scan"></i>Nuovo esame</a><?php elseif(!empty($pacsEnabled) && $chart['actor']['role']===1): ?><a class="btn" href="<?= $base.'/pacs/richieste#nuova-richiesta' ?>"><i data-icon="scan"></i>Nuovo esame</a><?php endif ?>
<?php if($canEditClinical): ?><a class="btn primary" href="<?= $source ? $base.'#nuovo' : '#nuovo' ?>"><i data-icon="plus"></i>Nuovo episodio clinico</a><?php endif ?>
</div></div>
<nav class="tabs" aria-label="Sezioni della cartella"><?php if($chart['clinical']): ?><a href="#documenti"><i data-icon="history"></i>Cronologia</a><a href="#prestazioni"><i data-icon="calendar"></i>Visite e prestazioni</a><?php if(isset($pacsDemo)): ?><a href="#pacs-demo"><i data-icon="scan"></i>Esami e immagini</a><?php elseif(!empty($pacsEnabled)): ?><a href="#diagnostica"><i data-icon="scan"></i>Esami e immagini</a><?php endif ?><?php endif ?><a href="#allegati"><i data-icon="folder"></i>Documenti</a><a href="#consensi"><i data-icon="shield"></i>Consensi</a></nav>
</header>
<div class="clinical-workspace layout">
<aside class="patient-sidebar card patient" aria-label="Anagrafica paziente"><div class="identity"><div class="avatar" aria-hidden="true"><?php $parts=preg_split('/\s+/',trim($patient['patient_name'] ?? 'P')); echo esc(mb_strtoupper(mb_substr($parts[0],0,1).(count($parts)>1?mb_substr(end($parts),0,1):''))); ?></div><h2><?= esc($patient['patient_name'] ?? 'Paziente') ?></h2><?php if(!empty($patient['patient_birth_date'])): ?><p><?= (int)(new \DateTimeImmutable($patient['patient_birth_date']))->diff(new \DateTimeImmutable())->y ?> anni</p><?php endif ?></div>
<div class="patient-details"><dl><dt>Codice fiscale</dt><dd class="cf"><?= esc($patient['patient_tax_code'] ?? '') ?: 'Non disponibile' ?></dd>
<?php if(!empty($patient['patient_birth_date'])): ?><dt>Data di nascita</dt><dd><?= esc(date('d/m/Y',strtotime($patient['patient_birth_date']))) ?></dd><?php endif ?>
<?php foreach(['patient_mobile'=>'Cellulare','patient_phone'=>'Telefono','patient_email'=>'Email'] as $key=>$label): if(empty($patient[$key])) continue; ?><dt><?= esc($label) ?></dt><dd><?= esc($patient[$key]) ?></dd><?php endforeach ?></dl>
<?php if($chart['clinical']): ?><div class="line"></div><h3><i data-icon="heart"></i>Quadro clinico</h3><a class="patient-link" href="#documenti">Consulta la storia clinica<i data-icon="right"></i></a><div class="line"></div><h3><i data-icon="calendar"></i>Appuntamenti</h3><?php $upcoming=array_values(array_filter($chart['appointments'],static fn($a)=>($a['data_slot'] ?? '')>=date('Y-m-d') && ($a['stato'] ?? '')!=='ANNULLATO')); usort($upcoming,static fn($a,$b)=>strcmp(($a['data_slot'] ?? '').($a['ora_inizio'] ?? ''),($b['data_slot'] ?? '').($b['ora_inizio'] ?? ''))); if($upcoming): ?><p class="subtext"><strong><?= esc(date('d/m/Y',strtotime($upcoming[0]['data_slot'])).' · '.substr($upcoming[0]['ora_inizio'] ?? '',0,5)) ?></strong><br><?= esc($upcoming[0]['tipo_visita_label'] ?? 'Visita') ?></p><?php endif ?><a class="patient-link" href="#prestazioni">Visualizza appuntamenti<i data-icon="right"></i></a><?php endif ?></div>
</aside>
<main class="panel">
<?php if($chart['actor']['role']===4 && !$readOnly): ?><p class="notice">Gestione operativa del paziente: puoi registrare consensi, conservare i relativi allegati e aprire la lista diagnostica. La compilazione e la firma dei referti restano ai medici.</p><?php endif ?>
<?php if(session()->getFlashdata('success')): ?><div class="notice" role="status"><?= esc(session()->getFlashdata('success')) ?></div><?php endif ?>
<?php if(isset($pacsDemo)): ?><?= view('clinical/pacs_patient_demo',compact('pacsDemo','patient','patientId','base'),['saveData'=>false]) ?><?php endif ?>
<?php if($chart['clinical']): ?>
<?php if(!empty($pacsEnabled) && !$readOnly): ?><section class="card" id="diagnostica"><h2>Percorso diagnostico</h2><?php if($chart['actor']['role']===1): ?><p><a class="button" href="<?= $base.'/pacs/richieste#nuova-richiesta' ?>">Nuova richiesta per questo paziente</a></p><?php endif ?><p><a href="<?= $base.'/pacs/richieste' ?>">Richieste, stato esami, immagini e referti</a></p><?php if(!empty($pacsRequestsUnavailable)): ?><p class="muted">L’elenco delle richieste non è al momento disponibile.</p><?php else: ?><?php foreach(array_slice($pacsRequests ?? [],0,5) as $request): ?><div class="entry"><a href="<?= $base.'/pacs/richieste/'.$request['id'] ?>"><?= esc($request['payload']['description']) ?></a> · <?= esc($request['accession']) ?><br><span class="tag"><?= esc(['draft'=>'Bozza','ready'=>'Confermata','cancelled'=>'Annullata'][$request['state']]) ?></span> <span class="tag"><?= esc(\App\Services\Pacs\PacsOrderService::STAGES[$request['workflow_stage']]) ?></span></div><?php endforeach ?><?php endif ?><p class="muted">Crea una richiesta da una prestazione in agenda e segui ogni passaggio nello storico della richiesta.</p></section><?php endif ?><section class="card timeline-panel" id="documenti"><div class="section-heading panel-head"><div><h2><?= !empty($focusedDocument) ? 'Documento selezionato' : 'Cronologia clinica' ?> <span class="count"><?= (int)$chart['total'] ?></span></h2><p class="subtitle">Visite, valutazioni e aggiornamenti del percorso</p></div><?php if($canEditClinical): ?><span class="section-symbol"><i data-icon="history"></i></span><?php endif ?></div>
<div class="episode-toolbar toolbar" hidden><label class="search"><i data-icon="search"></i><input type="search" id="episode-search" aria-label="Cerca nella cronologia" placeholder="Cerca diagnosi, terapia o episodio…"></label><select id="episode-state" aria-label="Filtra episodi"><option value="">Tutti gli episodi</option><option value="draft">Bozze</option><option value="final">Definitivi</option><option value="signed">Firmati</option></select><select id="episode-order" aria-label="Ordina episodi"><option value="desc">Più recenti</option><option value="asc">Meno recenti</option></select><select id="episode-paragraph" aria-label="Filtra per paragrafo"><option value="">Tutti i paragrafi</option><?php foreach(['anamnesis'=>'Anamnesi','findings'=>'Esame obiettivo','diagnosis'=>'Diagnosi','therapy'=>'Terapia','follow_up'=>'Controlli'] as $key=>$label): ?><option value="<?= $key ?>"><?= esc($label) ?></option><?php endforeach ?></select></div>
<p class="empty" id="episode-empty" hidden>Nessun episodio corrisponde alla ricerca.</p>
<?php if(!$chart['entries']): ?><p class="empty">Nessun episodio clinico registrato.</p><?php endif ?>
<?php foreach($chart['entries'] as $entry): $own=(int)$entry['author_user_id']===$chart['actor']['user_id']; ?>
<article class="entry episode" data-state="<?= esc($entry['state'],'attr') ?>" data-date="<?= esc($entry['occurred_at'],'attr') ?>" id="episodio-<?= (int)$entry['id'] ?>"><div class="episode-top"><span class="date"><i data-icon="calendar"></i><?= esc(date('d/m/Y · H:i',strtotime($entry['occurred_at']))) ?></span><span class="badge <?= $entry['state']==='draft'?'draft':'' ?>"><i data-icon="<?= $entry['state']==='draft'?'edit':'check' ?>"></i><?= esc($states[$entry['state']] ?? $entry['state']) ?></span></div><h3><?= esc($entry['content']['title']) ?></h3><div class="byline"><i data-icon="doctor"></i><?= esc($entry['author_label'] ?? ClinicalRecordService::KINDS[$entry['kind']] ?? $entry['kind']) ?></div><p class="episode-summary"><?= esc($entry['content']['body']) ?></p><div class="clinical-grid">
<?php foreach(['anamnesis'=>'Anamnesi','findings'=>'Esame / riscontri','diagnosis'=>'Diagnosi','therapy'=>'Terapia','follow_up'=>'Indicazioni e controlli'] as $key=>$label): if(empty($entry['content'][$key])) continue; ?><details open data-paragraph="<?= $key ?>"><summary><?= esc($label) ?></summary><p><?= esc($entry['content'][$key]) ?></p></details><?php endforeach ?>
</div><div class="actions episode-bottom">
<?php if($entry['pdf_object_id']): ?><a class="button secondary" href="<?= $download($entry['pdf_object_id']) ?>"><i data-icon="download"></i>Scarica PDF</a><?php endif ?>
<?php if($entry['signed_object_id']): ?><a class="button" href="<?= $download($entry['signed_object_id']) ?>">Scarica documento firmato</a><?php endif ?>
<?php if($own && $entry['state']==='draft'): ?><a href="<?= $base.'?edit='.(int)$entry['id'].'#nuovo' ?>"><i data-icon="edit"></i>Riprendi compilazione<i data-icon="right"></i></a>
<?php if($chart['actor']['role']===1): ?><form method="post" action="<?= $base.'/documenti/'.(int)$entry['id'].'/finalizza' ?>"><?= csrf_field() ?><input type="hidden" name="revision" value="<?= (int)$entry['revision'] ?>"><button>Rendi definitivo</button></form><?php endif ?>
<?php elseif($own): ?><a href="<?= $base.'?revise='.(int)$entry['id'].'#nuovo' ?>">Crea correzione</a><?php endif ?>
</div>
<?php if($own && $entry['state']==='final' && $chart['actor']['role']===1): ?>
<details><summary>Acquisisci firma digitale</summary><p class="help">Scarica l’originale, firmalo con il tuo dispositivo o servizio e carica qui il risultato. La verifica deve confermare contenuto originale, identità del medico, catena e revoca del certificato. La qualifica della firma non è attestata automaticamente da questa verifica.</p>
<form method="post" enctype="multipart/form-data" action="<?= $base.'/documenti/'.(int)$entry['id'].'/firma' ?>"><?= csrf_field() ?>
<label>Formato<select name="format"><option value="pades">PAdES · PDF firmato</option><option value="cades">CAdES · PDF.P7M</option></select></label><label>Documento firmato (massimo 15 MB)<input type="file" name="document" accept=".pdf,.p7m" required></label><button>Verifica e archivia firma</button></form></details><?php endif ?>
</article><?php endforeach ?>
<?php if($chart['total']>25): ?><nav aria-label="Pagine documenti"><?php if($chart['page']>1): ?><a href="<?= $base.'?page='.($chart['page']-1) ?>">← Precedenti</a><?php endif ?><span>Pagina <?= (int)$chart['page'] ?></span><?php if($chart['page']*25<$chart['total']): ?><a href="<?= $base.'?page='.($chart['page']+1) ?>">Successivi →</a><?php endif ?></nav><?php endif ?></section>
<?php if($canEditClinical): ?><section class="card editor-panel" id="nuovo"><div class="panel-head"><div><h2><?= $editing ? 'Modifica bozza' : ($revisionOf ? 'Correzione del documento' : 'Nuovo episodio clinico') ?></h2><p class="subtitle"><?= esc($patient['patient_name'] ?? '') ?></p></div><a class="back" href="#documenti"><i data-icon="close"></i>Chiudi</a></div>
<form method="post" action="<?= $base ?>/salva"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)($editing['id'] ?? 0) ?>"><input type="hidden" name="revision" value="<?= (int)($editing['revision'] ?? 0) ?>"><input type="hidden" name="previous_entry_id" value="<?= (int)($revisionOf['id'] ?? 0) ?>">
<div class="form-body"><div class="form-title"><i data-icon="file"></i>Dati dell’episodio</div><div class="form-grid"><label class="field">Tipo di episodio<select name="kind"><?php foreach(ClinicalRecordService::KINDS as $key=>$label): if($chart['actor']['role']!==1 && !$fixtureDrafts && $key!=='note') continue; ?><option value="<?= esc($key,'attr') ?>" <?= ($source['kind'] ?? '')===$key ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select></label>
<label class="field">Data e ora<input type="datetime-local" name="occurred_at" required value="<?= esc(str_replace(' ','T',substr($source['occurred_at'] ?? $now,0,16)),'attr') ?>"></label>
<label class="field full">Titolo dell’episodio<input name="title" maxlength="160" required placeholder="Es. Controllo cardiologico" value="<?= esc($content['title'] ?? '','attr') ?>"></label>
<label class="field full">Appuntamento collegato<select name="appointment_id"><option value="0">Nessun appuntamento collegato</option><?php foreach($chart['appointments'] as $appointment): ?><option value="<?= (int)$appointment['id_appuntamento'] ?>" <?= (int)($source['appointment_id'] ?? 0)===(int)$appointment['id_appuntamento'] ? 'selected' : '' ?>><?= esc(($appointment['data_slot'] ?? '').' · '.substr($appointment['ora_inizio'] ?? '',0,5).' — '.($appointment['tipo_visita_label'] ?? $appointment['stato'])) ?></option><?php endforeach ?></select></label></div>
<hr class="form-rule"><div class="form-title"><i data-icon="doctor"></i>Valutazione clinica</div><div class="form-grid"><label class="field full">Motivo della visita<textarea name="body" maxlength="40000" required placeholder="Descrivi il motivo dell’accesso e gli aspetti da approfondire…"><?= esc($content['body'] ?? '') ?></textarea></label>
<?php if($chart['actor']['role']===1 || $fixtureDrafts): foreach(['anamnesis'=>'Anamnesi','findings'=>'Esame obiettivo','diagnosis'=>'Diagnosi / valutazione','therapy'=>'Terapia e indicazioni','follow_up'=>'Controlli successivi'] as $key=>$label): ?><label class="field <?= $key==='diagnosis'?'full':'' ?>"><?= esc($label) ?><textarea name="<?= esc($key,'attr') ?>" maxlength="20000"><?= esc($content[$key] ?? '') ?></textarea></label><?php endforeach; endif ?></div></div>
<div class="form-footer"><small>La bozza può essere completata in un secondo momento.</small><div class="buttons"><a class="btn" href="<?= $base ?>#documenti">Annulla</a><button class="btn primary"><i data-icon="save"></i>Salva bozza</button></div></div></form></section>
<?php endif ?><section class="card" id="prestazioni"><h2>Visite e prestazioni<?= !empty($chart['fse_enabled']) ? ' FSE' : '' ?></h2>
<?php if(!empty($pacsEnabled) || isset($pacsDemo)): ?><div class="exam-launch"><div><strong>Diagnostica e immagini</strong><p class="help">Richiesta, immagini PACS/DICOM e refertazione nel percorso del paziente.</p></div><div class="actions">
<?php if(!empty($pacsEnabled) && $chart['actor']['role']===1): ?><a class="button" href="<?= $base.'/pacs/richieste#nuova-richiesta' ?>">+ Nuovo esame</a><?php endif ?>
<?php if(isset($pacsDemo)): ?><a class="button secondary" href="#pacs-demo">Apri immagini PACS / DICOM</a><?php elseif(!empty($pacsEnabled)): ?><a class="button secondary" href="<?= $base.'/pacs' ?>">Apri immagini PACS / DICOM</a><?php endif ?>
<?php if(isset($pacsDemo)): ?><a class="button secondary" href="<?= $base.'?demo_new=1#pacs-demo' ?>">+ Nuovo esame</a><?php endif ?>
</div></div><?php endif ?>
<div class="table-wrap"><table><thead><tr><th>Appuntamento</th><th>Prestazione</th><th>Stato</th></tr></thead><tbody>
<?php foreach($chart['appointments'] as $appointment): ?><tr><td>#<?= (int)$appointment['id_appuntamento'] ?> · <?= esc(($appointment['data_slot'] ?? '').' '.($appointment['ora_inizio'] ?? '')) ?></td><td><?= esc($appointment['tipo_visita_label'] ?? 'Prestazione') ?><?php if(trim((string)($appointment['motivo_visita'] ?? ''))!==''): ?><br><small><?= esc($appointment['motivo_visita']) ?></small><?php endif ?></td><td><?= esc($appointment['stato']) ?><?php if($canEditClinical): ?><br><a href="#nuovo" data-appointment="<?= (int)$appointment['id_appuntamento'] ?>"><i data-icon="plus"></i>Crea episodio</a><?php endif ?><?php if(!empty($pacsEnabled) && $chart['actor']['role']===1 && in_array((int)$appointment['id_dot'],$pacsAppointmentDoctorIds ?? [],true) && $appointment['stato']!=='ANNULLATO'): ?><br><a href="<?= $base.'/pacs/richieste?appointment='.(int)$appointment['id_appuntamento'] ?>">Richiedi esame</a><?php endif ?></td></tr><?php endforeach ?></tbody></table></div>
<?php if(!$chart['appointments']): ?><p class="muted">Nessuna prestazione collegata visibile.</p><?php endif ?>
<?php foreach($chart['fse_reports'] as $report): ?><p>Referto FSE #<?= (int)$report['id_fse_document'] ?> · <?= esc($report['document_type'].' · '.$report['service_start'].' · '.$report['local_state']) ?> · <a href="<?= site_url('cartella-clinica/pazienti/'.$patientId.'/referti-fse/'.(int)$report['id_fse_document']) ?>">Scarica PDF disponibile</a></p><?php endforeach ?>
<p class="help">Lo storico riporta gli stati registrati in agenda.<?php if (!empty($chart['fse_enabled'])): ?> I documenti FSE mantengono il proprio percorso di validazione e pubblicazione.<?php endif ?></p></section>
<?php endif ?>
<section class="card" id="allegati"><h2>Allegati <?= !$chart['clinical'] ? 'dei consensi' : 'del paziente' ?></h2>
<?php foreach($chart['objects'] as $object): ?><p><a href="<?= $download($object['id']) ?>"><?= esc($object['name']) ?></a> <small>· <?= esc($object['created_at']) ?><?= $object['entry_id'] ? ' · documento #'.(int)$object['entry_id'] : '' ?></small></p><?php endforeach ?>
<details><summary>Aggiungi documento</summary><form method="post" enctype="multipart/form-data" action="<?= $base ?>/allegati"><?= csrf_field() ?>
<label>Categoria<select name="category"><?php if($canEditClinical && !$readOnly): ?><option value="clinical">Documento clinico</option><?php endif ?><option value="consent">Documento sottoscritto per consenso</option></select></label>
<label>Documento PDF, JPEG o PNG (massimo 15 MB)<input name="document" type="file" accept=".pdf,.jpg,.jpeg,.png" required></label><button>Archivia allegato</button></form></details></section>
<section class="card" id="consensi"><h2>Consensi e informative</h2><p class="help">Ogni scelta è associata a una versione del testo e conserva lo storico. Per registrare un consenso concesso, carica prima il documento sottoscritto nella categoria consensi.</p>
<?php if(!$chart['templates']): ?><p>Nessun modello pubblicato. Il responsabile dello spazio deve inserire i testi utilizzati dalla struttura.</p><?php endif ?>
<?php foreach($chart['templates'] as $template): $head=$latest[$template['kind']] ?? null; ?>
<details class="entry"><summary><?= esc($template['title'].' · versione '.$template['version']) ?> <span class="tag"><?= esc($head && (int)$head['template_id']===(int)$template['id'] ? ($decisions[$head['decision']] ?? $head['decision']) : 'Nessuna scelta attuale per questa versione') ?></span></summary>
<div class="text"><?= esc($template['content']) ?></div>
<form method="post" action="<?= $base ?>/consensi"><?= csrf_field() ?><input name="template_id" type="hidden" value="<?= (int)$template['id'] ?>"><input type="hidden" name="previous_id" value="<?= (int)($head['id'] ?? 0) ?>">
<div class="grid"><label>Scelta<select name="decision"><?php foreach($template['kind']==='privacy_notice' ? ['acknowledged'] : ['granted','denied','revoked'] as $decision): ?><option value="<?= $decision ?>"><?= esc($decisions[$decision]) ?></option><?php endforeach ?></select></label>
<label>Documento sottoscritto<select name="evidence_object_id"><option value="">Seleziona documento</option><?php foreach($chart['objects'] as $object): if($object['category']!=='consent') continue; ?><option value="<?= esc($object['id'],'attr') ?>"><?= esc($object['name']) ?></option><?php endforeach ?></select></label>
<label>Nome e cognome del dichiarante<input name="signer_name" maxlength="160" required></label><label>Qualità del dichiarante<input name="signer_capacity" placeholder="Paziente, genitore, tutore…" maxlength="160" required></label><label class="full">Annotazioni<textarea name="note" maxlength="2000"></textarea></label></div><button>Registra scelta</button></form></details><?php endforeach ?>
<details><summary>Storico completo dei consensi (<?= count($chart['consents']) ?>)</summary><?php foreach($chart['consents'] as $consent): ?><p><?= esc($consent['recorded_at'].' · '.(ClinicalRecordService::CONSENTS[$consent['kind']] ?? $consent['kind']).' · '.($decisions[$consent['decision']] ?? $consent['decision'])) ?><br><small>Modello #<?= (int)$consent['template_id'] ?> · <?= esc($consent['signer']['name'].' · '.$consent['signer']['capacity']) ?> · Operatore #<?= (int)$consent['recorded_by'] ?></small></p><?php endforeach ?></details>
<?php if($chart['manage_templates']): ?><details><summary>Pubblica un modello di consenso</summary><form method="post" action="<?= $base ?>/modelli"><?= csrf_field() ?><div class="grid"><label>Finalità<select name="kind"><?php foreach(ClinicalRecordService::CONSENTS as $key=>$label): ?><option value="<?= $key ?>"><?= esc($label) ?></option><?php endforeach ?></select></label><label>Versione<input name="version" maxlength="32" required></label><label class="full">Titolo<input name="title" maxlength="160" required></label><label class="full">Testo approvato dalla struttura<textarea name="content" maxlength="60000" required></textarea></label></div><button>Pubblica versione</button><p class="help">Il testo pubblicato resta invariato. Per aggiornarlo, pubblica una nuova versione.</p></form></details><?php endif ?>
</section></main></div></div></div></div></section></div></div>
<script src="<?= base_url('public/assets/js/billing-workspace.js?v=20260927-icons') ?>"></script>
<script src="<?= base_url('public/assets/js/clinical-workspace.js?v=20261008a') ?>"></script>
<script src="<?= base_url('public/assets/js/clinical-icons.js?v=20261008a') ?>"></script></body></html>
