<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Preparazione moduli clinici | AmbulatorioFacile</title>
<style>body{margin:0;background:#f3f6f8;color:#193345;font:16px/1.6 system-ui}main{max-width:1000px;margin:auto;padding:24px}section,article{background:#fff;border:1px solid #dce5e9;border-radius:12px;padding:24px;margin:20px 0}h1{line-height:1.2}h2{font-size:22px}a{color:#086f75}button{background:#086f75;color:white;border:0;border-radius:6px;padding:12px 18px;font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:default}.ok{color:#136344}.problem{color:#953f0b}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}label{display:block;font-weight:600}input:not([type=checkbox]),select{display:block;box-sizing:border-box;width:100%;padding:10px;border:1px solid #8ea3b0;border-radius:6px;font:inherit}small{display:block;color:#536675}summary{cursor:pointer;font-weight:600}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #dce5e9}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #e69f35;outline-offset:3px}.notice{padding:16px;background:#e3f2ec;border-radius:8px}form>p{margin-bottom:20px}@media(max-width:650px){.grid{grid-template-columns:1fr}main,section,article{padding:16px}td,th{padding:8px}}</style></head><body><main>
<a href="<?= site_url('agenda') ?>">← Agenda</a><h1>Preparazione moduli clinici</h1><p><?= esc($tenant['tenant_name']) ?></p>
<p>Prepara lo spazio, configura i collegamenti e verifica che siano pronti per il collaudo con il fornitore.</p>
<?php if($success=session()->getFlashdata('success')): ?><p class="notice" role="status"><?= esc($success) ?></p><?php endif ?>
<?php if($error): ?><p class="problem" role="alert"><?= esc($error) ?></p><?php endif ?>
<section><h2>1. Prepara lo spazio</h2><p>Cartella clinica abilitata<?= $status['pacs_enabled'] ? ' · PACS/DICOM abilitato' : '' ?>. Le abilitazioni sono gestite dal super master.</p>
<table><thead><tr><th>Controllo</th><th>Stato</th></tr></thead><tbody><?php foreach($status['checks'] as $check): ?><tr><td><?= esc($check['label']) ?><small><?= esc($check['detail']) ?></small></td><td class="<?= $check['ok'] ? 'ok':'problem' ?>"><?= $check['ok'] ? 'Pronto':'Da verificare' ?></td></tr><?php endforeach ?></tbody></table>
<p>La preparazione inizializza gli archivi mancanti dei moduli abilitati e il blocco degli accessi del personale. Puoi ripeterla dopo un aggiornamento; pazienti, documenti e dati già presenti vengono conservati.</p>
<form method="post" action="<?= site_url('cartella-clinica/configurazione/prepara') ?>"><?= csrf_field() ?><button>Prepara lo spazio</button></form></section>
<?php if($status['pacs_enabled']): ?>
<section><h2>2. Configura i collegamenti PACS</h2><p>Usa gli indirizzi DICOMweb HTTPS forniti dal servizio diagnostico. Gli indirizzi devono essere raggiungibili dal cloud. La password o il token non vengono mostrati dopo il salvataggio.</p>
<?php foreach($serverProfiles as $p): ?><p><strong><?= esc($p['label']) ?></strong> — collegamento esistente gestito sul server; resta disponibile.</p><?php endforeach ?>
<?php if(!$error && !empty(array_column($status['checks'],'ok','id')['settings_schema'])): ?>
<?php $forms=$profiles; $forms['__new']=['id'=>'','label'=>'','qido_url'=>'','wado_url'=>'','viewer_url'=>'','identity_namespace'=>'','auth'=>'none','enabled'=>false,'download_enabled'=>false,'revision'=>0]; ?>
<?php foreach($forms as $formKey=>$p): $prefix='profile-'.$formKey.'-'; ?>
<article><details <?= $formKey==='__new' ? 'open':'' ?>><summary><?= $formKey==='__new' ? 'Aggiungi un collegamento' : esc($p['label']).' · '.($p['enabled'] ? 'Attivo':'Disattivo') ?></summary>
<form method="post" autocomplete="off" action="<?= site_url('cartella-clinica/configurazione/pacs') ?>"><?= csrf_field() ?><input type="hidden" name="revision" value="<?= (int)$p['revision'] ?>">
<div class="grid">
<?php foreach(['id'=>'Identificativo collegamento','label'=>'Nome del collegamento','qido_url'=>'Indirizzo ricerca QIDO','wado_url'=>'Indirizzo download WADO','identity_namespace'=>'Ambito identificativi (opzionale)','viewer_url'=>'Visualizzatore esterno (opzionale)'] as $field=>$label): ?>
<p><label for="<?= esc($prefix.$field,'attr') ?>"><?= $label ?></label><input id="<?= esc($prefix.$field,'attr') ?>" name="<?= $field ?>" value="<?= esc($p[$field] ?? '','attr') ?>" <?= in_array($field,['id','label','qido_url','wado_url'],true) ? 'required':'' ?> <?= $field==='id' && $formKey!=='__new' ? 'readonly':'' ?> maxlength="<?= in_array($field,['qido_url','wado_url','viewer_url'],true) ? 2048 : ($field==='id' ? 40:100) ?>">
<?php if($field==='id'): ?><small>Lettere minuscole, numeri, trattino o underscore. Inizia con una lettera.</small><?php elseif($field==='viewer_url'): ?><small>Inserire {study} nel punto previsto per l’identificativo dello studio.</small><?php endif ?></p>
<?php endforeach ?>
<p><label for="<?= esc($prefix.'auth','attr') ?>">Autenticazione</label><select id="<?= esc($prefix.'auth','attr') ?>" name="auth"><?php foreach(['none'=>'Nessuna','basic'=>'Nome utente e password','bearer'=>'Token Bearer'] as $value=>$label): ?><option value="<?= $value ?>" <?= $p['auth']===$value ? 'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></p>
<?php foreach(['username'=>'Nome utente PACS','password'=>'Password PACS','token'=>'Token PACS'] as $field=>$label): ?><p><label for="<?= esc($prefix.$field,'attr') ?>"><?= $label ?></label><input type="password" autocomplete="new-password" id="<?= esc($prefix.$field,'attr') ?>" name="<?= $field ?>" value="" maxlength="4096"><small>Compila solo i campi richiesti dall’autenticazione scelta.</small></p><?php endforeach ?>
</div>
<?php if($formKey!=='__new'): ?><p>Lascia vuote le credenziali per conservarle. Se modifichi gli indirizzi o il tipo di autenticazione, reinseriscile. Cambiando indirizzi o ambito identificativi dovrai verificare nuovamente le associazioni dei pazienti.</p><?php endif ?>
<p><label><input type="checkbox" name="enabled" value="1" <?= $p['enabled'] ? 'checked':'' ?>> Collegamento attivo</label><label><input type="checkbox" name="download_enabled" value="1" <?= $p['download_enabled'] ? 'checked':'' ?>> Consenti download DICOM ai professionisti autorizzati</label></p>
<button>Salva collegamento</button></form></details></article><?php endforeach ?>
<?php else: ?><p>Completa la preparazione dello spazio prima di aggiungere i collegamenti.</p><?php endif ?>
<a href="<?= site_url('cartella-clinica/diagnostica/collegamenti') ?>">Apri verifica collegamenti PACS</a></section><?php endif ?>
<section><h2><?= $status['pacs_enabled'] ? '3':'2' ?>. Esegui il collaudo tecnico</h2><p>La prova scrive e rilegge un piccolo contenuto sintetico cifrato e lo rimuove. Se selezioni un PACS, esegue una ricerca QIDO con identificativo casuale; non crea pazienti o richieste cliniche.</p>
<form method="post" action="<?= site_url('cartella-clinica/configurazione/collaudo') ?>"><?= csrf_field() ?>
<p><label for="check-profile">Collegamento da verificare</label><select id="check-profile" name="profile_id"><option value="">Solo preparazione dello spazio</option><?php foreach($serverProfiles as $p): ?><option value="<?= esc($p['id'],'attr') ?>"><?= esc($p['label']) ?></option><?php endforeach ?><?php foreach($profiles as $p): if(!$p['enabled']) continue; ?><option value="<?= esc($p['id'],'attr') ?>"><?= esc($p['label']) ?></option><?php endforeach ?></select></p>
<button name="download" value="0">Esegui collaudo</button> <button name="download" value="1">Esegui e scarica esito</button></form>
<?php if(is_array($report)): ?><div role="status"><h3><?= $report['ready'] ? 'Controlli selezionati superati':'Controlli da completare' ?></h3><p><?= esc($report['checked_at']) ?></p><ul><?php foreach($report['checks'] as $check): ?><li><?= esc($check['label']) ?>: <strong><?= $check['ok'] ? 'Superato':'Non superato' ?></strong></li><?php endforeach ?></ul><?php if(isset($report['connection'])): ?><p><?= esc($report['connection']['message']) ?></p><?php endif ?><p><?= esc($report['scope']) ?></p></div><?php endif ?>
<h3>Completa il collaudo con il fornitore</h3><ol><li>Concorda un paziente sintetico e la corrispondenza degli identificativi.</li><li>Crea una prenotazione, conferma la richiesta e verifica accettazione ed esecuzione con i profili autorizzati.</li><li>Abbina l’esame e prova serie, download DICOM ed eventuale visualizzatore.</li><li>Finalizza il referto, verifica il PDF e prova una firma con il dispositivo reale.</li><li>Se previsti, verifica worklist e avanzamenti delle apparecchiature con il fornitore.</li></ol><p>Il superamento dei controlli tecnici non attesta l’interoperabilità completa o la qualifica della firma.</p></section>
</main></body></html>
